#!/bin/sh

#-------------------------------------------------------------------------------

deploy()
(
  if [ -f "$LIB_DIR/java-webapp/$1" ] || [ -L "$LIB_DIR/java-webapp/$1" ]
  then
    WAR_FILE="$LIB_DIR/java-webapp/$1"
    WAR_LINK="$1"
  elif [ -f "$LIB_DIR/java-webapp/${1}.war" ] || [ -L "$LIB_DIR/java-webapp/${1}.war" ]
  then
    WAR_FILE="$LIB_DIR/java-webapp/${1}.war"
    WAR_LINK="${1}.war"
  else
    exit 1
  fi
  
  [ -f "$HOME_DIR/standalone/deployments/${WAR_LINK}.undeployed" ] && rm -f "$HOME_DIR/standalone/deployments/${WAR_LINK}.undeployed"
  [ -f "$HOME_DIR/domain/deployments/${WAR_LINK}.undeployed" ] && rm -f "$HOME_DIR/domain/deployments/${WAR_LINK}.undeployed"
  lnk -cfr "$WAR_FILE" "$HOME_DIR/standalone/deployments/$WAR_LINK"
  lnk -cfr "$WAR_FILE" "$HOME_DIR/domain/deployments/$WAR_LINK"
)

#-------------------------------------------------------------------------------

undeploy()
(
  if [ -f "$HOME_DIR/standalone/deployments/$1" ] || [ -L "$HOME_DIR/standalone/deployments/$1" ] || [ -f "$HOME_DIR/domain/deployments/$1" ] || [ -L "$HOME_DIR/domain/deployments/$1" ]
  then
    WAR_LINK="$1"
  elif [ -f "$HOME_DIR/standalone/deployments/${1}.war" ] || [ -L "$HOME_DIR/standalone/deployments/${1}.war" ] || [ -f "$HOME_DIR/domain/deployments/${1}.war" ] || [ -L "$HOME_DIR/domain/deployments/${1}.war" ]
  then
    WAR_LINK="${1}.war"
  else
    exit 1
  fi
  
  rm -f "$HOME_DIR/standalone/deployments/$WAR_LINK"
  rm -f "$HOME_DIR/domain/deployments/$WAR_LINK"
)

#-------------------------------------------------------------------------------

redeploy()
(
  undeploy "$1"
  deploy "$1"
)

#-------------------------------------------------------------------------------

. m-sys.lib.sh
work "wildfly"
export JAVA_OPTS="-Djboss.server.base.dir=$HOME_DIR/standalone -Djboss.domain.base.dir=$HOME_DIR/domain $JAVA_OPTS"
if [ "$1" = "add-user.sh" ]
then
  shift
  set -- "add-user.sh" -sc "$HOME_DIR/standalone/configuration" -dc "$HOME_DIR/domain/configuration" "$@"
elif [ "$1" = "add-user.bat" ]
then
  shift
  set -- "add-user.bat" -sc "$HOME_DIR/standalone/configuration" -dc "$HOME_DIR/domain/configuration" "$@"
elif [ "$1" = "add-user.ps1" ]
then
  shift
  set -- "add-user.ps1" -sc "$HOME_DIR/standalone/configuration" -dc "$HOME_DIR/domain/configuration" "$@"
fi

export PATH="$WILDFLY_HOME/bin:$PATH"

if [ -z "$*" ]
then
#  bash -i
  java8
else
  case "$1" in
    "deploy") "$@";;
    "undeploy") "$@";;
    "redeploy") "$@";;
    *) java8 "$@";;
  esac
fi
