#!/bin/sh

sudo systemctl disable nginx
sudo systemctl stop nginx

sudo apt-get -y install --no-install-recommends wget gnupg ca-certificates lsb-release

wget -O - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
echo "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list
echo "deb http://openresty.org/package/arm64/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list

sudo apt-get update

sudo apt-get -y install openresty
#sudo apt-get -y install --no-install-recommends openresty
