#!/bin/sh

# source_dir="/m/data/music/tmp/test"
source_dir="/m/src/git/m/var/yt-download/music/download_old"
dest_dir="/m/src/git/m/var/yt-download/music/artist_old"

dump_file="/m/src/git/m/var/yt-download/music/_tags.dump"
dump_file_tmp="/m/src/git/m/var/yt-download/music/_tags.dump.tmp"

. arg.lib.sh

#-------------------------------------------------------------------------------

tag_move_files()
{
(
  artist_detected="$1"
  shift

  for k in "$@"
  do
    # echo "file: $k"
    artist="$(ffmpeg -i "$k" 2>&1 | grep -E '^\s*artist\s*\:\s.*$' | awk -F ': ' '{print $2}')"
    echo "$artist ### $k"
    if [ ! "$artist" = "$artist_detected" ]
    then
      echo "---> wrong artist: $artist"
      rm -f "${k}.tmp"
      mv "$k" "${k}.tmp"
      ffmpeg -i "${k}.tmp" -metadata artist="$artist_detected" -codec copy "$k"
      rm -f "${k}.tmp"
    fi
  done

  mkdir -p "$dest_dir/$artist_detected"
  mv -t "$dest_dir/$artist_detected" "${k%/*}"
)
}

#-------------------------------------------------------------------------------

process_line()
{
  if [ -n "$1" ]
  then
    artist="$(ffmpeg -i "$1" 2>&1 | grep -E '^\s*artist\s*\:\s.*$' | awk -F ': ' '{print $2}')"
    album_dir="${1%/*}"
    album_dir="${album_dir##*/}"
  else
    album_dir=""
  fi

  if [ "$album_dir" = "$album_dir_current" ]
  then
    artist_list="$(printf "${artist_list}\n${artist}")"
    files="$files $(quote "$1")"
    # echo "album_dir: $album_dir --- artist: $artist --- file: $@"
  elif [ -z "$album_dir_current" ]
  then
    album_dir_current="$album_dir"
    files="$(quote "$1")"
    # echo "album_dir: $album_dir --- artist: $artist --- file: $@"
  else
    artist_detected="$(echo "$artist_list" | sort | uniq -c | sort -nr | head -1 | sed 's/^\s\+[0-9]\+\s//')"
    echo "detected artist: $artist_detected"
    artist_detected="${artist_detected%%,*}"
    artist_detected="${artist_detected#The }"
    echo "detected artist (first only): $artist_detected"

    # echo "album dir scanned - detected artist: $artist_detected"
    # echo "files: $files"
    eval tag_move_files $(quote "$artist_detected") $files

    album_dir_current="$album_dir"
    artist_list="$artist"
    files="$(quote "$1")"
  fi
}

#-------------------------------------------------------------------------------

process_dump()
{
(
  while IFS= read -r line
  do
    process_line "$line" >> "$2"
  done < "$1"

  process_line >> "$2"
)
}

#-------------------------------------------------------------------------------

find -L "$source_dir" -type f -name '*.mp3' | sort > "$dump_file_tmp"

rm -f "$dump_file"
process_dump "$dump_file_tmp" "$dump_file"
rm -f "$dump_file_tmp"

echo ""
echo "--------------------------------------------------------------------------------"
echo "press ENTER to exit"
read -r EXIT_VAR
