#!/bin/sh

. realpaths.lib.sh
. waituser.lib.sh
. arg.lib.sh
. array.lib.sh

#------------------------------------------------------------------------------

move_rename_file()
{
(
  if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]
  then
    exit 1
  fi

  json="$1"
  shift
  file="$1"
  shift
  dest_dir="$1"
  shift

  dest_dir_artist="$dest_dir/artist"
  dest_dir_playlist="$dest_dir/playlist"

  echo "json=$json"
  echo "file=$file"
  echo "dest_dir=$dest_dir"

  artist="$(cat "$json" | jq -r '.artist')"
  album="$(cat "$json" | jq -r '.album')"
  track="$(cat "$json" | jq -r '.track')"
  track_number="$(cat "$json" | jq -r '.track_number')"
  release_year="$(cat "$json" | jq -r '.release_year')"

  title="$(cat "$json" | jq -r '.title')"
  fulltitle="$(cat "$json" | jq -r '.fulltitle')"
  alt_title="$(cat "$json" | jq -r '.alt_title')"
  creator="$(cat "$json" | jq -r '.creator')"
  playlist_title="$(cat "$json" | jq -r '.playlist_title')"
  playlist_index="$(cat "$json" | jq -r '.playlist_index')"

  # echo "artist=$artist"
  # echo "album=$album"
  # echo "track=$track"
  # echo "track_number=$track_number"
  # echo "release_year=$release_year"

  # echo "title=$title"
  # echo "fulltitle=$fulltitle"
  # echo "alt_title=$alt_title"
  # echo "creator=$creator"
  # echo "playlist_title=$playlist_title"
  # echo "playlist_index=$playlist_index"

  echo ""

  if [ "$artist" = "null" ]
  then
    artist=""
  fi

  if [ "$album" = "null" ]
  then
    album=""
  fi

  if [ "$release_year" = "null" ]
  then
    release_year=""
  fi

  if [ "$track" = "null" ]
  then
    track="$title"
  fi

  if [ "$track_number" = "null" ]
  then
    track_number="$playlist_index"
  fi

  if [ ! "${playlist_title#Album - *}" = "$playlist_title" ]
  then
    is_album="true"
  else
    is_album="false"
  fi

  echo "artist=$artist"
  echo "album=$album"
  echo "track=$track"
  echo "track_number=$track_number"
  echo "release_year=$release_year"
  echo "is_album=$is_album"

  if [ "$is_album" = "true" ]
  then
    dest_dir="$dest_dir_artist/$artist/$release_year - $album"
    dest_file="$track_number - $track"
  else
    dest_dir="$dest_dir_playlist/$playlist_title"
    dest_file="$playlist_index - $title"
  fi

  dest="$dest_dir/$dest_file"
  echo "dest=$dest"
  eval mkdir -p $(quote "$dest_dir")
  eval mv $(quote "$file") $(quote "$dest")

  echo ""
  echo "--------------------------------------------------------------------------------"
  echo ""
  echo ""
)
}

#-------------------------------------------------------------------------------

process_playlist()
{
(
  cd "$1"
  source_dir="$(pwd)"
  dest_dir="/m/data/music"

  for k in *.info.json
  do
    if [ -e "${k%*.info.json}.m4a" ]
    then
      move_rename_file "$source_dir/$k" "$source_dir/${k%*.info.json}.m4a" "$dest_dir"
    elif [ -e "${k%*.info.json}.mp3" ]
    then
      move_rename_file "$source_dir/$k" "$source_dir/${k%*.info.json}.mp3" "$dest_dir"
    fi
  done

  rm -rf "$(pwd)"
)
}

#-------------------------------------------------------------------------------

cd -L -- "${0%/*}"

export PATH="$(pwd):$PATH"

# printf "playlist name to process: "
# read -r pl_name

cd "$(pwd)/music/tmp"

for k in ..?* .[!.]* *
do
  if [ -e "$k" ]
  then
    process_playlist "$k"
  fi
done


# json="/m/data/music/tmp/Pop/01.info.json"
# json="/m/src/git/m/var/yt-dlp/music/tmp/Album_-_VITA_FUSA/1.info.json"
# json="/m/src/git/m/var/yt-dlp/music/tmp/NA/NA.info.json"

# cat "$json" | jq -r '.title'
# cat "$json" | jq '.artists'
# cat "$json" | jq '.release_year'
# cat "$json" | jq '.artist + " - " + .title'

# move-rename-file "$json" "-" "-"

echo ""
echo "--------------------------------------------------------------------------------"
echo "press ENTER to exit"
read -r EXIT_VAR
