#!/bin/sh

#------------------------------------------------------------------------------

quote()
{
  if [ -z "$1" ]
  then
    printf "''"
  fi

  # printf %s\\n "$1" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"
  printf "%s" "$1" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"
}

#------------------------------------------------------------------------------

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]
then
  exit 1
fi

json="$1"
shift
file="$1"
shift
dest_dir="$1"
shift

dest_dir_artist="$dest_dir/artist"
dest_dir_playlist="$dest_dir/playlist"

echo "json=$json"
echo "file=$file"
echo "dest_dir=$dest_dir"

artist="$(cat "$json" | jq -r '.artist')"
album="$(cat "$json" | jq -r '.album')"
track="$(cat "$json" | jq -r '.track')"
track_number="$(cat "$json" | jq -r '.track_number')"
release_year="$(cat "$json" | jq -r '.release_year')"

title="$(cat "$json" | jq -r '.title')"
fulltitle="$(cat "$json" | jq -r '.fulltitle')"
alt_title="$(cat "$json" | jq -r '.alt_title')"
creator="$(cat "$json" | jq -r '.creator')"
playlist_title="$(cat "$json" | jq -r '.playlist_title')"
playlist_index="$(cat "$json" | jq -r '.playlist_index')"

# echo "artist=$artist"
# echo "album=$album"
# echo "track=$track"
# echo "track_number=$track_number"
# echo "release_year=$release_year"

# echo "title=$title"
# echo "fulltitle=$fulltitle"
# echo "alt_title=$alt_title"
# echo "creator=$creator"
# echo "playlist_title=$playlist_title"
# echo "playlist_index=$playlist_index"

echo ""

if [ "$artist" = "null" ]
then
  artist=""
fi

if [ "$album" = "null" ]
then
  album=""
fi

if [ "$release_year" = "null" ]
then
  release_year=""
fi

if [ "$track" = "null" ]
then
  track="$title"
fi

if [ "$track_number" = "null" ]
then
  track_number="$playlist_index"
fi

if [ ! "${playlist_title#Album - *}" = "$playlist_title" ]
then
  is_album="true"
else
  is_album="false"
fi

echo "artist=$artist"
echo "album=$album"
echo "track=$track"
echo "track_number=$track_number"
echo "release_year=$release_year"
echo "is_album=$is_album"

if [ "$is_album" = "true" ]
then
  dest="$dest_dir_artist/$artist/$release_year - $album/$track_number - $track"
else
  dest="$dest_dir_playlist/$playlist_title/$playlist_index - $title"
fi

echo "dest=$dest"
mv "$file" $(quote "$dest")

echo ""
echo "--------------------------------------------------------------------------------"
echo ""
echo ""
