#!/bin/sh

source_dir="/m/src/git/m/var/yt-download/music/tmp"
dest_dir="/m/src/git/m/var/yt-download/music/artist"

dump_file="/m/src/git/m/var/yt-download/music/tags.dump"

. arg.lib.sh

#-------------------------------------------------------------------------------


process_line()
{
  if [ -z "$*" ]
  then
    if [ -z "$file" ]
    then
      echo ""
      return 0
    fi

    album_source_dir="${file%/*}"
    album_dest_dir="${album_source_dir##*/}"
    album_dest_dir="${album_dest_dir#*] }"
    album_dest_dir="$dest_dir/$artist_detected/$album_dest_dir"
    mkdir -p "${album_dest_dir%/*}"
    mv -T "$album_source_dir" "$album_dest_dir"
    echo ""
    return 0
  fi

  if [ ! "$#" = "1" ]
  then
    echo "WRONG NUMBER OF ARGUMENTS!!! n.args: $#"
    exit 1
  fi

  eval set -- $1

  artist_detected="$1"
  shift
  artist="$1"
  shift
  album="$1"
  shift
  file="$1"
  shift

  # if [ ! "$artist" = "$artist_detected" ]
  # then
  #   echo "---> WRONG ARTIST!!! $artist_detected <--- $artist"
  #   rm -f "${file}.tmp"
  #   mv "$file" "${file}.tmp"
  #   # ffmpeg -i "${file}.tmp" -metadata artist="$artist_detected" -codec copy "$file"
  #   ffmpeg -i "${file}.tmp" -metadata artist="$artist_detected" -codec copy "$file" 2>&1 > /dev/null
  #   rm -f "${file}.tmp"
  # fi

  # echo "artist_detected=$artist_detected artist=$artist album=$album file=$file"
  echo "artist_detected=$artist_detected |###| artist=$artist |###| album=$album |###| file=$file"
}

#-------------------------------------------------------------------------------

process_dump()
{
(
  while IFS= read -r line
  do
    process_line "$line"
  done < "$1"

  # process empty line to force detect end of last album
  process_line
)
}

#-------------------------------------------------------------------------------

process_dump "$dump_file"

echo ""
echo "--------------------------------------------------------------------------------"
echo "press ENTER to exit"
read -r EXIT_VAR
