#!/bin/sh

source_dir="/m/src/git/m/var/yt-download/music/tmp"
dest_dir="/m/src/git/m/var/yt-download/music/artist"

dump_file="/m/src/git/m/var/yt-download/music/tags.dump"
dump_file_tmp="/m/src/git/m/var/yt-download/music/tags.dump.tmp"

. arg.lib.sh

#-------------------------------------------------------------------------------

process_line()
{
  if [ ! "$#" = "1" ]
  then
    echo "WRONG NUMBER OF ARGUMENTS!!! n.args: $#"
    exit 1
  fi

  if [ -z "$1" ]
  then
    echo "EMPTY LINE!!!"
    exit 1
  fi

  artist="$(ffmpeg -i "$1" 2>&1 | grep -E '^\s*artist\s*\:\s.*$' | awk -F ': ' '{print $2}')"
  album="$(ffmpeg -i "$1" 2>&1 | grep -E '^\s*album\s*\:\s.*$' | awk -F ': ' '{print $2}')"

  if [ ! "$album" = "$album_current" ]
  then
    echo ""
    album_current="$album"
  fi

  artist_detected="${artist%%,*}"

  artist_detected="$(quote "$artist_detected")"
  artist="$(quote "$artist")"
  album="$(quote "$album")"
  file="$(quote "$1")"

  echo "$artist_detected $artist $album $file"
}

#-------------------------------------------------------------------------------

process_dump()
{
(
  while IFS= read -r line
  do
    process_line "$line" >> "$2"
  done < "$1"
)
}

#-------------------------------------------------------------------------------

find -L "$source_dir" -type f -name '*.mp3' | sort > "$dump_file_tmp"

rm -f "$dump_file"
process_dump "$dump_file_tmp" "$dump_file"
rm -f "$dump_file_tmp"

echo ""
echo "--------------------------------------------------------------------------------"
echo "press ENTER to exit"
read -r EXIT_VAR
