#!/bin/sh

dest_dir="$(pwd)/$(date +"[%Y-%m-%d %H:%M:%S]")"

if [ -z "$1" ]
then
  printf "download url: "
  read -r url

  echo ""
  echo "--------------------------------------------------------------------------------"
  echo "press ENTER to start download"
  echo "--------------------------------------------------------------------------------"
  read -r EXIT_VAR
  echo ""
else
  unattended_download="true"

  url="$1"
  shift

  if [ -n "$1" ]
  then
    dest_dir="$1"
  fi
fi

if [ ! "$url" = "${url#*"/watch?"}" ]
then
  echo "SINGLE SONG DETECTED!"
  url="${url%"&list="*}"
fi

echo "downloading url: $url"

cd -L -- "${0%/*}"
PATH="$(pwd):$PATH"
FFMPEG_DIR="$(command -v ffmpeg)"
FFMPEG_DIR="${FFMPEG_DIR%/ffmpeg}"

yt-dlp \
--extract-audio \
--audio-format mp3 \
--audio-quality 0 \
--abort-on-unavailable-fragments \
--embed-thumbnail \
--convert-thumbnails jpg \
--no-check-certificate \
--add-metadata \
--restrict-filenames \
--ffmpeg-location "$FFMPEG_DIR" \
--output "$dest_dir/$(date +"[%Y-%m-%d %H:%M:%S]") %(album)s/%(playlist_index)s - %(title)s.%(ext)s" "$url"
# --output "$dest_dir/%(artist)s - %(album)s/%(playlist_index)s - %(title)s.%(ext)s" "$url"

EXIT_STATUS="$?"

if [ "$unattended_download" = "true" ]
then
  exit "$EXIT_STATUS"
fi

echo ""
echo "--------------------------------------------------------------------------------"
echo "press ENTER to exit"
read -r EXIT_VAR
