#!/bin/sh

cd -L -- "${0%/*}"

PATH="$(pwd):$PATH"

printf "download list file: "
read -r list

if [ ! -f "$list" ]
then
  echo "list is NOT A FILE!"
  exit 1
fi

printf "download dir ($(pwd)/music/download): "
read -r dest_dir

if [ -z "$dest_dir" ]
then
  dest_dir="$(pwd)/music/download"
fi

# dest_dir="$dest_dir/$(date +"[%Y-%m-%d %H:%M:%S]")"

echo ""
echo "--------------------------------------------------------------------------------"
echo "press ENTER to start download"
echo "--------------------------------------------------------------------------------"
read -r EXIT_VAR
echo ""

for k in $(cat "$list")
do
  if [ "$k" = "${k#http}" ]
  then
    continue
  fi

  echo "processing list element: $k"
  yt-download-url "$k" "$dest_dir"
done

echo ""
echo "--------------------------------------------------------------------------------"
echo "press ENTER to exit"
read -r EXIT_VAR
