#!/bin/sh

cd -L -- "${0%/*}"

PATH="$(pwd):$PATH"
FFMPEG_DIR="$(command -v ffmpeg)"
FFMPEG_DIR="${FFMPEG_DIR%/ffmpeg}"

printf "download url: "
read -r url

echo ""
echo "--------------------------------------------------------------------------------"
echo "press ENTER to start download"
echo "--------------------------------------------------------------------------------"
read -r EXIT_VAR
echo ""

echo "downloading -> $url"

yt-dlp \
--extract-audio \
--audio-format mp3 \
--audio-quality 0 \
--abort-on-unavailable-fragments \
--embed-thumbnail \
--convert-thumbnails jpg \
--no-check-certificate \
--add-metadata \
--write-info-json \
--restrict-filenames \
--ffmpeg-location "$FFMPEG_DIR" \
--output "$(pwd)/music/tmp/$(date +"[%Y-%m-%d %H:%M:%S]") %(playlist_title)s/%(playlist_index)s.%(ext)s" "$url"

echo ""
echo "--------------------------------------------------------------------------------"
echo "press ENTER to exit"
read -r EXIT_VAR
