#!/bin/sh

TYPE="custom"
VERSIONS="latest"
VERSION="latest"

FILE_TYPE="none"

APP_LAUNCHERS="cmd=cmd"
APP_FORK="none"

postinstall()
{
  cat << 'EOF' > "./cmd"
#!/bin/sh

. realpaths.lib.sh
# . waituser.lib.sh

#-------------------------------------------------------------------------------

realpaths

if [ -z "$*" ]
then
  set -- "$(menu gitman rsudo-jobs)"
fi

"$@"

# waituser

EOF

  chmod +x "./cmd"
}
