#!/bin/sh

TYPE="github"
GITHUB_REPO="etcd-io/etcd"
GITHUB_ASSET_NAME_PATTERN="etcd-.*-linux-amd64.tar.gz"

FILE_TYPE="tar.gz"

SYMLINKS="etcd=etcd etcdctl=etcdctl etcdutl=etcdutl etcd-install=etcd-install etcd-uninstall=etcd-uninstall"

SERVICE_EXEC_START="etcd --config-file \"\$PKG_HOME/conf/etcd.conf\""
SERVICE_WORKING_DIR="\$PKG_HOME/data"

postinstall()
{
  #-----------------------------------------------------------------------------
  # CONF
  #-----------------------------------------------------------------------------
  mkdir -p ./conf
  mkdir -p ./data
  cat << EOF > "./conf/etcd.conf"

name: "etcd-main-cluster"
#data-dir: "$(pwd)/data/\${name}.etcd"
#listen-client-urls: "0.0.0.0:2379"
#advertise-client-urls: "127.0.0.1:2379"
#enable-grpc-gateway: true

EOF

}
