#!/bin/sh

TYPE="custom"

LATEST_RELEASE_URL="https://product-details.mozilla.org/1.0/firefox_versions.json"
VERSION=$(wget --no-check-certificate -qO- "$LATEST_RELEASE_URL" | grep "LATEST_FIREFOX_VERSION" | sed 's/.*LATEST_FIREFOX_VERSION": "//g' | sed 's/",.*//g')
DOWNLOAD_URL="https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US"
APP="true"

FILE_TYPE="tar.xz"
SYMLINKS="firefox=firefox"
