#!/bin/sh

TYPE="github"
GITHUB_REPO="geoserver/geoserver"
DOWNLOAD_URL='https://sourceforge.net/projects/geoserver/files/GeoServer/${VERSION}/geoserver-${VERSION}-bin.zip'

FILE_TYPE="zip"
SYMLINKS="geoserver-start=bin/startup.sh geoserver-stop=bin/shutdown.sh"

# MOVE_AND_LINK_CONF_SUBPATHS="'.config/Pulsar' '.local/share' '.pulsar'"

postinstall()
{
  sed -i 's/jetty.http.port=8080/#jetty.http.port=8080/g' start.ini
}
