#!/bin/sh

TYPE="github"
GITHUB_REPO="keycloak/keycloak"
GITHUB_ASSET_NAME_PATTERN="keycloak-.*.tar.gz"

FILE_TYPE="tar.gz"
SYMLINKS="keycloak=bin/kc.sh kcadm=bin/kcadm.sh kcreg=bin/kcreg.sh keycloak-bootstrap-admin=keycloak-bootstrap-admin"

CERT_GEN_NAME="keycloak"
POSTGRES_NAME="keycloak"
SERVICE_EXEC_START="bin/kc.sh start"

postinstall()
{
  #-----------------------------------------------------------------------------
  # BOOTSTRAP ADMIN
  #-----------------------------------------------------------------------------
  cat << 'EOF' > "./keycloak-bootstrap-admin"
#!/bin/sh

keycloak bootstrap-admin user

EOF



  #-----------------------------------------------------------------------------
  # CONF
  #-----------------------------------------------------------------------------
  cat << 'EOF' > "./conf/keycloak.conf"

# https-certificate-file=${kc.home.dir}/cert/keycloak.crt
# https-certificate-key-file=${kc.home.dir}/cert/keycloak.pem
# hostname-strict=false

https-certificate-file=/m/certs/localhost.pem
https-certificate-key-file=/m/certs/localhost.key
hostname=keycloak.local
#hostname=keycloak.local/keycloak
#hostname-admin=admin.keycloak.local
#hostname-debug=true
#proxy-headers=xforwarded

db=postgres
db-username=keycloak
db-password=keycloak
db-url=jdbc:postgresql://localhost:5432/keycloak

EOF



  nano "./conf/keycloak.conf"

  chmod +x "./keycloak-bootstrap-admin"
}
