#!/bin/sh

TYPE="github"
GITHUB_REPO="keycloak/keycloak"
GITHUB_ASSET_NAME_PATTERN="keycloak-.*.tar.gz"

FILE_TYPE="tar.gz"

SYMLINKS="keycloak=bin/kc.sh kcadm=bin/kcadm.sh kcreg=bin/kcreg.sh keycloak-bootstrap-admin=keycloak-bootstrap-admin"

CERT_GEN_NAME="keycloak"

POSTGRES_NAME="keycloak"

SERVICE_EXEC_START="bin/kc.sh start"

postinstall()
{
  #-----------------------------------------------------------------------------
  # BOOTSTRAP ADMIN
  #-----------------------------------------------------------------------------
  cat << 'EOF' > "./keycloak-bootstrap-admin"
#!/bin/sh

keycloak bootstrap-admin user

EOF



  #-----------------------------------------------------------------------------
  # CONF
  #-----------------------------------------------------------------------------
  cat << 'EOF' > "./conf/keycloak.conf"

log=file
#log=console,file

#log-level=all
#log-level=debug
log-level=warn
#log-level=error

#log-console-level=warn

#log-file=data/log/keycloak.log

#-------------------------------------------------------------------------------

https-certificate-file=${kc.home.dir}/cert/keycloak.pem
https-certificate-key-file=${kc.home.dir}/cert/keycloak.key

#-------------------------------------------------------------------------------

db=postgres
db-username=keycloak
db-password=keycloak
db-url=jdbc:postgresql://localhost:5432/keycloak

#-------------------------------------------------------------------------------

#hostname-debug=true

#hostname-strict=false
hostname-strict=true

#http-relative-path=/keycloak

#hostname-debug=true

hostname=keycloak.local
#hostname=keycloak.local/keycloak

#hostname-admin=keycloak-admin.local

#-------------------------------------------------------------------------------

#proxy-trusted-addresses=myserver.local
#proxy-address-forwarding=true
#proxy-headers=xforwarded

EOF



  nano "./conf/keycloak.conf"

  chmod +x "./keycloak-bootstrap-admin"
}
