#!/bin/sh

TYPE="custom"
FILE_TYPE="deb"
SYMLINKS="madedit-orig=bin/madedit"
APP="true"

VERSIONS="0.2.9-1"
VERSION="0.2.9-1"
DOWNLOAD_URL="https://sourceforge.net/projects/madedit/files/MadEdit/MadEdit-0.2.9/madedit_0.2.9-1_amd64.deb"
