#!/bin/sh

TYPE="github"
GITHUB_REPO="LiMinggang/madedit-mod"
DOWNLOAD_URL='https://sourceforge.net/projects/madedit-mod/files/${VERSION}/madedit-mod_${VERSION}-1_amd64_Ubuntu_22_04_2.deb'
APP="true"

FILE_TYPE="deb"
SYMLINKS="madedit=bin/madedit"
