#!/bin/sh

TYPE="github"
GITHUB_REPO="geosolutions-it/MapStore2"
GITHUB_ASSET_NAME_PATTERN="mapstore2-.*-bin.zip"

FILE_TYPE="zip"

SYMLINKS="mapstore-start=mapstore2-startup.sh mapstore-stop=mapstore2-shutdown.sh"

SERVICE_EXEC_START="mapstore-start"
SERVICE_EXEC_STOP="mapstore-stop"
SERVICE_WORKING_DIR="\$PKG_HOME"

postinstall()
{
  true
}
