#!/bin/sh

# TYPE="github"
# GITHUB_REPO="mpv-player/mpv"
# DOWNLOAD_URL='https://deb-multimedia.org/pool/main/m/mpv-dmo/mpv_${VERSION#v}-dmo3_amd64.deb'
#
# FILE_TYPE="deb"
#
# APP_LAUNCHERS="mpv=bin/mpv"
# APP_FORK="screen"



TYPE="github"
GITHUB_REPO="ivan-hc/MPV-appimage"
GITHUB_ASSET_NAME_PATTERN="mpv-Media-Player_.*-archimage5.0-x86_64.AppImage"

FILE_TYPE="AppImage"

APP_LAUNCHERS="mpv=AppRun"
APP_FORK="screen"



# TYPE="github"
# GITHUB_REPO="pkgforge-dev/mpv-AppImage"
# GITHUB_ASSET_NAME_PATTERN="mpv-.*-anylinux-x86_64.AppImage"
#
# FILE_TYPE="AppImage"
#
# APP_LAUNCHERS="mpv=AppDir/AppRun"
# APP_FORK="screen"
