#!/bin/sh

TYPE="github"
GITHUB_REPO="apache/netbeans"
DOWNLOAD_URL='https://dlcdn.apache.org/netbeans/netbeans/${VERSION}/netbeans-${VERSION}-bin.zip'

FILE_TYPE="zip"

APP_LAUNCHERS="netbeans=bin/netbeans"
APP_FORK="screen"
