#!/bin/sh

TYPE="github"
GITHUB_REPO="open-policy-agent/opa"
GITHUB_ASSET_NAME_PATTERN="opa_linux_amd64"

FILE_TYPE="none"
SYMLINKS="opa=opa_linux_amd64"

POSTGRES_NAME="opa"
SERVICE_EXEC_START="opa run"

postinstall()
{
  #-----------------------------------------------------------------------------
  # CONF
  #-----------------------------------------------------------------------------
  mkdir -p "./.opa"
  cat << 'EOF' > "./.opa/config.yaml"



EOF



  nano "./.opa/config.yaml"
}
