#!/bin/sh

TYPE="github"
GITHUB_REPO="openfga/openfga"
GITHUB_ASSET_NAME_PATTERN="openfga_.*_linux_amd64.tar.gz"

FILE_TYPE="tar.gz"

SYMLINKS="openfga=openfga"

POSTGRES_NAME="openfga"

SERVICE_EXEC_START="openfga run"

postinstall()
{
  #-----------------------------------------------------------------------------
  # CONF
  #-----------------------------------------------------------------------------
  mkdir -p "./.openfga"
  cat << 'EOF' > "./.openfga/config.yaml"



EOF



  nano "./.openfga/config.yaml"
}
