#!/bin/sh

TYPE="custom"
# LATEST_RELEASE_URL="https://www.opera.com/it/browsers"
# VERSION=$(wget --no-check-certificate -qO- "$LATEST_RELEASE_URL" | tr "<" "\n" | grep "Version" | sed 's/.*Version //g')
VERSION="129.0.5823.22"
# DOWNLOAD_URL="https://download.opera.com/download/get/?partner=www&opsys=Linux"
# DOWNLOAD_URL="https://download.opera.com/download/get/?id=76794&amp;location=415&amp;nothanks=yes&amp;sub=marine&amp;utm_tryagain=yes"
DOWNLOAD_URL="https://download3.operacdn.com/ftp/pub/opera/desktop/129.0.5823.22/linux/opera-stable_129.0.5823.22_amd64.deb"

FILE_TYPE="deb"

APP_LAUNCHERS="opera=bin/opera"
APP_FORK="screen"

postinstall()
{
  cd "./lib/x86_64-linux-gnu/opera-stable"
  sudo chown root:root ./opera_sandbox
  sudo chmod 4755 ./opera_sandbox
}
