#!/bin/sh

TYPE="custom"
RELEASES_URL="https://download3.operacdn.com/ftp/pub/opera/desktop/"
VERSIONS=$(wget --no-check-certificate -qO- "$RELEASES_URL" | tr "<" "\n" | grep "href" | sed 's|.*href="||g' | sed 's|/">.*||g' | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n)
VERSION="$(echo "$VERSIONS" | tail -n1)"
DOWNLOAD_URL="https://download3.operacdn.com/ftp/pub/opera/desktop/${VERSION}/linux/opera-stable_${VERSION}_amd64.deb"

FILE_TYPE="deb"

APP_LAUNCHERS="opera=bin/opera"
APP_FORK="screen"

postinstall()
{
  cd "./lib/x86_64-linux-gnu/opera-stable"
  sudo chown root:root ./opera_sandbox
  sudo chmod 4755 ./opera_sandbox
}
