#!/bin/sh

TYPE="github"
GITHUB_REPO="ivan-hc/VLC-appimage"
GITHUB_ASSET_NAME_PATTERN="VLC-media-player_.*-archimage5.0-x86_64.AppImage"

FILE_TYPE="AppImage"

APP_LAUNCHERS="vlc=AppRun"
APP_FORK="screen"
