#!/bin/sh

TYPE="github"
GITHUB_REPO="wxMEdit/wxMEdit"
VERSION="3.2"
DOWNLOAD_URL='http://downloads.sourceforge.net/project/wxmedit/${VERSION}/wxmedit_${VERSION}_amd64-icu72.deb'

FILE_TYPE="deb"

APP_LAUNCHERS="wxmedit=bin/wxmedit"
APP_FORK="screen"
