#!/bin/sh

LASTCHANGE_URL="https://api.github.com/repos/denoland/deno/releases/latest"

VERSION=$(wget --no-check-certificate -qO- "$LASTCHANGE_URL" | grep -oP '"tag_name": "\K(.*)(?=")')
VERSION="${VERSION#v}"
DOWNLOAD_URL="https://github.com/denoland/deno/releases/download/v${VERSION}/deno-x86_64-unknown-linux-gnu.zip"
FILE_TYPE="zip"
SYMLINKS="deno=deno"
