#!/bin/bash

log()
{
  tput sc
  tput cup $(("$TERM_ROWS")) 0
  echo -n "$@" 1>&2
  tput rc
}

printline()
{
  echo "$@" 1>&2
}

load_fav_paths()
{
  FAV_FILE="$1"

  FILES_ARRAY=(".")
  for k in $(cat "$FAV_FILE")
  do
    FILES_ARRAY+=("$k")
  done
}

load_dir()
{
  DIR="$1"
  DIR="$(cd -L -- "$DIR" && pwd -L)"
  cd "$DIR"

  FILES_ARRAY=("..")
  for k in *
  do
    FILES_ARRAY+=("$k")
  done
}

select_dir()
{
  SELECTED_FILE="${FILES_ARRAY[$((FILE_ARRAY_POS + CURSOR_POS))]}"
  # log "selected: $SELECTED_FILE"
  if [ -d "$SELECTED_FILE" ]
  then
    load_dir "$SELECTED_FILE"
    CURSOR_POS="0"
    FILE_ARRAY_POS="0"
    update_screen_list 0
    tput cup 0 0
  # else
  #   log "selected: $SELECTED_FILE is not a directory"
  fi
}

return_dir()
{
  SELECTED_FILE="${FILES_ARRAY[$((FILE_ARRAY_POS + CURSOR_POS))]}"
  
  if [ -d "$SELECTED_FILE" ]
  then
    echo "$SELECTED_FILE"
    exit 0
  else
    log "selected: $SELECTED_FILE is not a directory"
  fi
}

update_screen_vars()
{
  TERM_ROWS="$(tput lines)"
  TERM_COLS="$(tput cols)"
  ROWS="$((TERM_ROWS - 6))"
  COLS="$((TERM_COLS - 1))"
}

update_screen_list()
{
  tput sc

  update_screen_vars
  tput clear
  tput cup 0 0

  INDEX_START=$1
  INDEX_END=$((ROWS+$1))
  if [ "$INDEX_END" -gt "${#FILES_ARRAY[@]}" ]
  then
    INDEX_END="${#FILES_ARRAY[@]}"
  fi

  for (( i=INDEX_START; i<INDEX_END; i++ ));
  do
    # printline "${FILES_ARRAY[i]}"
    if [ -d "${FILES_ARRAY[i]}" ]
    then
      line=" [D]"
    elif [ -f "${FILES_ARRAY[i]}" ]
    then
      line=" [F]"
    fi
    # line="----------------------------------------------------------------------------------------------------------------$line"
    line="$line ${FILES_ARRAY[i]}"
    size=${#line}
    if [ "$size" -gt $((COLS -6)) ]
    then
      line="${line:0:$((COLS -6))} [...]"
    fi
    printline "$line"
  done

  printline "--------------------------------------------------------------------------------"
  printline "$DIR"
  printline "--------------------------------------------------------------------------------"
  printline "number of items: ${#FILES_ARRAY[@]}"
  printline "--------------------------------------------------------------------------------"

  tput rc
}

scroll_cursor()
{
  if [ -z "$CURSOR_POS" ]
  then
    CURSOR_POS="0"
  fi

  if [ -z "$FILE_ARRAY_POS" ]
  then
    FILE_ARRAY_POS="0"
  fi

  CURSOR_POS=$((CURSOR_POS + $1))

  UPDATE_SCREEN=false
  if [ "$CURSOR_POS" -lt "0" ]
  then
    FILE_ARRAY_POS=$((FILE_ARRAY_POS + $1))
    CURSOR_POS=0
    UPDATE_SCREEN=true
  elif [ "$CURSOR_POS" -gt "$(($ROWS - 1))" ]
  then
    FILE_ARRAY_POS=$((FILE_ARRAY_POS + $1))
    CURSOR_POS="$(($ROWS - 1))"
    UPDATE_SCREEN=true
  fi

  if [ "$FILE_ARRAY_POS" -lt "0" ]
  then
    FILE_ARRAY_POS=0
    # UPDATE_SCREEN=false
  elif [ "$FILE_ARRAY_POS" -gt "$((${#FILES_ARRAY[@]} - ROWS -1))" ]
  then
    FILE_ARRAY_POS="$((${#FILES_ARRAY[@]} - ROWS -1))"
    # UPDATE_SCREEN=false
  fi

  if [ "$UPDATE_SCREEN" = true ]
  then
    update_screen_list $((FILE_ARRAY_POS))
  #   log "screen updated"
  # else
  #   log "screen NOT updated"
  fi

  tput cup $CURSOR_POS 0
}

key_loop()
{
  while true
  do
    IFS= read -rsn1 key
    if [ "$key" = $'\E' ]
    then
      IFS= read -rsn2 key
    fi

    case "$key" in
      "q") tput clear; exit 0;;
      "[A") scroll_cursor -1;;
      "[B") scroll_cursor +1;;
      "[C") log "RIGHT";;
      "[D") log "LEFT";;
      "") select_dir;;
      " ") return_dir;;
  #    *) exit 1;;
    esac
  done
}

if [ -z "$1" ]
then
  load_dir "."
elif [ -d "$1" ]
then
  load_dir "$1"
elif [ -f "$1" ]
then
  load_fav_paths "$1"
fi

update_screen_list 0
key_loop
