#!/bin/bash

cursor_addressing_mode_enter()
{
  tput sc
  tput smcup
  tput clear
}

cursor_addressing_mode_exit()
{
  tput clear
  tput rmcup
  tput rc
}

quit()
{
  cursor_addressing_mode_exit
  if [ -z "$1" ]
  then
    exit 0
  else
    exit "$1"
  fi
}

printline()
{
  echo "$@" 1>&2
}

log()
{
  tput sc
  tput cup $(("$TERM_ROWS")) 0
  tput setab 7
  printf "$@" 1>&2
  tput rc
}

vars_init()
{
  ARRAY_POS="0"
  CURSOR_POS="0"
}

update_screen_vars()
{
  TERM_ROWS="$(tput lines)"
  TERM_COLS="$(tput cols)"

  ROWS="$(($TERM_ROWS - 6))"
  COLS="$(($TERM_COLS - 6))"

  if [ "${#ARRAY[@]}" -lt "$ROWS" ]
  then
    ROWS="${#ARRAY[@]}"
  fi
}

list_load()
{
  # fills the array to display from file, from ls, etc
  true
}

list_reset()
{
  ARRAY=()
}

list_size()
{
  echo "${#ARRAY[@]}"
}

list_add()
{
  ARRAY+=("$@")
}

list_rem()
{
  true
}

load_fav_paths()
{
  ARRAY=(".")
  for k in $(cat "$1")
  do
    ARRAY+=("$k")
  done

  vars_init
}

load_dir()
{
  DIR="$(cd -L -- "$1" && pwd -L)"
  cd "$DIR"

  if [ "$DIR" = "/" ]
  then
    ARRAY=()
  else
    ARRAY=("..")
  fi

  for k in ..?* .[!.]* *
  do
    if [ -e "$k" ]
    then
      ARRAY+=("$k")
    fi
  done

  vars_init
}

select_dir()
{
  SELECTED_FILE="${ARRAY[$((ARRAY_POS + CURSOR_POS))]}"
  # log "selected: $SELECTED_FILE"
  if [ -d "$SELECTED_FILE" ]
  then
    load_dir "$SELECTED_FILE"
    CURSOR_POS="0"
    ARRAY_POS="0"
    update_screen_list 0
    tput cup 0 0
  # else
  #   log "selected: $SELECTED_FILE is not a directory"
  fi
}

return_dir()
{
  SELECTED_FILE="$(pwd)/${ARRAY[$((ARRAY_POS + CURSOR_POS))]}"

  if [ -d "$SELECTED_FILE" ]
  then
    SELECTED_FILE="$(cd -L -- "$SELECTED_FILE" && pwd -L)"
    echo "$SELECTED_FILE"
    if [ -n "$OUTPUT_FILE" ]
    then
      echo "$SELECTED_FILE" > "$OUTPUT_FILE"
    fi

    quit
  else
    log "selected: $SELECTED_FILE is not a directory"
  fi
}

update_screen_list()
{
  update_screen_vars
  tput clear

  INDEX_START=$1
  INDEX_END=$((ROWS+$1))
  if [ "$INDEX_END" -gt "${#ARRAY[@]}" ]
  then
    INDEX_END="${#ARRAY[@]}"
  fi

  for (( i=INDEX_START; i<INDEX_END; i++ ))
  do
    if [ -d "${ARRAY[i]}" ]
    then
      line=" [D]"
    elif [ -f "${ARRAY[i]}" ]
    then
      line=" [F]"
    fi

    # line="----------------------------------------------------------------------------------------------------------------$line"
    line="$line ${ARRAY[i]}"
    size="${#line}"
    if [ "$size" -gt "$COLS" ]
    then
      line="${line:0:$COLS} [...]"
    fi
    printline "$line"
  done

  printline "--------------------------------------------------------------------------------"
  printline " $DIR"
  printline "--------------------------------------------------------------------------------"
  printline " number of items: ${#ARRAY[@]}"
  printline "--------------------------------------------------------------------------------"

  tput cup "$CURSOR_POS" 0
}

scroll_cursor()
{
  CURSOR_POS="$(($CURSOR_POS + $1))"

  UPDATE_SCREEN="false"

  if [ "$CURSOR_POS" -lt "0" ]
  then
    ARRAY_POS="$(($ARRAY_POS + $1))"
    CURSOR_POS="0"
    UPDATE_SCREEN="true"
  elif [ "$CURSOR_POS" -gt "$(($ROWS - 1))" ]
  then
    ARRAY_POS="$(($ARRAY_POS + $1))"
    CURSOR_POS="$(($ROWS - 1))"
    UPDATE_SCREEN="true"
  fi

  if [ "$ARRAY_POS" -lt "0" ]
  then
    ARRAY_POS=0
    # UPDATE_SCREEN=false
  elif [ "$ARRAY_POS" -gt "$((${#ARRAY[@]} - $ROWS))" ]
  then
    ARRAY_POS="$((${#ARRAY[@]} - $ROWS))"
    # UPDATE_SCREEN=false
  fi

  if [ "$UPDATE_SCREEN" = true ]
  then
    update_screen_list $((ARRAY_POS))
  fi

  tput cup $CURSOR_POS 0
}

key_loop()
{
  while true
  do
    IFS= read -rsn1 key
    if [ "$key" = $'\E' ]
    then
      IFS= read -rsn2 key
    fi

    case "$key" in
      "q") quit;;
      "[A") scroll_cursor -1;;
      "[B") scroll_cursor +1;;
      # "[C") log "RIGHT";;
      # "[D") log "LEFT";;
      "") select_dir;;
      " ") return_dir;;
  #    *) exit 1;;
    esac
  done
}

screen_init()
{
  cursor_addressing_mode_enter

  # fix fo initial wrong values of size from tput
  tput clear
  for k in {0..999}
  do
    echo -n "                                                 " 1>&2
  done
  tput clear

  # update_screen_vars
  # echo "rows: $ROWS, term rows: $TERM_ROWS, cols: $COLS, term cols: $TERM_COLS"
  # read x
}

main()
{
  # resolving symlink if any
  if [ -L "$0" ]
  then
    THIS_PATH="$(ls -ld -- "$0")"
    THIS_PATH="${THIS_PATH#*" $0 -> "}"
  else
    THIS_PATH="$0"
  fi

  # resolving this file and dir
  THIS_FILE="${THIS_PATH##*/}"
  THIS_DIR="$(cd -P -- "${THIS_PATH%/*}" && pwd -P)"

  if [ -z "$1" ]
  then
    load_dir "."
  elif [ -d "$1" ]
  then
    load_dir "$1"
  elif [ -f "$1" ]
  then
    load_fav_paths "$1"
  fi

  if [ -n "$2" ]
  then
    OUTPUT_FILE="$2"
  else
    OUTPUT_FILE="$THIS_DIR/$THIS_FILE.sel"
  fi

  screen_init
  update_screen_list 0
  key_loop
}

main "$@"
