#!/bin/sh

GIT_ASKPASS_DIR="/m/env"
GIT_ASKPASS_CMD="git-askpass"

if [ -f "$GIT_ASKPASS_DIR/$GIT_ASKPASS_CMD" ]
then
  echo "--------------------------------------------------------------------------------"
  echo "GIT ASKPASS FILE FOUND: $GIT_ASKPASS_DIR/$GIT_ASKPASS_CMD"
  echo "--------------------------------------------------------------------------------"

  export SSH_ASKPASS="$GIT_ASKPASS_DIR/$GIT_ASKPASS_CMD"
  export GIT_ASKPASS="$SSH_ASKPASS"

  export GIT_SSH_COMMAND="setsid ssh"

  export DISPLAY=:0
else
  echo "--------------------------------------------------------------------------------"
  echo "NO GIT ASKPASS FILE FOUND: $GIT_ASKPASS_DIR/$GIT_ASKPASS_CMD"
  echo "--------------------------------------------------------------------------------"
#  read -p "press ENTER to exit" EXIT_VAR
#  exit 1
fi

