#!/bin/sh

GIT_ASKPASS_CONF_FILE="git-askpass.conf"

if [ -L "$0" ]
then
  THIS_PATH="$(ls -ld -- "$0")"
  THIS_PATH="${THIS_PATH#*" $0 -> "}"
else
  THIS_PATH="$0"
fi

THIS_FILE="${THIS_PATH##*/}"

THIS_DIR="$(cd -P -- "${THIS_PATH%/*}" && pwd -P)"

PATH="$THIS_DIR:$PATH"

if [ "$1" = "askpass" ]
then
  shift
  echo "configuring askpass..."

  if [ -f "./$GIT_ASKPASS_CONF_FILE" ]
  then
    echo "importing git askpass configuration: $(pwd)/$GIT_ASKPASS_CONF_FILE"
    . "./$GIT_ASKPASS_CONF_FILE"
  elif [ -f "$THIS_DIR/$GIT_ASKPASS_CONF_FILE" ]
  then
    echo "importing git askpass configuration: $THIS_DIR/$GIT_ASKPASS_CONF_FILE"
    . "$THIS_DIR/$GIT_ASKPASS_CONF_FILE"
  else
    echo "no git askpass configuration!"
  fi
fi

if [ ! -d "./.git" ]
then
  cd "$THIS_DIR"
  while [ ! -d "./.git" ] && [ "$(pwd)" != "/" ]
  do
    cd ..
  done
fi

if [ -d "./.git" ]
then
  echo "--------------------------------------------------------------------------------"
  echo "GIT REPOSITORY FOUND: $(pwd)"
  echo "--------------------------------------------------------------------------------"
else
  echo "--------------------------------------------------------------------------------"
  echo "NO GIT REPOSITORY FOUND: $(pwd)"
  echo "--------------------------------------------------------------------------------"
  read -p "press ENTER to exit" EXIT_VAR
  exit 1
fi

GIT_CMD_COMMAND="$1"
shift

"$THIS_DIR/$GIT_CMD_COMMAND" "$@"
