#!/bin/sh

LASTCHANGE_URL="https://dl.google.com/linux/chrome/deb/dists/stable/main/binary-amd64/Packages"

VERSION=$(curl -sSf "$LASTCHANGE_URL" | grep -A1 "Package: google-chrome-stable" | awk '/Version/{print $2}' | cut -d '-' -f1)
DOWNLOAD_URL="https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${VERSION}_amd64.deb"
DOWNLOAD_URL="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
FILE_TYPE="deb"

postinstall()
(
  cd ./latest/opt/google/chrome
  sudo chown root:root ./chrome-sandbox
  sudo chmod 4755 ./chrome-sandbox
)
