#!/bin/sh

#CONF=DEBUG
#CONF=RELEASE
#TARGET_CPU=x86
#TARGET_CPU=AMD64
#TARGET_OS=WIN
#TARGET_OS=LINUX
#TARGET_OS=OSX
#TARGET_ARCHITECTURE=32
#TARGET_ARCHITECTURE=64
#SYS_COMPILER=GCC
#SYS_COMPILER=Cygwin
#SYS_COMPILER=MinGW
#SYS_COMPILER=MinGW64

CONF=DEBUG
TARGET_CPU=AMD64
TARGET_OS=LINUX
TARGET_ARCHITECTURE=64
SYS_COMPILER=GCC
