@echo off

REM set CONF=DEBUG
REM set CONF=RELEASE
REM set TARGET_CPU=x86
REM set TARGET_CPU=AMD64
REM set TARGET_OS=WIN
REM set TARGET_OS=LINUX
REM set TARGET_OS=OSX
REM set TARGET_ARCHITECTURE=32
REM set TARGET_ARCHITECTURE=64
REM set SYS_COMPILER=GCC
REM set SYS_COMPILER=Cygwin
REM set SYS_COMPILER=MinGW
REM set SYS_COMPILER=MinGW64

set CONF=DEBUG
set TARGET_CPU=AMD64
set TARGET_OS=WIN
set TARGET_ARCHITECTURE=32
set SYS_COMPILER=MinGW
