#!/bin/sh

. m-sys.lib.sh
work "wildfly"
export JAVA_OPTS="-Djboss.server.base.dir=$HOME_DIR/standalone -Djboss.domain.base.dir=$HOME_DIR/domain $JAVA_OPTS"

if [ "$SYS_OS_TYPE" = "windows" ]
then
  unset TMP
  unset TEMP
  "$WILDFLY_HOME/bin/domain.bat" "$@" 1>>"$LOG_DIR/stdout.log" 2>&1 &
  PID=$!
  echo $PID>"$HOME_DIR/wildfly-domain.pid"
else
#  "$WILDFLY_HOME/bin/domain.sh" -Djboss.server.base.dir="$HOME_DIR/standalone" -Djboss.domain.base.dir="$HOME_DIR/domain" "$@" 1>>"$LOG_DIR/stdout.log" 2>&1 &
  "$WILDFLY_HOME/bin/domain.sh" "$@" 1>>"$LOG_DIR/stdout.log" 2>&1 &
  PID=$!
  echo $PID>"$HOME_DIR/wildfly-domain.pid"
fi
