#!/bin/sh

. realpaths.lib.sh
. waituser.lib.sh

#-------------------------------------------------------------------------------

# resolve caller dir
CALL_DIR="$(cd -L -- "${0%/*}" && pwd -L)"

# resolve caller symlink
if [ -L "$0" ]
then
  THIS_PATH="$(ls -ld -- "$0")"
  THIS_PATH="${THIS_PATH#*" $0 -> "}"
else
  THIS_PATH="$0"
fi

# actual called file and dir from resolved path
THIS_FILE="${THIS_PATH##*/}"
THIS_DIR="$(cd -P -- "${THIS_PATH%/*}" && pwd -P)"

# set path
PATH="$CALL_DIR:$THIS_DIR:$PATH"

for k in "$THIS_DIR"/*
do
  if [ -d "$k" ]
  then
    PATH="$k:$PATH"
  fi
done

for k in "${THIS_DIR}/${THIS_FILE}-"*".test"
do
  if [ -f "$k" ]
  then
    echo "importing test file: $k"
    . "$k"
  fi
done

if [ -z "$*" ]
then
  echo "no test argument passed!"
  if [ -f "${THIS_DIR}/${THIS_FILE}.conf" ]
  then
    echo "reading test to perform from conf!"
    set -- "$(cat "${THIS_DIR}/${THIS_FILE}.conf")"
  else
    echo "no test conf available!"
    exit 1
  fi
fi

test_"$@"

waituser
