#!/bin/sh

. realpaths.lib.sh
. waituser.lib.sh

#-------------------------------------------------------------------------------

realpaths

echo "CALL_DIR=$CALL_DIR"
echo "THIS_PATH=$THIS_PATH"
echo "THIS_DIR=$THIS_DIR"
echo "THIS_FILE=$THIS_FILE"
echo "PATH=$PATH"

for k in "${THIS_DIR}/${THIS_FILE}-"*".test"
do
  if [ -f "$k" ]
  then
    echo "importing test file: $k"
    . "$k"
  fi
done

if [ -z "$*" ]
then
  echo "no test argument passed!"
  if [ -f "${THIS_DIR}/${THIS_FILE}.conf" ]
  then
    echo "reading test to perform from conf!"
    set -- "$(cat "${THIS_DIR}/${THIS_FILE}.conf")"
    echo "${THIS_DIR}/${THIS_FILE}.conf -> '$1'"
  else
    echo "no test conf available!"
    exit 1
  fi
fi

echo "launching TEST=test_$@"
test_"$@"

waituser
