#!/bin/sh

get_desktop_apps()
{
  set -- "aa" "bb"

  # for k in ..?* .[!.]* *
  # do
  #   if [ -e "$k" ] && [ -f "./$k/$k.desktop" ]
  #   then
  #     FILES_ARRAY+=("$k")
  #   fi
  # done
}

CALL_DIR="$(cd -L -- "${0%/*}" && pwd -L)"

# resolve symlink caller
if [ -L "$0" ]
then
  THIS_PATH="$(ls -ld -- "$0")"
  THIS_PATH="${THIS_PATH#*" $0 -> "}"
else
  THIS_PATH="$0"
fi

# actual name and dir from resolved path
THIS_FILE="${THIS_PATH##*/}"
THIS_DIR="$(cd -P -- "${THIS_PATH%/*}" && pwd -P)"

# set path
PATH="$CALL_DIR:$THIS_DIR:$PATH"

. "$THIS_DIR/app.conf"

cd "$APPS_SCRIPT_DIR"

set --
for k in ..?* .[!.]* *
do
  if [ -e "$k" ] && [ -f "./$k/$k.desktop" ]
  then
    set -- "$@" "$k"
  fi
done

menu "$@"
eval "SELECTED_APP=\"\$$(($? + 1))\""

menu "install '$SELECTED_APP' desktop file" "uninstall '$SELECTED_APP' desktop file"

if [ "$?" = "0" ]
then
  sudo rm -f "/usr/share/applications/$SELECTED_APP"
  sudo cp "./$SELECTED_APP/$SELECTED_APP.desktop" "/usr/share/applications"
else
  sudo rm -f "/usr/share/applications/$SELECTED_APP"
fi

read -p "press ENTER to exit" test
