#!/bin/sh

VERSION="1.127.1"
DOWNLOAD_URL="https://download.pulsar-edit.dev/?os=linux&type=linux_tar"
DOWNLOAD_URL="https://github.com/pulsar-edit/pulsar/releases/download/v${VERSION}/Linux.pulsar-${VERSION}.tar.gz"
FILE_TYPE="tar.gz"

postinstall()
{
  sudo chown root:root ./latest/chrome-sandbox
  sudo chmod 4755 ./latest/chrome-sandbox
}

