#!/bin/sh

sudo -s << SUDO

KEYCLOAK_PKG_HOME="/m/src/git/m/cmd/pkg/zzz/pkg/keycloak-26.4.0/keycloak-26.4.0"
KEYCLOAK_HOME=""
if [ -z "" ]
then
  KEYCLOAK_HOME="/opt/keycloak"
fi

systemctl stop keycloak
systemctl disable keycloak
rm -f "/etc/systemd/system/keycloak.service"
systemctl daemon-reload
systemctl reset-failed

GROUP="admino adm cdrom sudo dip plugdev users lpadmin"
GROUP=""
chown -R "admino:" ""
userdel -r keycloak
groupdel keycloak

umount ""

SUDO

