#!/bin/sh

sudo -s << SUDO

KEYCLOAK_PKG_HOME="/m/src/git/m/cmd/pkg/zzz/pkg/keycloak-26.4.0/keycloak-26.4.0"

echo "Enter virtual path where service is mapped with mount bind (default: /opt/keycloak)"
read KEYCLOAK_HOME
if [ -z "" ]
then
  KEYCLOAK_HOME="/opt/keycloak"
fi

echo "" > "/KEYCLOAK_VIRTUAL_HOME"
mkdir -p ""
mount --bind "" ""

groupadd keycloak
useradd -r -g keycloak -d "" -s /sbin/nologin keycloak
chown -R keycloak:keycloak ""
#chmod -R o+rwx ""

cp "/keycloak.service" "/etc/systemd/system/keycloak.service"
chown root:root "/etc/systemd/system/keycloak.service"
chmod 644 "/etc/systemd/system/keycloak.service"
systemctl daemon-reload
systemctl enable keycloak

SUDO

