#!/bin/sh

#-------------------------------------------------------------------------------

exist_function()
{
  type "$1">/dev/null 2>&1
}

#-------------------------------------------------------------------------------

wait_user()
{
  EXIT_CODE="$?"

  # wait user input to terminate
  echo ""
  echo "--------------------------------------------------------------------------------"
  echo "EXIT_CODE=$EXIT_CODE"
  echo "--------------------------------------------------------------------------------"
  read -p "press ENTER to exit" test

  exit "$EXIT_CODE"
}

#-------------------------------------------------------------------------------

update()
{
  . "${APP_SCRIPT_DIR}/${APP_NAME}-${COMMAND}"

  DOWNLOAD_FILE="${APP_NAME}-${VERSION}.${FILE_TYPE}"
  echo "latest VERSION is $VERSION"
  if [ -d "$VERSION" ]
  then
    echo "already have latest version"
  else
    rm -rf $VERSION
    mkdir $VERSION
    cd $VERSION
    echo "fetching $DOWNLOAD_URL"
    #curl -# "$DOWNLOAD_URL" > "$DOWNLOAD_FILE"
    wget -O "$DOWNLOAD_FILE" "$DOWNLOAD_URL"
    echo "unpacking..."
    if [ "$FILE_TYPE" = "zip" ]
    then
      unzip "$DOWNLOAD_FILE"
    elif [ "$FILE_TYPE" = "tar.gz" ] || [ "$FILE_TYPE" = "tgz" ] || [ "$FILE_TYPE" = "tar" ] || [ "$FILE_TYPE" = "gzip" ] || [ "$FILE_TYPE" = "bzip" ] || [ "$FILE_TYPE" = "xz" ]
    then
      tar xvf "$DOWNLOAD_FILE"
    elif [ "$FILE_TYPE" = "deb" ]
    then
      dpkg-deb -x "$DOWNLOAD_FILE" ./
    else
      echo "unknown file type: FILE_TYPE=$FILE_TYPE"
      exit 1
    fi
    rm "$DOWNLOAD_FILE"
    # find the root subdir as UNPACKED_SUB_DIR (eventually empty)
    if [ "$(ls | wc -l)" = "1" ]
    then
      UNPACKED_SUB_DIR="$(ls)"
      ls "$UNPACKED_SUB_DIR"
      echo "UNPACKED_SUB_DIR=$UNPACKED_SUB_DIR"
      if [ "$(ls "$UNPACKED_SUB_DIR" | wc -l)" = "1" ]
      then
        UNPACKED_SUB_DIR="$UNPACKED_SUB_DIR/$(ls "$UNPACKED_SUB_DIR")"
        echo "UNPACKED_SUB_DIR=$UNPACKED_SUB_DIR"
      fi
    fi
    cd ..

    rm -f ./latest
    ln -s "$VERSION/$UNPACKED_SUB_DIR" ./latest

    if exist_function postinstall
    then
      postinstall
    fi
  fi

  wait_user
}

#-------------------------------------------------------------------------------

run()
{
  if [ ! -e "./latest" ]
  then
    (COMMAND="update"; update)
  fi
  #. "${APP_SCRIPT_DIR}/${APP_NAME}-${COMMAND}"
  #"${APP_SCRIPT_DIR}/${APP_NAME}-${COMMAND}"
  screen -S app-session -d -m "${APP_SCRIPT_DIR}/${APP_NAME}-${COMMAND}" "$@"
  sleep 1
}

#-------------------------------------------------------------------------------

debug()
{
  echo "debug cmdline: $@"
  if [ ! -f "${APP_SCRIPT_DIR}/${APP_NAME}-${COMMAND}" ]
  then
    COMMAND="run"
  fi

  #. "${APP_SCRIPT_DIR}/${APP_NAME}-${COMMAND}"
  "${APP_SCRIPT_DIR}/${APP_NAME}-${COMMAND}" "$@"

  wait_user
}

#-------------------------------------------------------------------------------

# parse command line: $1=APP_NAME, $2=COMMAND
if [ -n "$1" ]
then
  APP_NAME="$1"
  shift
else
  echo "app name cannot be empty"
  exit 1
fi

if [ -n "$1" ]
then
  COMMAND="$1"
  shift
else
  COMMAND="run"
fi

case "$COMMAND" in
  "update") true;;
  "run") true;;
  "debug") true;;
  *) exit 1;;
esac


# resolve caller dir
CALL_DIR="$(cd -L -- "${0%/*}" && pwd -L)"

# resolve caller symlink
if [ -L "$0" ]
then
  THIS_PATH="$(ls -ld -- "$0")"
  THIS_PATH="${THIS_PATH#*" $0 -> "}"
else
  THIS_PATH="$0"
fi

# actual called file and dir from resolved path
THIS_FILE="${THIS_PATH##*/}"
THIS_DIR="$(cd -P -- "${THIS_PATH%/*}" && pwd -P)"



# apps update/run/debug script dir
APP_SCRIPT_DIR="$APPS_SCRIPT_DIR/$APP_NAME"

# apps bin dir
. "$THIS_DIR/app.conf"
APP_DIR="$APPS_DIR/$APP_NAME"

# setup home environment variable for app
export USERHOME="$THIS_DIR/conf/$APP_NAME"
export HOME="$USERHOME"

# create app dirs and cd into main dir
if [ ! -d "$HOME" ]
then
  mkdir -p "$HOME"
fi

if [ ! -d "$APPS_DIR" ]
then
  mkdir -p "$APPS_DIR"
fi

# create link to this command
if [ ! -L "$APPS_DIR/$THIS_FILE" ]
then
  ln -s "$THIS_DIR/$THIS_FILE" "$APPS_DIR/$THIS_FILE"
fi

if [ ! -d "$APP_DIR" ]
then
  mkdir -p "$APP_DIR"
fi

cd "$APP_DIR"

"$COMMAND" "$@"
