#!/bin/sh

TYPE="custom"

GITHUB_REPO="nodejs/node"

LATEST_RELEASE_URL="https://api.github.com/repos/${GITHUB_REPO}/releases/latest"
VERSION="$(wget --no-check-certificate -qO- "$LATEST_RELEASE_URL" | grep -oP '"tag_name": "\K(.*)(?=")')"

DOWNLOAD_URL="https://nodejs.org/dist/${VERSION}/node-${VERSION}-linux-x64.tar.xz"

FILE_TYPE="tar.xz"
SYMLINKS="node=bin/node npm=bin/npm npx=bin/npx corepack=bin/corepack"
