#!/bin/sh

LASTCHANGE_URL="https://api.github.com/repos/electron/electron/releases/latest"

VERSION=$(wget --no-check-certificate -qO- "$LASTCHANGE_URL" | grep -oP '"tag_name": "\K(.*)(?=")')
VERSION="${VERSION#v}"
DOWNLOAD_URL="https://github.com/electron/electron/releases/download/v${VERSION}/electron-v${VERSION}-linux-x64.zip"
FILE_TYPE="zip"
SYMLINKS="electron=electron"

postinstall()
{
  sudo chown root:root ./latest/chrome-sandbox
  sudo chmod 4755 ./latest/chrome-sandbox
}
