#!/bin/sh

if [ -L "$0" ]
then
  THIS_PATH="$(ls -ld -- "$0")"
  THIS_PATH="${THIS_PATH#*" $0 -> "}"
else
  THIS_PATH="$0"
fi

export GEOSERVER_HOME="$(cd -P -- "${THIS_PATH%/*}" && pwd -P)"

if [ -z "${GEOSERVER_DATA_DIR:-}" ]
then
  if [ -r "${GEOSERVER_HOME}/data_dir" ]
  then
    export GEOSERVER_DATA_DIR="${GEOSERVER_HOME}/data_dir"
  else
    echo "No GEOSERVER_DATA_DIR found, using application defaults"
    GEOSERVER_DATA_DIR=""
  fi
fi

export JAVA_OPTS="${JAVA_OPTS:+"$JAVA_OPTS"} -DALLOW_ENV_PARAMETRIZATION=true"

# mkdir -p "$GEOSERVER_DATA_DIR/logs"
# "$GEOSERVER_HOME/bin/startup.sh" 1>>"$GEOSERVER_DATA_DIR/logs/stdout.log" 2>&1 &

"$GEOSERVER_HOME/bin/startup.sh"

