#!/bin/sh

sudo -s << SUDO

systemctl stop keycloak
systemctl disable keycloak
rm -f "/etc/systemd/system/keycloak.service"
systemctl daemon-reload
systemctl reset-failed

GROUP="admino adm cdrom sudo dip plugdev users lpadmin"
GROUP=""
chown -R "admino:" "/m/src/git/m/cmd/pkg"
userdel -r keycloak
groupdel keycloak

SUDO

