#!/bin/sh

. env.lib.sh

export PKG_INST_CONF_ROOT_DIR="/m/src/git/m/cmd/pkg/conf"
export PKG_INST_ROOT_DIR="/m/pkg"
export BIN_LINKS_ROOT_DIR="/m/bin"
export APP_SCRIPTS_ROOT_DIR="/m/app"
export LIB_LINKS_ROOT_DIR="/m/lib"
export HOME_ROOT_DIR="/m/home"
export CONF_LINKS_ROOT_DIR="/m/conf"

#-------------------------------------------------------------------------------

install()
{
  # pkg-install "$PKG_NAME" "$PKG_VER" "/m/src/git/m/cmd/pkg/conf" "/m/pkg" "/m/bin" "/m/lib" "/m/conf/.cache" "/m/conf"
  pkg-install "$PKG_NAME" "$PKG_VER"
}

#-------------------------------------------------------------------------------

run()
{
  APP_DIR="${PKG_NAME%/*}"

  if [ -z "$APP_NAME" ]
  then
    APP_NAME="${APP_DIR##*/}"
  fi

  echo "detected:"
  echo "APP_DIR=$APP_DIR"
  echo "APP_NAME=$APP_NAME"
  echo "APP_ARGS=$@"

  export HOME="$HOME_ROOT_DIR/$APP_NAME"
  export USERHOME="$HOME"

  if [ ! -d "$HOME" ]
  then
    mkdir -p "$HOME"
  fi

  cd "$APP_DIR"

  # "$PKG_NAME" "$@"
  screen -S app-session -d -m "$PKG_NAME" "$@"
  sleep 1
}

#-------------------------------------------------------------------------------

PKG_COMMAND="$1"
shift

PKG_NAME="$1"
shift

PKG_VER="$1"

if [ -z "$PKG_COMMAND" ] || [ -z "$PKG_NAME" ]
then
  echo "some args are null, required: pkg-command, pkg-name, optional: pkg-ver"
  exit 1
fi

case "$PKG_COMMAND" in
  "install") true;;
  "run") true;;
  *) exit 1;;
esac

"$PKG_COMMAND" "$@"
