#!/bin/sh

. env.lib.sh

#-------------------------------------------------------------------------------

install()
{
  pkg-install "$1" "$2" "/m/src/git/m/cmd/pkg/conf" "/m/pkg" "/m/bin" "/m/lib" "/m/conf" "/m/conf_ver"
}

#-------------------------------------------------------------------------------

run()
{
  true
}

#-------------------------------------------------------------------------------

PKG_COMMAND="$1"
shift

PKG_NAME="$1"
shift

PKG_VER="$1"

if [ -z "$PKG_COMMAND" ] || [ -z "$PKG_NAME" ]
then
  echo "some args are null, required: pkg-command, pkg-name, optional: pkg-ver"
  exit 1
fi

case "$PKG_COMMAND" in
  "install") true;;
  "run") true;;
  *) exit 1;;
esac

"$PKG_COMMAND" "$@"
