#!/bin/sh

. env.lib.sh

export PKG_INST_CONF_ROOT_DIR="/m/src/git/m/cmd/pkg/conf"
export PKG_INST_ROOT_DIR="/m/pkg"
export BIN_LINKS_ROOT_DIR="/m/bin"
export APP_SCRIPTS_ROOT_DIR="/m/app"
export LIB_LINKS_ROOT_DIR="/m/lib"
export HOME_ROOT_DIR="/m/home"
export CONF_LINKS_ROOT_DIR="/m/conf"

#-------------------------------------------------------------------------------

install()
{
  pkg-install "$PKG_NAME" "$PKG_VER"
}

#-------------------------------------------------------------------------------

run()
{
  pkg-run "$PKG_NAME" "$@"
}

#-------------------------------------------------------------------------------

PKG_COMMAND="$1"
shift

PKG_NAME="$1"
shift

PKG_VER="$1"

if [ -z "$PKG_COMMAND" ] || [ -z "$PKG_NAME" ]
then
  echo "some args are null, required: pkg-command, pkg-name, optional: pkg-ver"
  exit 1
fi

case "$PKG_COMMAND" in
  "install") true;;
  "run") true;;
  *) exit 1;;
esac

"$PKG_COMMAND" "$@"
