#!/bin/sh

. env.lib.sh

#-------------------------------------------------------------------------------

find_deepest_dir()
{
  DEEPEST_DIR="$1"
  shift

  (
    cd "$DEEPEST_DIR"

    if [ "$(ls | wc -l)" = "1" ] && [ -d "$(ls)" ]
    then
      DEEPEST_DIR="$(ls)"
      if [ "$(ls "$DEEPEST_DIR" | wc -l)" = "1" ] && [ -d "$(ls "$DEEPEST_DIR")" ]
      then
        DEEPEST_DIR="$DEEPEST_DIR/$(ls "$DEEPEST_DIR")"
      fi
    else
      DEEPEST_DIR=""
    fi

    cd "$DEEPEST_DIR"

    pwd
  )
}

#-------------------------------------------------------------------------------

install_extra_features()
{
  PKG_INST_DEEPEST_DIR="$DEEPEST_DIR"

  # self signed cert
  if [ -n "$CERT_GEN_NAME" ]
  then
    (
      cd "$PKG_INST_DEEPEST_DIR"
      mkdir -p "./cert"
      cd "./cert"
      openssl genrsa -out "${CERT_GEN_NAME}.key" 2048
      openssl req -new -x509 -sha256 -key "${CERT_GEN_NAME}.key" -out "${CERT_GEN_NAME}.crt" -days 365 -subj "/C=IT/ST=Italy/L=Rome/O=X/OU=X/CN=X"
      cp "${CERT_GEN_NAME}.key" "${CERT_GEN_NAME}.pem"
      cat "${CERT_GEN_NAME}.crt" >> "${CERT_GEN_NAME}.pem"
    )
  fi

  # postgres installer (on demand)
  if [ -n "$POSTGRES_NAME" ]
  then
    echo "POSTGRES_NAME=\"$POSTGRES_NAME\"" > "./${POSTGRES_NAME}-postgres"
    echo "POSTGRES_EXTENSIONS=\"$POSTGRES_EXTENSIONS\"" >> "./${POSTGRES_NAME}-postgres"
    chmod +x "./${POSTGRES_NAME}-postgres"
    if [ -z "$SYMLINKS" ]
    then
      SYMLINKS="${PKG_NAME}-postgres=${POSTGRES_NAME}-postgres"
    else
      SYMLINKS="$SYMLINKS ${PKG_NAME}-postgres=${POSTGRES_NAME}-postgres"
    fi
    cat << 'EOF' >> "./${POSTGRES_NAME}-postgres"
#!/bin/sh

echo "DO YOU WANT TO INSTALL POSTGRES DB? YES, NO (default = NO): "
read INSTALL_FLAG
if [ "$INSTALL_FLAG" = "YES" ] || [ "$INSTALL_FLAG" = "yes" ] || [ "$INSTALL_FLAG" = "Y" ] || [ "$INSTALL_FLAG" = "y" ] || [ "$INSTALL_FLAG" = "Yes" ]
then
  true
else
  exit 0
fi

echo "WARNING!!! Press ENTER to DELETE current ${POSTGRES_NAME} DB and initialize a new DB (install postgres if not present)"
read x

sudo -s << SUDO
if ! which psql > /dev/null
then
  echo "Type new password for '${POSTGRES_NAME}' user (defaults to ${POSTGRES_NAME}): "
  read POSTGRES_PASS
  if [ -z "${POSTGRES_PASS}" ]
  then
    POSTGRES_PASS="${POSTGRES_NAME}"
  fi
  apt update
  apt install -y postgresql
  if [ -n "${POSTGRES_EXTENSIONS}" ]
  then
    apt install -y ${POSTGRES_EXTENSIONS}
  fi
  sudo -u postgres psql -c "CREATE USER ${POSTGRES_NAME} WITH PASSWORD '${POSTGRES_PASS}';"
else
  systemctl restart postgresql
  sudo -u postgres dropdb --force --if-exists ${POSTGRES_NAME}
fi

sudo -u postgres createdb ${POSTGRES_NAME}
sudo -u postgres psql -d ${POSTGRES_NAME} -c "ALTER DATABASE ${POSTGRES_NAME} OWNER TO ${POSTGRES_NAME};"
sudo -u postgres psql -d ${POSTGRES_NAME} -c "GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_NAME} TO ${POSTGRES_NAME};"

SUDO
EOF

    "./${POSTGRES_NAME}-postgres"
  fi

  # service
  if [ -n "$SERVICE_EXEC_START" ]
  then
    (
      cd "$PKG_INST_DEEPEST_DIR"

#-------------------------------------------------------------------------------
      cat << EOF > "./${PKG_NAME}-service-start"
#!/bin/sh

sudo systemctl start ${PKG_NAME}

EOF
      chmod +x "./${PKG_NAME}-service-start"

#-------------------------------------------------------------------------------
      cat << EOF > "./${PKG_NAME}-service-stop"
#!/bin/sh

sudo systemctl stop ${PKG_NAME}

EOF
      chmod +x "./${PKG_NAME}-service-stop"

#-------------------------------------------------------------------------------
      cat << EOF > "./${PKG_NAME}-service-restart"
#!/bin/sh

sudo systemctl restart ${PKG_NAME}

EOF
      chmod +x "./${PKG_NAME}-service-restart"

#-------------------------------------------------------------------------------
      cat << EOF > "./${PKG_NAME}-service-status"
#!/bin/sh

sudo systemctl status ${PKG_NAME}

EOF
      chmod +x "./${PKG_NAME}-service-status"

#-------------------------------------------------------------------------------
      cat << 'EOF' | tee "./${PKG_NAME}-service-install" > "./${PKG_NAME}-service-uninstall"
#!/bin/sh

if [ -L "$0" ]
then
  THIS_PATH="$(ls -ld -- "$0")"
  THIS_PATH="${THIS_PATH#*" $0 -> "}"
else
  THIS_PATH="$0"
fi

PKG_HOME="$(cd -P -- "${THIS_PATH%/*}" && pwd -P)"

EOF

      chmod +x "./${PKG_NAME}-service-install"
      chmod +x "./${PKG_NAME}-service-uninstall"
      echo "PKG_NAME=\"$PKG_NAME\"" | tee -a "./${PKG_NAME}-service-install" >> "./${PKG_NAME}-service-uninstall"

#-------------------------------------------------------------------------------
      cat << EOF >> "./${PKG_NAME}-service-install"

SERVICE_EXEC_START="$SERVICE_EXEC_START"
SERVICE_EXEC_STOP="$SERVICE_EXEC_STOP"
SERVICE_WORKING_DIR="$SERVICE_WORKING_DIR"

EOF

      cat << 'EOF' >> "./${PKG_NAME}-service-install"
if [ -n "$SERVICE_WORKING_DIR" ]
then
  SERVICE_WORKING_DIR="WorkingDirectory=$SERVICE_WORKING_DIR"
fi

SERVICE_EXEC_START="ExecStart=$PKG_HOME/$SERVICE_EXEC_START"

if [ -n "$SERVICE_EXEC_STOP" ]
then
  SERVICE_EXEC_STOP="ExecStop=$PKG_HOME/$SERVICE_EXEC_STOP"
fi

sudo -s << SUDO

groupadd ${PKG_NAME}
useradd -r -g ${PKG_NAME} -d "$PKG_HOME" -s /sbin/nologin ${PKG_NAME}
chown -RL ${PKG_NAME}:${PKG_NAME} "$PKG_HOME"



cat > "/etc/systemd/system/${PKG_NAME}.service" << SERVICE
[Unit]
Description=${PKG_NAME} Service
After=network.service

[Service]
Type=simple
User=${PKG_NAME}
Group=${PKG_NAME}
${SERVICE_WORKING_DIR}
${SERVICE_EXEC_START}
${SERVICE_EXEC_STOP}

[Install]
WantedBy=multi-user.target

SERVICE



chown root:root "/etc/systemd/system/${PKG_NAME}.service"
chmod 644 "/etc/systemd/system/${PKG_NAME}.service"
systemctl daemon-reload
systemctl enable ${PKG_NAME}

SUDO
EOF

#-------------------------------------------------------------------------------
      cat << 'EOF' >> "./${PKG_NAME}-service-uninstall"
sudo -s << SUDO

systemctl stop ${PKG_NAME}
systemctl disable ${PKG_NAME}
rm -f "/etc/systemd/system/${PKG_NAME}.service"
systemctl daemon-reload
systemctl reset-failed

# userdel -r ${PKG_NAME}
userdel ${PKG_NAME}
groupdel ${PKG_NAME}

GROUP="$(groups)"
GROUP="${GROUP%% *}"
chown -RL "${USER}:${GROUP}" "${PKG_HOME}"

SUDO
EOF

      echo "DO YOU WANT TO INSTALL SERVICE DAEMON? YES, NO (default = NO): "
      read INSTALL_FLAG
      if [ "$INSTALL_FLAG" = "YES" ] || [ "$INSTALL_FLAG" = "yes" ] || [ "$INSTALL_FLAG" = "Y" ] || [ "$INSTALL_FLAG" = "y" ] || [ "$INSTALL_FLAG" = "Yes" ]
      then
        "./${PKG_NAME}-service-install"
      fi
    )
    if [ -n "$SYMLINKS" ]
    then
      SYMLINKS="$SYMLINKS "
    fi
    SYMLINKS="$SYMLINKS${PKG_NAME}-service-install=${PKG_NAME}-service-install ${PKG_NAME}-service-uninstall=${PKG_NAME}-service-uninstall ${PKG_NAME}-service-start=${PKG_NAME}-service-start ${PKG_NAME}-service-stop=${PKG_NAME}-service-stop ${PKG_NAME}-service-restart=${PKG_NAME}-service-restart ${PKG_NAME}-service-status=${PKG_NAME}-service-status"
  fi
}

#-------------------------------------------------------------------------------

install_symlinks()
{
  PKG_INST_DEEPEST_DIR="$DEEPEST_DIR"

  if [ -z "$SYMLINKS" ]
  then
    # todo link all binaries found
    echo "SYMLINKS is empty! cannot create links"
    exit 1
  else
    for k in $SYMLINKS
    do
      symlink="${k%%=*}"
      target="${k#*=}"
      if [ "$APP" = "true" ]
      then
        rm -f "$APP_SCRIPTS_ROOT_DIR/$symlink"
        # ln -s "$PKG_INST_DEEPEST_DIR/$target" "$APP_SCRIPTS_ROOT_DIR/$symlink"
        cat << EOF > "$APP_SCRIPTS_ROOT_DIR/$symlink"
#!/bin/sh
export APP_NAME="$PKG_NAME"
pkg run "$PKG_INST_DEEPEST_DIR/$target" "\$@"
EOF
        sudo chmod +x "$APP_SCRIPTS_ROOT_DIR/$symlink"
      else
        rm -f "$BIN_LINKS_ROOT_DIR/$symlink"
        ln -s "$PKG_INST_DEEPEST_DIR/$target" "$BIN_LINKS_ROOT_DIR/$symlink"
      fi

      if [ -e "$PKG_INST_DEEPEST_DIR/$target" ] && [ ! -x "$PKG_INST_DEEPEST_DIR/$target" ]
      then
        sudo chmod +x "$PKG_INST_DEEPEST_DIR/$target"
      fi
    done
  fi

  if [ -f "${PKG_INST_CONF_ROOT_DIR}/${PKG_NAME}.desktop" ]
  then
    sudo rm -f "/usr/share/applications/${PKG_NAME}.desktop"
    sudo ln -s "${PKG_INST_CONF_ROOT_DIR}/${PKG_NAME}.desktop" "/usr/share/applications/${PKG_NAME}.desktop"
    APP_ICON="$(grep "Icon" "${PKG_INST_CONF_ROOT_DIR}/${PKG_NAME}.desktop" | sed 's/Icon=//g')"
    APP_ICON="${APP_ICON##*/}"
    echo "APP_ICON=$APP_ICON"
    if [ -f "${PKG_INST_CONF_ROOT_DIR}/${APP_ICON}" ]
    then
      sudo rm -f "/usr/share/pixmaps/${APP_ICON}"
      sudo ln -s "${PKG_INST_CONF_ROOT_DIR}/${APP_ICON}" "/usr/share/pixmaps/${APP_ICON}"
    fi
  fi
}

#-------------------------------------------------------------------------------

install()
{
  if [ -z "$PKG_VER" ]
  then
    VERSION="$(pkg-repo latest_version "${PKG_INST_CONF_ROOT_DIR}/${PKG_NAME}.conf")"
    PKG_VER="$VERSION"
  fi

  PKG_INST_DIR="$PKG_INST_ROOT_DIR/${PKG_NAME}-${PKG_VER}"

  if [ -d "$PKG_INST_DIR" ]
  then
    echo "$PKG_INST_DIR already installed!"
    return 0
  fi

  echo "installing $PKG_INST_DIR"

  DOWNLOAD_URL="$(pkg-repo download_url "${PKG_INST_CONF_ROOT_DIR}/${PKG_NAME}.conf" "$PKG_VER")"

  DOWNLOAD_FILE="${PKG_INST_DIR}-$(date +"[%Y-%m-%d %H:%M:%S]").${FILE_TYPE}"

  UNPACK_DIR="$PKG_INST_DIR"

  pkg-download "$DOWNLOAD_URL" "$DOWNLOAD_FILE" "$UNPACK_DIR" "$FILE_TYPE"

  DEEPEST_DIR="$(find_deepest_dir "$PKG_INST_DIR")"

  if exist_function postinstall
  then
    (
      # cd "$PKG_INST_DIR"
      cd "$DEEPEST_DIR"
      postinstall
    )
  fi

  install_extra_features

  install_symlinks
}

#-------------------------------------------------------------------------------

PKG_NAME="$1"
shift

PKG_VER="$1"
shift



if [ -z "$PKG_INST_CONF_ROOT_DIR" ]
then
  echo "$0 - pkg-inst-conf-dir cannot be null"
  exit 1
fi
mkdir -p "$PKG_INST_CONF_ROOT_DIR"
PKG_INST_CONF_ROOT_DIR="$(cd -- "$PKG_INST_CONF_ROOT_DIR" && pwd)"



if [ -z "$PKG_INST_ROOT_DIR" ]
then
  echo "$0 - pkg-inst-dir cannot be null"
  exit 1
fi
mkdir -p "$PKG_INST_ROOT_DIR"
PKG_INST_ROOT_DIR="$(cd -- "$PKG_INST_ROOT_DIR" && pwd)"



if [ -z "$BIN_LINKS_ROOT_DIR" ]
then
  echo "$0 - BIN_LINKS_ROOT_DIR cannot be null"
  exit 1
fi
mkdir -p "$BIN_LINKS_ROOT_DIR"
BIN_LINKS_ROOT_DIR="$(cd -- "$BIN_LINKS_ROOT_DIR" && pwd)"



if [ -z "$APP_SCRIPTS_ROOT_DIR" ]
then
  echo "$0 - APP_SCRIPTS_ROOT_DIR cannot be null"
  exit 1
fi
mkdir -p "$APP_SCRIPTS_ROOT_DIR"
APP_SCRIPTS_ROOT_DIR="$(cd -- "$APP_SCRIPTS_ROOT_DIR" && pwd)"



if [ -z "$LIB_LINKS_ROOT_DIR" ]
then
  echo "$0 - LIB_LINKS_ROOT_DIR cannot be null"
  exit 1
fi
mkdir -p "$LIB_LINKS_ROOT_DIR"
LIB_LINKS_ROOT_DIR="$(cd -- "$LIB_LINKS_ROOT_DIR" && pwd)"



if [ -z "$HOME_ROOT_DIR" ]
then
  echo "$0 - HOME_ROOT_DIR cannot be null"
  exit 1
fi
mkdir -p "$HOME_ROOT_DIR"
HOME_ROOT_DIR="$(cd -- "$HOME_ROOT_DIR" && pwd)"



if [ -z "$CONF_LINKS_ROOT_DIR" ]
then
  echo "$0 - CONF_LINKS_ROOT_DIR cannot be null"
  exit 1
fi
mkdir -p "$CONF_LINKS_ROOT_DIR"
CONF_LINKS_ROOT_DIR="$(cd -- "$CONF_LINKS_ROOT_DIR" && pwd)"



. "${PKG_INST_CONF_ROOT_DIR}/${PKG_NAME}.conf"

install
