#!/bin/sh

#-------------------------------------------------------------------------------

run()
{
  PKG_NAME="$1"
  shift

  APP_DIR="${PKG_NAME%/*}"

  if [ -z "$APP_NAME" ]
  then
    APP_NAME="${APP_DIR##*/}"
  fi

  echo "detected:"
  echo "APP_DIR=$APP_DIR"
  echo "APP_NAME=$APP_NAME"
  echo "APP_ARGS=$@"

  export HOME="$HOME_ROOT_DIR/$APP_NAME"
  export XDG_DATA_HOME="$HOME"
  # export XDG_DATA_DIRS="$HOME:/usr/share/"
  export JAVA_OPTS="-Duser.home=$HOME"
  export _JAVA_OPTIONS="-Duser.home=$HOME"
  export JAVA_TOOL_OPTIONS="-Duser.home=$HOME"

  if [ ! -d "$HOME" ]
  then
    mkdir -p "$HOME"
  fi

  cd "$APP_DIR"

  if [ -z "$APP_FORK" ] || [ "$APP_FORK" = "none" ]
  then
    "$PKG_NAME" "$@"
  elif [ "$APP_FORK" = "simple" ]
  then
    "$PKG_NAME" "$@" &
    sleep 1
  elif [ "$APP_FORK" = "screen" ]
  then
    screen -S app-session -d -m "$PKG_NAME" "$@"
    sleep 1
  elif [ "$APP_FORK" = "setsid" ]
  then
    setsid "$PKG_NAME" "$@" &
    sleep 1
  else
    echo "unknownk option APP_FORK=\"$APP_FORK\""
    exit 1
  fi
}

#-------------------------------------------------------------------------------

run "$@"
