#!/bin/sh

#-------------------------------------------------------------------------------

unpack()
{
  PACKED_FILE="$1"
  shift
  FILE_TYPE="$1"
  shift
  UNPACK_DIR="$1"
  shift

  echo "unpacking $PACKED_FILE to $UNPACK_DIR"
  (
    cd "$UNPACK_DIR"

    if [ "$FILE_TYPE" = "zip" ]
    then
      unzip "$PACKED_FILE"
    elif [ "$FILE_TYPE" = "tar.gz" ] || [ "$FILE_TYPE" = "tgz" ] || [ "$FILE_TYPE" = "tar" ] || [ "$FILE_TYPE" = "gzip" ] || [ "$FILE_TYPE" = "bzip" ] || [ "$FILE_TYPE" = "tar.xz" ] || [ "$FILE_TYPE" = "xz" ]
    then
      tar xvf "$PACKED_FILE"
    elif [ "$FILE_TYPE" = "AppImage" ] || [ "$FILE_TYPE" = "appimage" ]
    then
      chmod +x "$PACKED_FILE"
      "$PACKED_FILE" --appimage-extract
    elif [ "$FILE_TYPE" = "deb" ]
    then
      dpkg-deb -x "$PACKED_FILE" ./
    elif [ "$FILE_TYPE" = "jar" ] || [ "$FILE_TYPE" = "war" ]
    then
      mv "$PACKED_FILE" "$UNPACK_DIR"
    elif [ "$FILE_TYPE" = "none" ]
    then
      true
    else
      echo "unknown file type: FILE_TYPE=$FILE_TYPE"
      exit 1
    fi
  )
}

#-------------------------------------------------------------------------------

download()
{
  rm -rf "$UNPACK_DIR"
  mkdir -p "$UNPACK_DIR"

  if [ "$FILE_TYPE" = "none" ]
  then
  (
    cd "$UNPACK_DIR"
    # wget "$DOWNLOAD_URL"
    wget --no-check-certificate "$DOWNLOAD_URL"
  )
  elif [ "$FILE_TYPE" = "jar" ] || [ "$FILE_TYPE" = "war" ]
  then
  (
    cd "$UNPACK_DIR"
    # DOWNLOAD_URLS="$(wget --no-check-certificate -qO- "$DOWNLOAD_URL" | sed '1d')"
    DOWNLOAD_URLS="$(wget \
    --header="Accept: text/html" \
    --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" \
    --no-check-certificate -qO- "$DOWNLOAD_URL" | grep "href" | sed 's/^.*href="\([^"]*\)".*$/\1/' | head -n -1)"
    echo "DOWNLOAD_URLS=$DOWNLOAD_URLS"
    PKG_VER="${DOWNLOAD_URL##*/}"
    for k in $DOWNLOAD_URLS
    do
      DOWNLOAD_FILE="$(echo "$k" | sed "s/-$PKG_VER//g")"
      wget --no-check-certificate -O "$DOWNLOAD_FILE" "${DOWNLOAD_URL}/${k}"
    done
  )
  else
    DOWNLOAD_FILE="${UNPACK_DIR}-$(date +"[%Y-%m-%d %H:%M:%S]").${FILE_TYPE}"
    # wget -O "$DOWNLOAD_FILE" "$DOWNLOAD_URL" && \
    wget --no-check-certificate -O "$DOWNLOAD_FILE" "$DOWNLOAD_URL" && \
    unpack "$DOWNLOAD_FILE" "$FILE_TYPE" "$UNPACK_DIR" && \
    rm -f "$DOWNLOAD_FILE"
  fi
}

#-------------------------------------------------------------------------------

if [ "$#" -lt "4" ]
then
  echo "$0 - some args are null, required: download_url, download_file, unpack_dir, file_type"
  exit 1
fi

DOWNLOAD_URL="$1"
shift

DOWNLOAD_FILE="$1"
shift

UNPACK_DIR="$1"
shift

FILE_TYPE="$1"
shift

if [ -z "$FILE_TYPE" ]
then
  FILE_TYPE="none"
fi

download
