#!/bin/sh

#-------------------------------------------------------------------------------

check_function()
{
  if exist_function "$1"
  then
    true
  else
    echo "missing type function! TYPE=$TYPE - function=$1"
    exit 1
  fi
}

#-------------------------------------------------------------------------------

if [ -z "$TYPE" ]
then
  TYPE="custom"
fi

case "$TYPE" in
  "custom") true;;
  "github") true;;
  "maven") true;;
  "sourceforge") true;;
  "codeberg") true;;
  *)
    echo "unknown type! TYPE=$TYPE"
    exit 1
  ;;
esac

. "${0}-type-${TYPE}"

check_function "versions"
check_function "find_latest_version"
check_function "get_download_url"

#-------------------------------------------------------------------------------
