#!/bin/sh

. env.lib.sh

#-------------------------------------------------------------------------------

find_deepest_dir()
{
  DEEPEST_DIR="$1"
  shift

  (
    cd "$DEEPEST_DIR"

    if [ "$(ls | wc -l)" = "1" ] && [ -d "$(ls)" ]
    then
      DEEPEST_DIR="$(ls)"
      if [ "$(ls "$DEEPEST_DIR" | wc -l)" = "1" ] && [ -d "$(ls "$DEEPEST_DIR")" ]
      then
        DEEPEST_DIR="$DEEPEST_DIR/$(ls "$DEEPEST_DIR")"
      fi
    else
      DEEPEST_DIR=""
    fi

    cd "$DEEPEST_DIR"

    pwd
  )
}

#-------------------------------------------------------------------------------

uninstall_extra_features()
{
  PKG_INST_DEEPEST_DIR="$DEEPEST_DIR"

  # postgres uninstaller (on demand)
  if [ -n "$POSTGRES_NAME" ]
  then
    "./${POSTGRES_NAME}-postgres"
  fi

  # TODO ask if to remove home

  # service
  if [ -n "$SERVICE_EXEC_START" ]
  then
    (
      cd "$PKG_INST_DEEPEST_DIR"
      "./${PKG_NAME}-service-uninstall"
    )
    if [ -n "$SYMLINKS" ]
    then
      SYMLINKS="$SYMLINKS "
    fi
    SYMLINKS="$SYMLINKS${PKG_NAME}-service-install=${PKG_NAME}-service-install ${PKG_NAME}-service-uninstall=${PKG_NAME}-service-uninstall ${PKG_NAME}-service-start=${PKG_NAME}-service-start ${PKG_NAME}-service-stop=${PKG_NAME}-service-stop ${PKG_NAME}-service-restart=${PKG_NAME}-service-restart ${PKG_NAME}-service-status=${PKG_NAME}-service-status"
  fi
}

#-------------------------------------------------------------------------------

uninstall_symlinks()
{
  # bin symlinks
  if [ -n "$SYMLINKS" ]
  then
    for k in $SYMLINKS
    do
      symlink="${k%%=*}"
      target="${k#*=}"
      rm -f "$BIN_LINKS_ROOT_DIR/$symlink"
    done
  fi

  # app launcher scripts
  if [ -n "$APP_LAUNCHERS" ]
  then
    for k in $APP_LAUNCHERS
    do
      launcher="${k%%=*}"
      target="${k#*=}"
      rm -f "$APP_SCRIPTS_ROOT_DIR/$launcher"

      # desktop, icon, menu
      desktop_file="${PKG_INST_CONF_ROOT_DIR}/${PKG_NAME}-${launcher}.desktop"
      target_desktop_file="/usr/share/applications/${PKG_NAME}-${launcher}.desktop"
      icon_file_prefix="${PKG_INST_CONF_ROOT_DIR}/${PKG_NAME}-${launcher}-icon"
      target_icon_dir="/usr/share/pixmaps"
      target_icon_file_prefix="${target_icon_dir}/${PKG_NAME}-${launcher}-icon"
      menu_file="${PKG_INST_CONF_ROOT_DIR}/${PKG_NAME}-${launcher}-menu"
      target_menu_file="/usr/share/menu/${PKG_NAME}-${launcher}-menu"
      if [ -f "$desktop_file" ]
      then
        sudo rm -f "$target_desktop_file"
      fi
      if ls -d "${icon_file_prefix}"* >/dev/null 2>&1
      then
        sudo rm -f "${target_icon_file_prefix}"*
      fi
      if [ -f "$menu_file" ]
      then
        sudo rm -f "$target_menu_file"
      fi
    done
  fi
}

#-------------------------------------------------------------------------------

uninstall()
{
  if ! ls -d "$PKG_INST_ROOT_DIR/${PKG_NAME}"* >/dev/null 2>&1
  then
    echo "no package installed found: PKG_NAME=$PKG_NAME"
    exit 1
  fi

  if [ -z "$PKG_VER" ]
  then
    set -- $(ls -drv1 "$PKG_INST_ROOT_DIR/${PKG_NAME}"*)

    for k in $@
    do
      echo "uninstall '$k'? YES, NO (default = NO)"
      read uninstall_choice
      if [ "$uninstall_choice" = "YES" ] || [ "$uninstall_choice" = "yes" ] || [ "$uninstall_choice" = "Y" ] || [ "$uninstall_choice" = "y" ] || [ "$uninstall_choice" = "Yes" ]
      then
        PKG_INST_DIR="$k"
        PKG_VER="${PKG_INST_DIR#$PKG_INST_ROOT_DIR/${PKG_NAME}-}"
        break
      fi
    done
  fi

  if [ -z "$PKG_VER" ]
  then
    PKG_INST_DIR="$1"
    PKG_VER="${PKG_INST_DIR#$PKG_INST_ROOT_DIR/${PKG_NAME}-}"
  fi

  echo "uninstalling PKG_NAME=\"$PKG_NAME\" PKG_VER=\"$PKG_VER\" $PKG_INST_DIR"

  DEEPEST_DIR="$(find_deepest_dir "$PKG_INST_DIR")"

  if exist_function beforeuninstall
  then
    (
      # cd "$PKG_INST_DIR"
      cd "$DEEPEST_DIR"
      beforeuninstall
    )
  fi

  uninstall_extra_features

  uninstall_symlinks

  echo "remove directory: '${PKG_INST_DIR}'? YES, NO (default = NO)"
  read uninstall_choice
  if [ "$uninstall_choice" = "YES" ] || [ "$uninstall_choice" = "yes" ] || [ "$uninstall_choice" = "Y" ] || [ "$uninstall_choice" = "y" ] || [ "$uninstall_choice" = "Yes" ]
  then
    rm -rfv "${PKG_INST_DIR}"
  fi
}

#-------------------------------------------------------------------------------

PKG_NAME="$1"
shift

PKG_VER="$1"
shift



if [ -z "$PKG_INST_CONF_ROOT_DIR" ]
then
  echo "$0 - pkg-inst-conf-dir cannot be null"
  exit 1
fi
mkdir -p "$PKG_INST_CONF_ROOT_DIR"
PKG_INST_CONF_ROOT_DIR="$(cd -- "$PKG_INST_CONF_ROOT_DIR" && pwd)"



if [ -z "$PKG_INST_ROOT_DIR" ]
then
  echo "$0 - pkg-inst-dir cannot be null"
  exit 1
fi
mkdir -p "$PKG_INST_ROOT_DIR"
PKG_INST_ROOT_DIR="$(cd -- "$PKG_INST_ROOT_DIR" && pwd)"



if [ -z "$BIN_LINKS_ROOT_DIR" ]
then
  echo "$0 - BIN_LINKS_ROOT_DIR cannot be null"
  exit 1
fi
mkdir -p "$BIN_LINKS_ROOT_DIR"
BIN_LINKS_ROOT_DIR="$(cd -- "$BIN_LINKS_ROOT_DIR" && pwd)"



if [ -z "$APP_SCRIPTS_ROOT_DIR" ]
then
  echo "$0 - APP_SCRIPTS_ROOT_DIR cannot be null"
  exit 1
fi
mkdir -p "$APP_SCRIPTS_ROOT_DIR"
APP_SCRIPTS_ROOT_DIR="$(cd -- "$APP_SCRIPTS_ROOT_DIR" && pwd)"



if [ -z "$LIB_LINKS_ROOT_DIR" ]
then
  echo "$0 - LIB_LINKS_ROOT_DIR cannot be null"
  exit 1
fi
mkdir -p "$LIB_LINKS_ROOT_DIR"
LIB_LINKS_ROOT_DIR="$(cd -- "$LIB_LINKS_ROOT_DIR" && pwd)"



if [ -z "$HOME_ROOT_DIR" ]
then
  echo "$0 - HOME_ROOT_DIR cannot be null"
  exit 1
fi
mkdir -p "$HOME_ROOT_DIR"
HOME_ROOT_DIR="$(cd -- "$HOME_ROOT_DIR" && pwd)"



if [ -z "$CONF_LINKS_ROOT_DIR" ]
then
  echo "$0 - CONF_LINKS_ROOT_DIR cannot be null"
  exit 1
fi
mkdir -p "$CONF_LINKS_ROOT_DIR"
CONF_LINKS_ROOT_DIR="$(cd -- "$CONF_LINKS_ROOT_DIR" && pwd)"



. "${PKG_INST_CONF_ROOT_DIR}/${PKG_NAME}.conf"

uninstall
