#!/bin/sh

. env.lib.sh

#-------------------------------------------------------------------------------

check_function()
{
  if exist_function "$1"
  then
    true
  else
    echo "missing type function! TYPE=$TYPE - function=$1"
    exit 1
  fi
}

#-------------------------------------------------------------------------------

versions()
{
  get_versions 1>&2 > /dev/null
  echo "$VERSIONS"
}

#-------------------------------------------------------------------------------

latest_version()
{
  find_latest_version 1>&2 > /dev/null
  echo "$VERSION"
}

#-------------------------------------------------------------------------------

download_url()
{
  if [ -z "$VERSION" ]
  then
    VERSION="$(latest_version)"
  fi

  get_download_url 1>&2 > /dev/null
  echo "$DOWNLOAD_URL"
}

#-------------------------------------------------------------------------------

if [ "$#" -lt "2" ]
then
  echo "$0 - some args are null, required: command, conf-file"
  exit 1
fi

COMMAND="$1"
shift

CONF_FILE="$1"
shift

VERSION="$1"

case "$COMMAND" in
  "versions") true;;
  "latest_version") true;;
  "download_url") true;;
  *)
    echo "unknown command! COMMAND=$COMMAND"
    exit 1
  ;;
esac

. "$CONF_FILE"

if [ -z "$TYPE" ]
then
  TYPE="custom"
fi

case "$TYPE" in
  "custom") true;;
  "github") true;;
  "maven") true;;
  "sourceforge") true;;
  "codeberg") true;;
  *)
    echo "unknown type! TYPE=$TYPE"
    exit 1
  ;;
esac

. "${0}-type-${TYPE}"

check_function "versions"
check_function "find_latest_version"
check_function "get_download_url"

"$COMMAND"
