#!/bin/sh

#-------------------------------------------------------------------------------

get_versions()
{
  echo "$VERSIONS"
}

#-------------------------------------------------------------------------------

find_latest_version()
{
  if [ -z "$MAVEN_REPO" ]
  then
    echo "$0 - repo is null"
    exit 1
  fi

  MAVEN_GROUP_ID="${MAVEN_REPO%/*}"
  MAVEN_ARTIFACT_ID="${MAVEN_REPO#*/}"
  LATEST_RELEASE_URL="https://search.maven.org/solrsearch/select?q=g:%22${MAVEN_GROUP_ID}%22+AND+a:%22${MAVEN_ARTIFACT_ID}%22"
  VERSION="$(wget --no-check-certificate -qO- "$LATEST_RELEASE_URL" | sed 's/^.*"latestVersion":"\([^"]*\)".*$/\1/')"
}

#-------------------------------------------------------------------------------

get_download_url()
{
  if [ -z "$MAVEN_REPO" ]
  then
    echo "$0 - repo is null"
    exit 1
  fi

  if [ -z "$VERSION" ]
  then
    echo "$0 - version is null"
    exit 1
  fi

  MAVEN_GROUP_ID="${MAVEN_REPO%/*}"
  MAVEN_ARTIFACT_ID="${MAVEN_REPO#*/}"
  MAVEN_GROUP_PATH="$(echo "$MAVEN_GROUP_ID" | tr "." "/")"
  MAVEN_BASE_URL="https://repo1.maven.org/maven2"
  # DOWNLOAD_URL="${MAVEN_BASE_URL}/${MAVEN_GROUP_PATH}/${MAVEN_ARTIFACT_ID}/${VERSION}/${MAVEN_ARTIFACT_ID}-${VERSION}.${FILE_TYPE}"
  DOWNLOAD_URL="${MAVEN_BASE_URL}/${MAVEN_GROUP_PATH}/${MAVEN_ARTIFACT_ID}/${VERSION}"
}

#-------------------------------------------------------------------------------
