#!/bin/sh

#-------------------------------------------------------------------------------

get_versions()
{
  echo "$VERSIONS"
}

#-------------------------------------------------------------------------------

find_latest_version()
{
  # LATEST_RELEASE_URL="https://sourceforge.net/projects/${SOURCEFORGE_REPO}/rss?path=/${SOURCEFORGE_PATH}"
  # LATEST_RELEASE_URL="https://sourceforge.net/projects/${SOURCEFORGE_REPO}/files/${SOURCEFORGE_PATH}"
  LATEST_RELEASE_URL="https://sourceforge.net/projects/${SOURCEFORGE_REPO}/best_release.json"
  VERSION="$(wget --no-check-certificate -qO- "$LATEST_RELEASE_URL" | sed 's/", /\n/g' | grep "filename" | grep "${SOURCEFORGE_ASSET_NAME_PATTERN}" | head -n 1 | sed 's/.*\///g')"

  VERSION_PREFIX="$(printf "%s\n%s\n" "$SOURCEFORGE_ASSET_NAME_PATTERN" "$VERSION" | sed -e 'N;s/^\(.*\).*\n\1.*$/\1\n\1/;D')"

  VERSION_REV="$(echo "$VERSION" | sed -e 's/^/\
/' -e ':a' -e 's/\n\(.*\)\(.\)/\2\
\1/
ta' -e 's/\n//')"

  PATTERN_REV="$(echo "$SOURCEFORGE_ASSET_NAME_PATTERN" | sed -e 's/^/\
/' -e ':a' -e 's/\n\(.*\)\(.\)/\2\
\1/
ta' -e 's/\n//')"

  VERSION_SUFFIX="$(printf "%s\n%s\n" "$PATTERN_REV" "$VERSION_REV" | sed -e 'N;s/^\(.*\).*\n\1.*$/\1\n\1/;D' | sed -e 's/^/\
/' -e ':a' -e 's/\n\(.*\)\(.\)/\2\
\1/
ta' -e 's/\n//')"

  VERSION="${VERSION#$VERSION_PREFIX}"
  VERSION="${VERSION%$VERSION_SUFFIX}"

  # echo "VERSION=$VERSION"
  # echo "VERSION_REV=$VERSION_REV"
  # echo "PATTERN_REV=$PATTERN_REV"
  # echo "VERSION_PREFIX=$VERSION_PREFIX"
  # echo "VERSION_SUFFIX=$VERSION_SUFFIX"

  # reverse string: sed -e 'G;:1' -e 's/\(.\)\(.*\n\)/\2\1/;t1' -e 's/.//'
}

#-------------------------------------------------------------------------------

get_download_url()
{
  if [ -z "$SOURCEFORGE_REPO" ]
  then
    echo "$0 - repo is null"
    exit 1
  fi

  if [ -z "$SOURCEFORGE_PATH" ]
  then
    echo "$0 - repo is null"
    exit 1
  fi

  if [ -z "$VERSION" ]
  then
    echo "$0 - version is null"
    exit 1
  fi

  eval SOURCEFORGE_PATH="$SOURCEFORGE_PATH"
  RELEASE_URL="https://sourceforge.net/projects/${SOURCEFORGE_REPO}/files/${SOURCEFORGE_PATH}"
  # echo "RELEASE_URL=$RELEASE_URL"
  DOWNLOAD_URL="$(wget --no-check-certificate -qO- "$RELEASE_URL" | tr "<" "\n" | grep 'href="' | grep "$SOURCEFORGE_ASSET_NAME_PATTERN" | grep "$PKG_VER" | head -n 1 | sed 's/.*href="//g' | sed 's/\/download"//g')"
}

#-------------------------------------------------------------------------------
