#!/bin/sh

if [ -L "$0" ]
then
  THIS_PATH="$(ls -ld -- "$0")"
  THIS_PATH="${THIS_PATH#*" $0 -> "}"
else
  THIS_PATH="$0"
fi

THIS_FILE="${THIS_PATH##*/}"

THIS_DIR="$(cd -P -- "${THIS_PATH%/*}" && pwd -P)"

#COMMIT_MESSAGE_FILE="${THIS_DIR}/${THIS_FILE}.msg"
COMMIT_MESSAGE_FILE="${THIS_DIR}/commit.msg"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "BRANCH: $BRANCH"
[ -z "$BRANCH" ] && echo "empty branch!" && exit 1

for k in *
do
  [ -d "$k/.git" ] && mv "$k/.git" "$k/.git_"
done

git fetch origin && \
git reset --hard origin/"$BRANCH"
EXIT_CODE="$?"

for k in *
do
  [ -d "$k/.git_" ] && mv "$k/.git_" "$k/.git"
done

if [ "$EXIT_CODE" = "0" ]
then
  COMMIT_MESSAGE="$(git show-branch --no-name HEAD)" && \
  echo "$COMMIT_MESSAGE" > "$COMMIT_MESSAGE_FILE"
fi

exit "$EXIT_CODE"
