#!/bin/sh

# authz opa
curl -i "${APISIX_ADMIN_URL}/plugin_configs?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "rewrite-authn-authz-plugins",
  "plugins":
  {
    "proxy-rewrite":
    {
      "regex_uri": ["^/(.*)/(.*)", "/$2"]
    },
    "openid-connect":
    {
      "bearer_only": false,
      "session":
      {
        "secret": "change_to_whatever_secret_you_want"
      },
      "use_pkce": true,
      "client_id": "'"${KEYCLOAK_CLIENT_ID}"'",
      "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
      "discovery": "https://'"${KEYCLOAK_HOST}"':'"${KEYCLOAK_PORT}"'/realms/'"${KEYCLOAK_REALM}"'/.well-known/openid-configuration",
      "scope": "openid profile",
      "redirect_uri": "https://'"${APISIX_HOST}"':'"${APISIX_PORT}"'/'"${KEYCLOAK_AUTHENTICATED_URI}"'/callback"
    },
    "opa":
    {
      "host": "http://dev.rpr-spa.it:8181",
      "policy": "rpr"
    }
  }
}'

# authz openfga 1
curl -i "${APISIX_ADMIN_URL}/plugin_configs?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "rewrite-authn-authz-plugins",
  "plugins":
  {
    "proxy-rewrite":
    {
      "regex_uri": ["^/(.*)/(.*)", "/$2"]
    },
    "openid-connect":
    {
      "bearer_only": false,
      "session":
      {
        "secret": "change_to_whatever_secret_you_want"
      },
      "use_pkce": true,
      "client_id": "'"${KEYCLOAK_CLIENT_ID}"'",
      "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
      "discovery": "https://'"${KEYCLOAK_HOST}"':'"${KEYCLOAK_PORT}"'/realms/'"${KEYCLOAK_REALM}"'/.well-known/openid-configuration",
      "scope": "openid profile",
      "redirect_uri": "https://'"${APISIX_HOST}"':'"${APISIX_PORT}"'/'"${KEYCLOAK_AUTHENTICATED_URI}"'/callback"
    },
    "authz-openfga":
    {
      "host": "http://dev.rpr-spa.it:8080",
      "store_id": "01KGPK43DH6P8HF3VTCRSMT8YY",
      "authorization_model_id": "01KGPZ3S05RFNY0DQ9H2E7XXJT",
      "user_jwt_claim": "sub",
      "relation": "assignee",
      "object_type": "role",
      "check":
      {
        "condition": "AND",
        "tuples":
        [
          {
            "user_id": "claim::sub",
            "relation": "assignee",
            "object_type": "role",
            "object_id": "view:transaction:any"
          },
          {
            "user_id": "claim::sub",
            "relation": "member",
            "object_type": "organization",
            "object_id": "org-a"
          }
        ]
      }
    }
  }
}'

# authz openfga 2
curl -i "${APISIX_ADMIN_URL}/plugin_configs?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "rewrite-authn-authz-plugins",
  "plugins":
  {
    "proxy-rewrite":
    {
      "regex_uri": ["^/(.*)/(.*)", "/$2"]
    },
    "openid-connect":
    {
      "bearer_only": false,
      "session":
      {
        "secret": "change_to_whatever_secret_you_want"
      },
      "use_pkce": true,
      "client_id": "'"${KEYCLOAK_CLIENT_ID}"'",
      "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
      "discovery": "https://'"${KEYCLOAK_HOST}"':'"${KEYCLOAK_PORT}"'/realms/'"${KEYCLOAK_REALM}"'/.well-known/openid-configuration",
      "scope": "openid profile",
      "redirect_uri": "https://'"${APISIX_HOST}"':'"${APISIX_PORT}"'/'"${KEYCLOAK_AUTHENTICATED_URI}"'/callback"
    },
    "openfga_authz":
    {
      "openfga_url": "http://dev.rpr-spa.it:8080",
      "store_id": "01KGPK43DH6P8HF3VTCRSMT8YY",
      "authorization_model_id": "01KGPZ3S05RFNY0DQ9H2E7XXJT",
      "resource_mappings":
      [
        {
          "resource_type": "resource",
          "uri_pattern": "/.*",
          "id_location": "last_part"
        }
      ]
    }
  }
}'

# route auth authz-keycloak java client
curl -i "${APISIX_ADMIN_URL}/routes?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "route-authn-authz-java",
  "uri": "/'"${KEYCLOAK_AUTHORIZATED_URI}-java"'/*",
  "plugins":
  {
    "openid-connect":
    {
      "bearer_only": false,
      "session":
      {
        "secret": "change_to_whatever_secret_you_want"
      },
      "use_pkce": true,
      "client_id": "'"${KEYCLOAK_CLIENT_ID}"'",
      "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
      "discovery": "https://'"${KEYCLOAK_HOST}"':'"${KEYCLOAK_PORT}"'/realms/'"${KEYCLOAK_REALM}"'/.well-known/openid-configuration",
      "scope": "openid profile",
      "redirect_uri": "https://'"${APISIX_HOST}"':'"${APISIX_PORT}"'/'"${KEYCLOAK_AUTHENTICATED_URI}"'/callback"
    },
    "proxy-rewrite":
    {
      "regex_uri": ["^/(.*)/(.*)", "/$2"]
    }
  },
  "upstream":
  {
    "scheme": "http",
    "nodes":
    {
      "dev.rpr-spa.it:8081": 1
    }
  }
}'



# authz-keycloak ---------------------------------------------------------------

curl -i "${APISIX_ADMIN_URL}/routes?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "route-auth",
  "uri": "/'"${KEYCLOAK_AUTHENTICATED_URI}"'/*",
  "plugins":
  {
    "authz-keycloak":
    {
      "client_id": "'"${KEYCLOAK_CLIENT_ID}"'",
      "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
      "discovery": "https://'"${KEYCLOAK_HOST}"':'"${KEYCLOAK_PORT}"'/realms/'"${KEYCLOAK_REALM}"'/.well-known/uma2-configuration",
      "policy_enforcement_mode": "ENFORCING",
      "permissions": ["ip-resource"],
      "lazy_load_paths": false,
      "http_method_as_scope": false,
      "ssl_verify": true
    },
    "proxy-rewrite":
    {
      "regex_uri": ["^/(.*)/(.*)", "/$2"]
    }
  },
  "service_id": "service-test-https"
}'

# get access token
curl "https://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token" \
  -d "client_id=${KEYCLOAK_CLIENT_ID}" \
  -d "client_secret=${KEYCLOAK_CLIENT_SECRET}" \
  -d "grant_type=client_credentials"

export ACCESS_TOKEN="REPLACE_WITH_ACTUAL_ACCESS_TOKEN"

# test access token
curl http://127.0.0.1:9080/auth/ip -H "Authorization: Bearer ${ACCESS_TOKEN}"



#-------------------------------------------------------------------------------

# full path redirect_uri
curl -i "${APISIX_ADMIN_URL}/plugin_configs?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "plugins-authn",
  "plugins":
  {
    "proxy-rewrite":
    {
      "regex_uri": ["^/(.*)/(.*)", "/$2"]
    },
    "openid-connect":
    {
      "client_id": "'"${KEYCLOAK_CLIENT_ID_AUTHN}"'",
      "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
      "discovery": "https://'"${KEYCLOAK_HOST}"':'"${KEYCLOAK_PORT}"'/realms/'"${KEYCLOAK_REALM}"'/.well-known/openid-configuration",
      "redirect_uri": "https://'"${APISIX_HOST}"':'"${APISIX_PORT}"'/'"${APISIX_AUTHENTICATED_URI}"'/callback",
      "scope": "openid profile",
      "use_pkce": true,
      "bearer_only": false,
      "session":
      {
        "secret": "change_to_whatever_secret_you_want"
      }
    }
  }
}'
