#!/bin/sh

# klaro cookie consent ---------------------------------------------------------

var headReplace = `"
  <script>
    var klaroConfig =
    {
      elementID: 'klaro',
      mustConsent: true,
      privacyPolicy: '/privacy-policy.html',
      hideDeclineAll: true,
      lang: 'it',
      services:
      [
        {
          name: 'rpr',
          title: 'Servizi RpR',
          purposes: ['analytics'],
          required: true,
          cookies:
          [
            ['session'], // Cancella questi cookie se il consenso viene revocato
            ['_gid']
          ]
        },
        {
          name: 'google-analytics',
          title: 'Google Analytics',
          purposes: ['analytics'],
          required: false, // Se true, l'utente non può disattivarlo
          cookies:
          [
            [/^_ga/, '/', 'google.com'], // Cancella questi cookie se il consenso viene revocato
            ['_gid']
          ]
        }
      ],

      translations:
      {
        it:
        {
          consentModal:
          {
            title: 'Informazioni sui Cookie',
            description: 'Qui puoi vedere e gestire le informazioni che raccogliamo su di te.',
          },
          consentNotice:
          {
            changeDescription: 'Ci sono state modifiche dall\\\\\\'ultima visita, aggiorna le tue scelte.',
            description: 'Utilizziamo i cookie per ottimizzare il nostro sito web.',
            learnMore: 'Scopri di più o personalizza',
            acceptAll: 'Accetta tutti',
            declineAll: 'Rifiuta tutti'
          },
          purposes:
          {
            analytics: 'Statistiche e Analisi'
          }
        }
      }
    };
  </script>

  <script defer type='text/javascript' src='https://cdn.kiprotect.com/klaro/latest/klaro.js'></script>
</head>
"`;

headReplace = JSON.parse(headReplace.replace(/\n/g, '\\\\n').trim());

const apisixPluginConfig = `
{
  "filters": [
    {
      "scope": "once",
      "regex": "</head>",
      "replace": "${headReplace}"
    }
  ]
}
`;

console.log(apisixPluginConfig);

# cookie consent (orest bida) --------------------------------------------------

var headReplace = `"
  <link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.1.0/dist/cookieconsent.css' />
  <script src='https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.1.0/dist/cookieconsent.umd.js'></script>
</head>
"`;

headReplace = JSON.parse(headReplace.replace(/\s+/g, ' ').trim());

var bodyReplace = `"
<script>
CookieConsent.run(
{
  categories:
  {
    necessary:
    {
      enabled: true,  // this category is enabled by default
      readOnly: true  // this category cannot be disabled
    },
    analytics: {}
  },

  language:
  {
    default: 'en',
    translations:
    {
      en:
      {
        consentModal:
        {
          title: 'We use cookies',
          description: 'Cookie modal description',
          acceptAllBtn: 'Accept all',
          acceptNecessaryBtn: 'Reject all',
          showPreferencesBtn: 'Manage Individual preferences'
        },
        preferencesModal:
        {
          title: 'Manage cookie preferences',
          acceptAllBtn: 'Accept all',
          acceptNecessaryBtn: 'Reject all',
          savePreferencesBtn: 'Accept current selection',
          closeIconLabel: 'Close modal',
          sections:
          [
            {
              title: 'Somebody said ... cookies?',
              description: 'I want one!'
            },
            {
              title: 'Strictly Necessary cookies',
              description: 'These cookies are essential for the proper functioning of the website and cannot be disabled.',

              //this field will generate a toggle linked to the 'necessary' category
              linkedCategory: 'necessary'
            },
            {
              title: 'Performance and Analytics',
              description: 'These cookies collect information about how you use our website. All of the data is anonymized and cannot be used to identify you.',
              linkedCategory: 'analytics'
            },
            {
              title: 'More information',
              description: 'For any queries in relation to my policy on cookies and your choices, please contact us'
            }
          ]
        }
      }
    }
  }
});
</script>
</body>
"`;

bodyReplace = JSON.parse(bodyReplace.replace(/\s+/g, ' ').trim());

const apisixPluginConfig = `
{
  "filters": [
    {
      "scope": "once",
      "regex": "</head>",
      "replace": "${headReplace}"
    },
    {
      "scope": "once",
      "regex": "</body>",
      "replace": "${bodyReplace}"
    }
  ]
}
`;

console.log(apisixPluginConfig);

#-------------------------------------------------------------------------------

export APISIX_RELATIVE_REDIRECT_URI="/callback"
export APISIX_PUBLIC_URI="pub"
export APISIX_AUTHENTICATED_URI="authn"
export APISIX_AUTHORIZATED_URI="authz"



# upstreams --------------------------------------------------------------------

curl -i "${APISIX_ADMIN_URL}/upstreams?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "upstream-test-http",
  "name": "upstream-test-http",
  "scheme": "http",
  "retries": 1,
  "type": "roundrobin",
  "nodes":
  {
    "httpbin.org:80": 1
  }
}'

curl -i "${APISIX_ADMIN_URL}/upstreams?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "upstream-test-https",
  "name": "upstream-test-https",
  "scheme": "https",
  "retries": 1,
  "type": "roundrobin",
  "nodes":
  {
    "httpbin.org:443": 1
  }
}'



# services ---------------------------------------------------------------------

curl -i "${APISIX_ADMIN_URL}/services?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "service-test-http",
  "name": "service-test-http",
  "upstream_id": "upstream-test-http"
}'

curl -i "${APISIX_ADMIN_URL}/services?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "service-test-https",
  "name": "service-test-https",
  "upstream_id": "upstream-test-https"
}'



# services ---------------------------------------------------------------------

curl -i "${APISIX_ADMIN_URL}/services?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "service-test-http",
  "name": "service-test-http",
  "upstream":
  {
    "scheme": "http",
    "retries": 1,
    "type": "roundrobin",
    "nodes":
    {
      "httpbin.org:80": 1
    }
  }
}'

curl -i "${APISIX_ADMIN_URL}/services?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "service-test-https",
  "name": "service-test-https",
  "upstream":
  {
    "scheme": "https",
    "retries": 1,
    "type": "roundrobin",
    "nodes":
    {
      "httpbin.org:443": 1
    }
  }
}'

curl -i "${APISIX_ADMIN_URL}/services?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "service-test-java-http",
  "name": "service-test-java-http",
  "upstream":
  {
    "scheme": "http",
    "retries": 1,
    "type": "roundrobin",
    "nodes":
    {
      "dev.rpr-spa.it:8081": 1
    }
  }
}'



# plugins ----------------------------------------------------------------------

curl -i "${APISIX_ADMIN_URL}/plugin_configs?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "plugins-rewrite",
  "plugins":
  {
    "proxy-rewrite":
    {
      "regex_uri": ["^/(.*)/(.*)", "/$2"]
    }
  }
}'

curl -i "${APISIX_ADMIN_URL}/plugin_configs?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "plugins-authn",
  "plugins":
  {
    "proxy-rewrite":
    {
      "regex_uri": ["^/(.*)/(.*)", "/$2"]
    },
    "openid-connect":
    {
      "client_id": "'"${KEYCLOAK_CLIENT_ID_AUTHN}"'",
      "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
      "discovery": "https://'"${KEYCLOAK_HOST}"':'"${KEYCLOAK_PORT}"'/realms/'"${KEYCLOAK_REALM}"'/.well-known/openid-configuration",
      "redirect_uri": "'"${APISIX_RELATIVE_REDIRECT_URI}"'",
      "scope": "openid profile",
      "use_pkce": true,
      "bearer_only": false,
      "session":
      {
        "secret": "change_to_whatever_secret_you_want"
      }
    }
  }
}'

curl -i "${APISIX_ADMIN_URL}/plugin_configs?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "plugins-authn-authz",
  "plugins":
  {
    "proxy-rewrite":
    {
      "regex_uri": ["^/(.*)/(.*)", "/$2"]
    },
    "openid-connect":
    {
      "client_id": "'"${KEYCLOAK_CLIENT_ID_AUTHN_AUTHZ}"'",
      "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
      "discovery": "https://'"${KEYCLOAK_HOST}"':'"${KEYCLOAK_PORT}"'/realms/'"${KEYCLOAK_REALM}"'/.well-known/openid-configuration",
      "redirect_uri": "'"${APISIX_RELATIVE_REDIRECT_URI}"'",
      "scope": "openid profile",
      "use_pkce": true,
      "bearer_only": false,
      "access_token_in_authorization_header": true,
      "session":
      {
        "secret": "change_to_whatever_secret_you_want"
      }
    }
  }
}'

curl -i "${APISIX_ADMIN_URL}/plugin_configs?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "plugins-authn-authz-dynamic",
  "plugins":
  {
    "proxy-rewrite":
    {
      "regex_uri": ["^/(.*)/(.*)", "/$2"]
    },
    "openid-connect":
    {
      "client_id": "'"${KEYCLOAK_CLIENT_ID_AUTHN_AUTHZ}"'",
      "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
      "discovery": "https://'"${KEYCLOAK_HOST}"':'"${KEYCLOAK_PORT}"'/realms/'"${KEYCLOAK_REALM}"'/.well-known/openid-configuration",
      "redirect_uri": "'"${APISIX_RELATIVE_REDIRECT_URI}"'",
      "scope": "openid profile",
      "use_pkce": true,
      "bearer_only": false,
      "access_token_in_authorization_header": true,
      "session":
      {
        "secret": "change_to_whatever_secret_you_want"
      }
    },
    "authz-keycloak":
    {
      "client_id": "'"${KEYCLOAK_CLIENT_ID_AUTHN_AUTHZ}"'",
      "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
      "discovery": "https://'"${KEYCLOAK_HOST}"':'"${KEYCLOAK_PORT}"'/realms/'"${KEYCLOAK_REALM}"'/.well-known/uma2-configuration",
      "policy_enforcement_mode": "ENFORCING",
      "lazy_load_paths": true,
      "http_method_as_scope": false,
      "ssl_verify": true
    }
  }
}'

curl -i "${APISIX_ADMIN_URL}/plugin_configs?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "plugins-test-authn-authz",
  "plugins":
  {
    "proxy-rewrite":
    {
      "regex_uri": ["^/(.*)/(.*)", "/$2"]
    },
    "openid-connect":
    {
      "client_id": "'"${KEYCLOAK_CLIENT_ID_AUTHN_AUTHZ}"'",
      "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
      "discovery": "https://'"${KEYCLOAK_HOST}"':'"${KEYCLOAK_PORT}"'/realms/'"${KEYCLOAK_REALM}"'/.well-known/openid-configuration",
      "redirect_uri": "'"${APISIX_RELATIVE_REDIRECT_URI}"'",
      "scope": "openid profile",
      "use_pkce": true,
      "bearer_only": false,
      "access_token_in_authorization_header": true,
      "session":
      {
        "secret": "change_to_whatever_secret_you_want"
      }
    },
    "authz-keycloak":
    {
      "client_id": "'"${KEYCLOAK_CLIENT_ID_AUTHN_AUTHZ}"'",
      "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
      "discovery": "https://'"${KEYCLOAK_HOST}"':'"${KEYCLOAK_PORT}"'/realms/'"${KEYCLOAK_REALM}"'/.well-known/uma2-configuration",
      "policy_enforcement_mode": "ENFORCING",
      "lazy_load_paths": false,
      "http_method_as_scope": false,
      "permissions": ["ip-resource"],
      "ssl_verify": true
    }
  }
}'



# routes -----------------------------------------------------------------------

curl -i "${APISIX_ADMIN_URL}/routes?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "route-test-pub",
  "uri": "/test-'"${APISIX_PUBLIC_URI}"'/*",
  "plugin_config_id": "plugins-rewrite",
  "service_id": "service-test-https"
}'

curl -i "${APISIX_ADMIN_URL}/routes?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "route-test-authn",
  "uri": "/test-'"${APISIX_AUTHENTICATED_URI}"'/*",
  "plugin_config_id": "plugins-authn",
  "service_id": "service-test-https"
}'
