#!/bin/sh

# amd64
# wget -O - http://repos.apiseven.com/pubkey.gpg | sudo apt-key add -
# wget -O - http://repos.apiseven.com/pubkey.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/apisix-repo.gpg
# echo "deb http://repos.apiseven.com/packages/debian bullseye main" | sudo tee /etc/apt/sources.list.d/apisix.list

curl -fsSL https://repos.apiseven.com/pubkey.gpg | sudo gpg --dearmor -o /usr/share/keyrings/apisix-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/apisix-archive-keyring.gpg] https://repos.apiseven.com/packages/debian bullseye main" | sudo tee /etc/apt/sources.list.d/apisix.list
# echo "deb [signed-by=/usr/share/keyrings/apisix-archive-keyring.gpg] https://repos.apiseven.com/packages/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/apisix.list

# arm64
#wget -O - http://repos.apiseven.com/pubkey.gpg | sudo apt-key add -
#echo "deb http://repos.apiseven.com/packages/arm64/debian bullseye main" | sudo tee /etc/apt/sources.list.d/apisix.list

sudo apt update
sudo apt install -y apisix

sudo apisix init

sudo nano /usr/local/apisix/conf/config.yaml

sudo apisix start
# sudo apisix start --config "/usr/local/apisix/conf/config.yaml"
#sudo apisix stop
#sudo apisix help
#systemctl start apisix
#systemctl stop apisix

systemctl list-unit-files --state=enabled
systemctl list-unit-files --state=running

# validate
curl "http://127.0.0.1:9080" --head | grep Server
