#!/bin/sh

# environment variables --------------------------------------------------------

export APISIX_KEY="knpgKvNuusqgtxbsIhPuqGWEBWpDJwHg"
export APISIX_ADMIN_URL="http://127.0.0.1:9180/apisix/admin"

export KEYCLOAK_CLIENT_ID_AUTHN="apisix-authn"
export KEYCLOAK_CLIENT_ID_AUTHN_AUTHZ="apisix-authn-authz"
export KEYCLOAK_CLIENT_SECRET="WiLDWAtS9FMMjSzAP7fElIzvHn9ftrTU"



export PROXY_HOST="apps.rpr-spa.it"

export APISIX_HOST="apisix.rpr-spa.it"
export APISIX_PORT="9443"

export KEYCLOAK_HOST="keycloak.rpr-spa.it"
export KEYCLOAK_PORT="8443"
export KEYCLOAK_REALM="rpr"

export KEYCLOAK_REALM_URL="https://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}"
#export KEYCLOAK_REALM_URL="https://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/keycloak/realms/${KEYCLOAK_REALM}"

export AUTHN_DISCOVERY_URL="${KEYCLOAK_REALM_URL}/.well-known/openid-configuration"
export AUTHZ_DISCOVERY_URL="${KEYCLOAK_REALM_URL}/.well-known/uma2-configuration"

export AUTHN_REDIRECT_BASE_URL="https://${APISIX_HOST}:${APISIX_PORT}"
#export AUTHN_REDIRECT_BASE_URL="https://${PROXY_HOST}/apisix"



# ssl --------------------------------------------------------------------------

curl -i "${APISIX_ADMIN_URL}/ssls?api_key=${APISIX_KEY}" -X PUT -d '
{
  "id": "apisix-ssl",
  "type": "server",
  "status": 1,
  "sni": "'"${APISIX_HOST}"'",
  "cert": "'"$(cat "/m/certs/rpr-spa.pem")"'",
  "key": "'"$(cat "/m/certs/rpr-spa.key")"'",
  "ssl_protocols": ["TLSv1.2", "TLSv1.3"]
}'



# functions --------------------------------------------------------------------

create_service()
{
(
  ID="$1"
  SCHEME="$2"
  ADDRESS_PORT="$3"

  curl -i "${APISIX_ADMIN_URL}/services?api_key=${APISIX_KEY}" -X PUT -d '
  {
    "id": "'"${ID}"'",
    "name": "'"${ID}"'",
    "upstream":
    {
      "scheme": "'"${SCHEME}"'",
      "retries": 1,
      "type": "roundrobin",
      "nodes":
      {
        "'"${ADDRESS_PORT}"'": 1
      }
    }
  }'
)
}



create_authenticated_route()
{
(
  ID="$1"
  URI="$2"
  PREFIX_REMOVE="$3"
  SERVICE_ID="$4"

  curl -i "${APISIX_ADMIN_URL}/routes?api_key=${APISIX_KEY}" -X PUT -d '
  {
    "id": "'"${ID}"'",
    "uris": ["/'"${URI}"'", "/'"${URI}"'/*"],
    "plugins":
    {
      "proxy-rewrite":
      {
        "regex_uri": ["^/'"${PREFIX_REMOVE}"'/(.*)", "/$1"]
      },
      "openid-connect":
      {
        "client_id": "'"${KEYCLOAK_CLIENT_ID_AUTHN}"'",
        "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
        "discovery": "'"${AUTHN_DISCOVERY_URL}"'",
        "redirect_uri": "'"${AUTHN_REDIRECT_BASE_URL}"'/'"${URI}"'/callback",
        "scope": "openid profile",
        "use_pkce": true,
        "bearer_only": false,
        "access_token_in_authorization_header": true,
        "set_userinfo_header": true,
        "session":
        {
          "secret": "change_to_whatever_secret_you_want"
        }
      }
    },
    "service_id": "'"${SERVICE_ID}"'"
  }'
)
}



create_authorized_route()
{
(
  ID="$1"
  URI="$2"
  PREFIX_REMOVE="$3"
  RESOURCE="$4"
  SERVICE_ID="$5"

  curl -i "${APISIX_ADMIN_URL}/routes?api_key=${APISIX_KEY}" -X PUT -d '
  {
    "id": "'"${ID}"'",
    "uris": ["/'"${URI}"'", "/'"${URI}"'/*"],
    "plugins":
    {
      "proxy-rewrite":
      {
        "regex_uri": ["^/'"${PREFIX_REMOVE}"'/(.*)", "/$1"]
      },
      "openid-connect":
      {
        "client_id": "'"${KEYCLOAK_CLIENT_ID_AUTHN_AUTHZ}"'",
        "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
        "discovery": "'"${AUTHN_DISCOVERY_URL}"'",
        "redirect_uri": "'"${AUTHN_REDIRECT_BASE_URL}"'/'"${URI}"'/callback",
        "scope": "openid profile",
        "use_pkce": true,
        "bearer_only": false,
        "access_token_in_authorization_header": true,
        "set_userinfo_header": true,
        "session":
        {
          "secret": "change_to_whatever_secret_you_want"
        }
      },
      "authz-keycloak":
      {
        "client_id": "'"${KEYCLOAK_CLIENT_ID_AUTHN_AUTHZ}"'",
        "client_secret": "'"${KEYCLOAK_CLIENT_SECRET}"'",
        "discovery": "'"${AUTHZ_DISCOVERY_URL}"'",
        "policy_enforcement_mode": "ENFORCING",
        "lazy_load_paths": false,
        "http_method_as_scope": false,
        "permissions": ["'"${RESOURCE}"'"],
        "ssl_verify": true
      }
    },
    "service_id": "'"${SERVICE_ID}"'"
  }'
)
}



# call functions ---------------------------------------------------------------

create_service "service-test-http" "http" "httpbin.org:80"
create_service "service-test-https" "https" "httpbin.org:443"
create_service "service-test-java-http" "http" "dev.rpr-spa.it:8081"

create_authenticated_route "route-authn-java" "java" "java" "service-test-java-http"

create_authorized_route "route-authz-ip" "authz/ip" "authz" "ip-resource" "service-test-https"
create_authorized_route "route-authz-headers" "authz/headers" "authz" "headers-resource" "service-test-https"
create_authorized_route "route-authz-response-headers" "authz/response-headers" "authz" "response-headers-resource" "service-test-https"

create_service "service-https-apache2" "https" "127.0.0.1:443"
create_authorized_route "route-authz-webgis" "authz/webgis" "authz" "webgis-resource" "service-https-apache2"

create_service "service-https-webgis-test" "https" "webgisrpr.rpr-spa.it:443"
create_authorized_route "route-authz-gis-server" "authz/gis-server" "authz/gis-server" "webgis-resource" "service-https-webgis-test"
