#!/bin/sh

. realpaths.lib.sh
# . waituser.lib.sh

#-------------------------------------------------------------------------------

realpaths

if [ -z "$*" ]
then
  set -- "$(menu gitman rsudo-jobs)"
fi

"$@"

# waituser
