#!/bin/sh

. realpaths.lib.sh
# . waituser.lib.sh

#-------------------------------------------------------------------------------

realpaths

if [ -z "$*" ]
then
  # set -- "$(menu ./app/app=app ./gitman/gitman=gitman rsudo ls)"
  set -- "$(menu app bin desktop gitman rsudo-jobs)"
fi

"$@"

# waituser
