#!/bin/sh

#-------------------------------------------------------------------------------

. env.lib.sh
. enc.lib.sh
. menu.lib.sh
. waituser.lib.sh

#-------------------------------------------------------------------------------

menuset nomulti
menuset keys "e:d"

MENU_HEADER="FILE ENCODING / DECODING: e=encode, d=decode"
MENU_FOOTER=""

env_read "key file selection" tui head "$MENU_HEADER" "$MENU_FOOTER" tui-menu-file .

if [ "$key" = "esc" ] || [ "$key" = "q" ]
then
  false
elif [ ! -f "$file" ]
then
  echo "not a file: $file"
else
  if [ "$key" = "e" ]
  then
    file_enc "$file"
  elif [ "$key" = "d" ]
  then
    file_dec "$file"
  fi
fi

waituser
