#!/bin/sh

#-------------------------------------------------------------------------------

# . realpaths.lib.sh
. waituser.lib.sh
. enc.lib.sh
. menu.lib.sh

#-------------------------------------------------------------------------------

menu_dir()
(
  if [ ! -d "$1" ]
  then
    return 1
  fi

  cd "$1"

  array DIR_ARRAY
  array DIR_ARRAY add ".."
  for k in ..?* .[!.]* *
  do
    if [ -e "$k" ]
    then
      array DIR_ARRAY add "$k"
    fi
  done

  FILE="$(eval menu $(array DIR_ARRAY get))"

  if [ -n "$FILE" ]
  then
    echo "$(cd -L -- "$1" && pwd -L)/$FILE"
  fi
)

#-------------------------------------------------------------------------------

# realpaths

menuset nomulti
menuset keys "e:d"
menuset header "FILE ENCODING / DECODING: enter=choose, e=encode, d=decode"

menufs "key" "file" "selection"

if [ ! -f "$file" ]
then
  echo "not a file: $file"
else
  if [ "$key" = "enter" ]
  then
    eval "$(menuset keys "" && menu file_enc="Encode file: $file" file_dec="Decode file: $file") '$file'"
  elif [ "$key" = "e" ]
  then
    file_enc "$file"
  elif [ "$key" = "d" ]
  then
    file_dec "$file"
  fi
fi

waituser
