#!/bin/sh

if [ -L "$0" ]
then
  THIS_PATH="$(ls -ld -- "$0")"
  THIS_PATH="${THIS_PATH#*" $0 -> "}"
else
  THIS_PATH="$0"
fi

THIS_FILE="${THIS_PATH##*/}"

THIS_DIR="$(cd -P -- "${THIS_PATH%/*}" && pwd -P)"

cd "$THIS_DIR"
PATH="$THIS_DIR:$PATH"
cd ..



git fetch origin

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "BRANCH: $BRANCH"
[ -z "$BRANCH" ] && echo "empty branch!" && exit 1

for k in *
do
  [ -d "$k/.git" ] && mv "$k/.git" "$k/.git_"
done

git reset --hard origin/"$BRANCH"
EXIT_CODE="$?"

for k in *
do
  [ -d "$k/.git_" ] && mv "$k/.git_" "$k/.git"
done

echo ""
echo ""
echo ""
echo "--------------------------------------------------------------------------------"
read -p "press ENTER to exit" test

exit "$EXIT_CODE"

