#!/bin/sh

. realpaths.lib.sh

#-------------------------------------------------------------------------------

realpaths

if [ -z "$2" ]
then
  node "$THIS_DIR/jsc.js" "${1%/*}" "${1##*/}"
else
  node "$THIS_DIR/jsc.js" "${1%/*}" "${1##*/}" > "${2}"
  
  if [ "${2}" != "${2%.js}" ]
  then
    echo "type javascript"
    MINIFIED_FILE="${2%.js}.min.js"
    npx --yes google-closure-compiler --js="$2" --js_output_file="$MINIFIED_FILE"
  elif [ "${2}" != "${2%.css}" ]
  then
    echo "type css"
    MINIFIED_FILE="${2%.css}.min.css"
    npx --yes uglifycss "$2" > "$MINIFIED_FILE"
  else
    echo "type unknown -> no minification available"
    MINIFIED_FILE="$2"
  fi

  gzip < "$MINIFIED_FILE" > "${MINIFIED_FILE}.gz"
fi
