#!/bin/sh

. log.lib.sh

#-------------------------------------------------------------------------------

log_exec_all_to_stdout()
{
  "$@" 2>&1
}

#-------------------------------------------------------------------------------

log_exec_all_to_stdout_and_to_file()
{
  if [ -z "$LOG_STDALL_FILE" ]
  then
    log_fatal "LOG_STDALL_FILE is null"
    return 1
  fi

  "$@" >"$LOG_STDALL_FILE"
}

#-------------------------------------------------------------------------------

log_exec_stdout_stderr_to_files()
{
  if [ -z "$LOG_STDOUT_FILE" ]
  then
    log_fatal "LOG_STDOUT_FILE is null"
    return 1
  fi

  if [ -z "$LOG_STDERR_FILE" ]
  then
    log_fatal "LOG_STDERR_FILE is null"
    return 1
  fi

  "$@" 1>"$LOG_STDOUT_FILE" 2>"$LOG_STDERR_FILE"
}

#-------------------------------------------------------------------------------

log_exec_stdout_stderr_stdall_to_files()
{
  if [ -z "$LOG_STDOUT_FILE" ]
  then
    log_fatal "LOG_STDOUT_FILE is null"
    return 1
  fi

  if [ -z "$LOG_STDERR_FILE" ]
  then
    log_fatal "LOG_STDERR_FILE is null"
    return 1
  fi

  if [ -z "$LOG_STDALL_FILE" ]
  then
    log_fatal "LOG_STDALL_FILE is null"
    return 1
  fi

  rm -f "$LOG_STDOUT_FILE" "$LOG_STDERR_FILE" "$LOG_STDALL_FILE"
  touch "$LOG_STDOUT_FILE" "$LOG_STDERR_FILE" "$LOG_STDALL_FILE"

  trap "log_cleanup" INT QUIT TERM HUP PIPE ABRT TSTP EXIT

  tail -f -n -100 "$LOG_STDOUT_FILE" >> "$LOG_STDALL_FILE" &
  PID_LOG_STDOUT="$!"
  tail -f -n -100 "$LOG_STDERR_FILE" >> "$LOG_STDALL_FILE" &
  PID_LOG_STDERR="$!"

  "$@" 1>"$LOG_STDOUT_FILE" 2>"$LOG_STDERR_FILE" || exit "$?"
}

#-------------------------------------------------------------------------------

log_exec_all_to_stdout_and_stdout_stderr_stdall_to_files()
{
  if [ -z "$LOG_STDOUT_FILE" ]
  then
    log_fatal "LOG_STDOUT_FILE is null"
    return 1
  fi

  if [ -z "$LOG_STDERR_FILE" ]
  then
    log_fatal "LOG_STDERR_FILE is null"
    return 1
  fi

  if [ -z "$LOG_STDALL_FILE" ]
  then
    log_fatal "LOG_STDALL_FILE is null"
    return 1
  fi

  rm -f "$LOG_STDOUT_FILE" "$LOG_STDERR_FILE" "$LOG_STDALL_FILE"
  touch "$LOG_STDOUT_FILE" "$LOG_STDERR_FILE" "$LOG_STDALL_FILE"

  trap "log_cleanup" INT QUIT TERM HUP PIPE ABRT TSTP EXIT

  tail -f -n -100 "$LOG_STDOUT_FILE" >> "$LOG_STDALL_FILE" &
  PID_LOG_STDOUT="$!"
  tail -f -n -100 "$LOG_STDERR_FILE" >> "$LOG_STDALL_FILE" &
  PID_LOG_STDERR="$!"
  tail -f -n -100 "$LOG_STDALL_FILE" &
  PID_LOG_STDALL="$!"

  "$@" 1>"$LOG_STDOUT_FILE" 2>"$LOG_STDERR_FILE" || exit "$?"
}

#-------------------------------------------------------------------------------

log_cleanup()
{
  EXIT_CODE="$?"

  log_warn "log_cleanup - EXIT_CODE: $EXIT_CODE"

  if [ -z "$PID_LOG_STDOUT" ]
  then
    kill "$PID_LOG_STDOUT" 1>/dev/null 2>/dev/null
  fi

  if [ -z "$PID_LOG_STDERR" ]
  then
    kill "$PID_LOG_STDERR" 1>/dev/null 2>/dev/null
  fi

  if [ -z "$PID_LOG_STDALL" ]
  then
    kill "$PID_LOG_STDALL" 1>/dev/null 2>/dev/null
  fi

  exit $EXIT_CODE
}

#-------------------------------------------------------------------------------

# log_exec_all_to_stdout
# log_exec_all_to_stdout_and_to_file
# log_exec_stdout_stderr_to_files
# log_exec_stdout_stderr_stdall_to_files
# log_exec_all_to_stdout_and_stdout_stderr_stdall_to_files

log_exec()
{
  log_exec_all_to_stdout_and_stdout_stderr_stdall_to_files "$@"
  exit "$?"

  if [ -n "$LOG_STDOUT" ]
  then
# log_exec_all_to_stdout
# log_exec_all_to_stdout_and_to_file
# log_exec_all_to_stdout_and_stdout_stderr_stdall_to_files
  else
# log_exec_stdout_stderr_to_files
# log_exec_stdout_stderr_stdall_to_files
  fi

  if [ -z "$LOG_STDOUT" ] &&  [ -z "$LOG_ALL_FILES" ]
  then
    log_exec_all_to_stdout "$@"
  elif [ -z "$LOG_STDOUT" ] &&  [ -n "$LOG_ALL_FILES" ]
  then
    log_exec_all_to_stdout_and_to_file "$@"
  elif [ -n "$LOG_STDOUT" ] &&  [ -z "$LOG_ALL_FILES" ]
  then
    log_exec_stdout_stderr_stdall_to_files "$@"
  else
    log_exec_all_to_stdout_and_stdout_stderr_stdall_to_files "$@"
  fi

  if [ -z "$LOG_FILES_PATH_PREFIX_NAME" ]
  then
    log_trace "LOG_FILES_PATH_PREFIX_NAME null, setting default"
    LOG_FILES_PATH_PREFIX_NAME="log_$(basename "${1}")"
  fi

  LOG_FILES_PATH_PREFIX="${LOG_FILES_PATH_PREFIX_DIR}/${LOG_FILES_PATH_PREFIX_NAME}"

  if [ -n "$LOG_FILES_PATH_PREFIX_UNIQUE" ]
  then
    log_trace "using LOG_FILES_PATH_PREFIX_UNIQUE"
    LOG_FILES_PATH_PREFIX="${LOG_FILES_PATH_PREFIX}_${LOG_FILES_PATH_PREFIX_UNIQUE}"
  fi
}

#-------------------------------------------------------------------------------

export LOG_LEVEL

LOG_STDOUT=""
LOG_ALL_FILES=""

while [ "$1" != "--" ] && [ "$#" -gt "0" ]
do
  case "$1" in
    -l | --level) shift; log_level "$1";;
    -d | --dir)
      shift
      if [ -z "$1" ]
      then
        log_fatal "--dir: empty arg"
        return 1
      fi
      LOG_FILES_PATH_PREFIX_DIR="$1"
    ;;
    -n | --name)
      shift
      if [ -z "$1" ]
      then
        log_fatal "--name: empty arg"
        return 1
      fi
      LOG_FILES_PATH_PREFIX_NAME="$1"
    ;;
    -u | --unique) LOG_FILES_PATH_PREFIX_UNIQUE="$(date +%Y-%m-%d_%H-%M-%S_%N)_$$";;
    - | -o | --stdout) LOG_STDOUT="true";;
    -a | --all) LOG_ALL_FILES="true";;
    *) log_fatal "bad arguments"; exit 1;;
  esac
  shift
done
shift



# set file names
LOG_FILES_PATH_PREFIX=""

if [ -z "$LOG_FILES_PATH_PREFIX_DIR" ]
then
  log_trace "LOG_FILES_PATH_PREFIX_DIR null, setting default"
  LOG_FILES_PATH_PREFIX_DIR="."
fi

if [ -z "$LOG_FILES_PATH_PREFIX_NAME" ]
then
  log_trace "LOG_FILES_PATH_PREFIX_NAME null, setting default"
  LOG_FILES_PATH_PREFIX_NAME="log_$(basename "${1}")"
fi

LOG_FILES_PATH_PREFIX="${LOG_FILES_PATH_PREFIX_DIR%/}/${LOG_FILES_PATH_PREFIX_NAME}"

if [ -n "$LOG_FILES_PATH_PREFIX_UNIQUE" ]
then
  log_trace "using LOG_FILES_PATH_PREFIX_UNIQUE"
  LOG_FILES_PATH_PREFIX="${LOG_FILES_PATH_PREFIX}_${LOG_FILES_PATH_PREFIX_UNIQUE}"
fi

log_debug "LOG_FILES_PATH_PREFIX: $LOG_FILES_PATH_PREFIX"

mkdir -p "$(dirname "$LOG_FILES_PATH_PREFIX")"

LOG_STDOUT_FILE="${LOG_FILES_PATH_PREFIX}_stdout.log"
LOG_STDERR_FILE="${LOG_FILES_PATH_PREFIX}_stderr.log"
LOG_STDALL_FILE="${LOG_FILES_PATH_PREFIX}_stdall.log"

log_debug "LOG_STDOUT_FILE=$LOG_STDOUT_FILE - LOG_STDERR_FILE=$LOG_STDERR_FILE - LOG_STDALL_FILE=$LOG_STDALL_FILE"



# exec
if [ "$#" -gt "0" ]
then
  log_exec "$@"
else
  log_debug "entering log subshell - sh"
  log_info "*** LOG SHELL (sh) *************************************************************"
  log_exec sh -i
  log_info "*** LOG SHELL (sh) - exit ******************************************************"
fi
