#!/bin/sh

. log.lib.sh

#-------------------------------------------------------------------------------

log_cleanup()
{
  EXIT_CODE="$?"

  log_warn "log_cleanup - EXIT_CODE: $EXIT_CODE"

  if [ -z "$PID_LOG_STDOUT" ]
  then
    kill "$PID_LOG_STDOUT" 1>/dev/null 2>/dev/null
  fi

  if [ -z "$PID_LOG_STDERR" ]
  then
    kill "$PID_LOG_STDERR" 1>/dev/null 2>/dev/null
  fi

  if [ -z "$PID_LOG_STDALL" ]
  then
    kill "$PID_LOG_STDALL" 1>/dev/null 2>/dev/null
  fi

  exit $EXIT_CODE
}

#-------------------------------------------------------------------------------

log_exec()
{
  if [ "$LOG_TO_FILES" = "false" ]
  then
    if [ "$LOG_TO_STDOUT" = "true" ]
    then
      "$@"
    else
      log_fatal "log_exec: bad switches combination! LOG_TO_STDOUT=$LOG_TO_STDOUT - LOG_TO_FILES=$LOG_TO_FILES - LOG_SYNC=$LOG_SYNC"
      exit 1
    fi
  elif [ "$LOG_TO_FILES" = "true" ]
  then
    # set file names
    LOG_FILES_PATH_PREFIX=""

    if [ -z "$LOG_FILES_PATH_PREFIX_DIR" ]
    then
      log_trace "LOG_FILES_PATH_PREFIX_DIR null, setting default"
      LOG_FILES_PATH_PREFIX_DIR="."
    fi

    if [ -z "$LOG_FILES_PATH_PREFIX_NAME" ]
    then
      log_trace "LOG_FILES_PATH_PREFIX_NAME null, setting default"
      LOG_FILES_PATH_PREFIX_NAME="log_$(basename "${1}")"
    fi

    LOG_FILES_PATH_PREFIX="${LOG_FILES_PATH_PREFIX_DIR%/}/${LOG_FILES_PATH_PREFIX_NAME}"

    if [ -n "$LOG_FILES_PATH_PREFIX_UNIQUE" ]
    then
      log_trace "using LOG_FILES_PATH_PREFIX_UNIQUE"
      LOG_FILES_PATH_PREFIX="${LOG_FILES_PATH_PREFIX}_${LOG_FILES_PATH_PREFIX_UNIQUE}"
    fi

    log_debug "LOG_FILES_PATH_PREFIX: $LOG_FILES_PATH_PREFIX"

    mkdir -p "$(dirname "$LOG_FILES_PATH_PREFIX")"

    LOG_STDOUT_FILE="${LOG_FILES_PATH_PREFIX}_stdout.log"
    LOG_STDERR_FILE="${LOG_FILES_PATH_PREFIX}_stderr.log"
    LOG_STDALL_FILE="${LOG_FILES_PATH_PREFIX}_stdall.log"

    log_debug "LOG_STDOUT_FILE=$LOG_STDOUT_FILE - LOG_STDERR_FILE=$LOG_STDERR_FILE - LOG_STDALL_FILE=$LOG_STDALL_FILE"

    # log to files
    if [ "$LOG_SYNC" = "true" ]
    then
      "$@" 1>"$LOG_STDALL_FILE" 2>&1
    elif [ "$LOG_SYNC" = "false" ]
    then
      trap "log_cleanup" INT QUIT TERM HUP PIPE ABRT TSTP EXIT

      rm -f "$LOG_STDOUT_FILE" "$LOG_STDERR_FILE" "$LOG_STDALL_FILE"
      touch "$LOG_STDOUT_FILE" "$LOG_STDERR_FILE" "$LOG_STDALL_FILE"

      tail -f -n -100 "$LOG_STDOUT_FILE" >> "$LOG_STDALL_FILE" &
      PID_LOG_STDOUT="$!"
      tail -f -n -100 "$LOG_STDERR_FILE" >> "$LOG_STDALL_FILE" &
      PID_LOG_STDERR="$!"
      if [ "$LOG_TO_STDOUT" = "true" ]
      then
        tail -f -n -100 "$LOG_STDALL_FILE" &
        PID_LOG_STDALL="$!"
      fi

      # "$@" 1>"$LOG_STDOUT_FILE" 2>"$LOG_STDERR_FILE" || exit "$?"
      "$@" 1>"$LOG_STDOUT_FILE" 2>"$LOG_STDERR_FILE"
    else
      log_fatal "log_exec: bad switches combination! LOG_TO_STDOUT=$LOG_TO_STDOUT - LOG_TO_FILES=$LOG_TO_FILES - LOG_SYNC=$LOG_SYNC"
      exit 1
    fi
  else
    log_fatal "bad value LOG_TO_FILES=$LOG_TO_FILES"
  fi
}

#-------------------------------------------------------------------------------

export LOG_LEVEL

LOG_TO_STDOUT="true"
LOG_TO_FILES="false"
LOG_SYNC="false"

while [ "$1" != "--" ] && [ "$#" -gt "0" ]
do
  case "$1" in
    -l | --level) shift; log_level "$1";;
    -d | --dir)
      shift
      if [ -z "$1" ]
      then
        log_fatal "--dir: empty arg"
        return 1
      fi
      LOG_TO_FILES="true"
      LOG_FILES_PATH_PREFIX_DIR="$1"
    ;;
    -n | --name)
      shift
      if [ -z "$1" ]
      then
        log_fatal "--name: empty arg"
        return 1
      fi
      LOG_TO_FILES="true"
      LOG_FILES_PATH_PREFIX_NAME="$1"
    ;;
    --quiet) LOG_TO_FILES="true"; LOG_TO_STDOUT="false";;
    --files) LOG_TO_FILES="true";;
    --unique) LOG_TO_FILES="true"; LOG_FILES_PATH_PREFIX_UNIQUE="$(date +%Y-%m-%d_%H-%M-%S_%N)_$$";;
    --sync) LOG_TO_FILES="true"; LOG_SYNC="true";;
    *) log_fatal "bad arguments"; exit 1;;
  esac
  shift
done

if [ "$1" = "--" ]
then
  shift
fi

# exec
if [ "$#" -gt "0" ]
then
  log_exec "$@"
else
  log_debug "entering log subshell - sh"
  log_info "*** LOG SHELL ******************************************************************"
  log_exec bash -i
  log_info "*** LOG SHELL - exit ***********************************************************"
fi
