#!/bin/sh

array()
{
  eval "[ \"\$${1}_TYPE\" = \"array\" ]"
  if [ ! "$?" = "0" ]
  then
    if [ "$#" = "1" ]
    then
      eval "${1}_TYPE=\"array\""
      eval "${1}_SIZE=\"0\""
      return 0
    else
      echo "not an array!" 1>&2
      exit 1
    fi
  fi

  case "$2" in
    "size")
      if [ -z "$3" ]
      then
        eval "echo \"\$${1}_SIZE\""
      else
        eval "${3}=\"\$${1}_SIZE\""
      fi
    ;;
    "get")
      if [ -z "$3" ]
      then
        while eval "[ \"\$(($# - 2))\" -lt \"\$${1}_SIZE\" ]"
        do
          set -- "$@" "$(array "$1" get $(($# - 2)))"
        done
        shift 2
        echo "$@"
        return 0
      fi
      eval "[ \"${3}\" -lt \"\$${1}_SIZE\" ] || exit 1"
      if [ -z "$4" ]
      then
        eval "echo \"\$${1}_${3}\""
      else
        eval "${4}=\"\$${1}_${3}\""
      fi
    ;;
    "put")
      eval "[ \"${3}\" -lt \"\$${1}_SIZE\" ] || exit 1"
      eval "${1}_${3}=\"\${4}\""
    ;;
    "add")
      eval "set -- \"\$@\" \"\$${1}_SIZE\""
      eval "${1}_${4}=\"${3}\""
      eval "${1}_SIZE=\"\$((\$${1}_SIZE + 1))\""
    ;;
    "ins")
      eval "[ \"${3}\" -lt \"\$${1}_SIZE\" ] || exit 1"
      set -- "$@" "$1" "set"
      while [ "$(($# - 6))" -lt "$3" ]
      do
        set -- "$@" "$(array "$1" get $(($# - 6)))"
      done
      set -- "$@" "$4"
      while eval "[ \"\$(($# - 7))\" -lt \"\$${1}_SIZE\" ]"
      do
        set -- "$@" "$(array "$1" get $(($# - 7)))"
      done
      shift 4
      array "$@"
    ;;
    "rem")
      eval "[ \"${3}\" -lt \"\$${1}_SIZE\" ] || exit 1"
      set -- "$@" "$1" "set"
      while [ "$(($# - 5))" -lt "$3" ]
      do
        set -- "$@" "$(array "$1" get $(($# - 5)))"
      done
      while eval "[ \"\$(($# - 4))\" -lt \"\$${1}_SIZE\" ]"
      do
        set -- "$@" "$(array "$1" get $(($# - 4)))"
      done
      shift 3
      array "$@"
    ;;
    "set")
      array "$1" unset
      array "$1"
      set -- "$@" "${1}"
      shift 2
      while [ "$#" -gt "1" ]
      do
        eval "array \"\$$#\" add \"\$1\""
        shift
      done
    ;;
    "unset")
      eval "set -- \"\$1\" \"\$${1}_SIZE\""
      while [ "$2" -gt "0" ]
      do
        eval "${1}_SIZE=\"\$((\$${1}_SIZE - 1))\""
        eval "set -- \"\$1\" \"\$${1}_SIZE\""
        eval "unset ${1}_${2}"
      done
      eval "unset ${1}_SIZE"
      eval "unset ${1}_TYPE"
    ;;
    *) exit 1;;
  esac
}

readc()
{
  if [ -t 0 ]
  then
    saved_tty_settings=$(stty -g)
    stty -echo -icanon min 1 time 0

    read -r key << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF

    if [ "$key" = "esc" ]
    then
      stty -echo -icanon min 0 time 0
      read -r key1 << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF
      read -r key2 << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF
      read -r key3 << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF
      read -r key4 << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF
      key="$key1$key2$key3$key4"
      case "$key" in
        "[A") key="up";;
        "[B") key="down";;
        "[C") key="right";;
        "[D") key="left";;
        "[3~") key="canc";;
        *) key="esc$key";;
      esac
    elif [ "$key" = "sp" ]
    then
      key="space"
    elif [ "$key" = "ht" ]
    then
      key="tab"
    elif [ "$key" = "lf" ]
    then
      key="enter"
    elif [ "$key" = "nl" ]
    then
      key="enter"
    fi

    eval "$1='$key'"

    stty "$saved_tty_settings"
  else
    echo "no tty" 1>&2
    exit 1
  fi
}

#-------------------------------------------------------------------------------

cursor_addressing_mode_enter()
{
  tput sc
  tput smcup
  tput clear
}

cursor_addressing_mode_exit()
{
  tput clear
  tput rmcup
  tput rc
}

trap_quit()
{
  cursor_addressing_mode_exit
  echo "trap_quit"
  exit 2
}

quit()
{
  cursor_addressing_mode_exit

  if [ -z "$1" ]
  then
    exit 1
  else
    array MENU_IDS get "$1"
    exit "$1"
  fi
}

log()
{
  tput sc
  tput cup $(("$TERM_ROWS")) 0
  echo -n "$@" 1>&2
  tput rc
}

printline()
{
  echo "$@" 1>&2
}

update_screen_vars()
{
  TERM_ROWS="$(tput lines)"
  TERM_COLS="$(tput cols)"

  ROWS="$(($TERM_ROWS - 0))"
  COLS="$(($TERM_COLS - 0))"

  if [ "$ARRAY_SIZE" -lt "$ROWS" ]
  then
    ROWS="$ARRAY_SIZE"
  fi
}

load_menu()
{
  array MENU_IDS
  array MENU_TEXTS

  for k in "$@"
  do
    ID="${k%%=*}"
    TEXT="${k#*=}"
    array MENU_IDS add "$ID"
    array MENU_TEXTS add "$TEXT"
  done

  ARRAY_SIZE="$(array MENU_IDS size)"
  ARRAY_POS="0"
  CURSOR_POS="0"
}

return_selection()
{
  SELECTED_POS="$((ARRAY_POS + CURSOR_POS))"

  quit "$SELECTED_POS"
}

screen_init()
{
  # fix fo initial wrong values of size from tput
  tput clear
  i=0
  while [ "$i" -lt "999" ]
  do
    echo -n "                                                 " 1>&2
    i="$(($i + 1))"
  done
  tput clear
}

update_screen_list()
{
  update_screen_vars
  tput clear

  INDEX_START=$1
  INDEX_END=$((ROWS+$1))
  if [ "$INDEX_END" -gt "$ARRAY_SIZE" ]
  then
    INDEX_END="$ARRAY_SIZE"
  fi

  i="$INDEX_START"
  while [ "$i" -lt "$INDEX_END" ]
  do
    line="$(array MENU_TEXTS get "$i")"
    # size="${#line}"
    # if [ "$size" -gt "$COLS" ]
    # then
    #   line="${line:0:$COLS} [...]"
    # fi
    printline "$line"
    i="$(($i + 1))"
  done

  tput cup "$CURSOR_POS" 0
}

scroll_cursor()
{
  CURSOR_POS="$(($CURSOR_POS + $1))"

  UPDATE_SCREEN="false"

  if [ "$CURSOR_POS" -lt "0" ]
  then
    ARRAY_POS="$(($ARRAY_POS + $1))"
    CURSOR_POS="0"
    UPDATE_SCREEN="true"
  elif [ "$CURSOR_POS" -gt "$(($ROWS - 1))" ]
  then
    ARRAY_POS="$(($ARRAY_POS + $1))"
    CURSOR_POS="$(($ROWS - 1))"
    UPDATE_SCREEN="true"
  fi

  if [ "$ARRAY_POS" -lt "0" ]
  then
    ARRAY_POS=0
    # UPDATE_SCREEN=false
  elif [ "$ARRAY_POS" -gt "$(($ARRAY_SIZE - $ROWS))" ]
  then
    ARRAY_POS="$(($ARRAY_SIZE - $ROWS))"
    # UPDATE_SCREEN=false
  fi

  if [ "$UPDATE_SCREEN" = true ]
  then
    update_screen_list $((ARRAY_POS))
  fi

  tput cup $CURSOR_POS 0
}

key_loop()
{
  while true
  do
    readc key

    case "$key" in
      "q") quit -1;;
      "up") scroll_cursor -1;;
      "down") scroll_cursor +1;;
      "enter") return_selection;;
      # *) exit 1;;
    esac
  done
}

main()
{
  if [ -z "$*" ] || [ "$#" -lt "5" ] || [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ] || [ -z "$5" ]
  then
    exit 1
  fi

  ROW_1="$1"
  ROW_2="$2"
  COL_1="$3"
  COL_2="$4"
  shift 4

  load_menu "$@"

  # trap "trap_quit" INT QUIT TERM HUP PIPE ABRT CHLD TSTP EXIT
  # trap "trap_quit" INT QUIT TERM HUP PIPE ABRT
  trap "trap_quit" INT QUIT TERM HUP PIPE ABRT TSTP EXIT
  cursor_addressing_mode_enter

  screen_init
  update_screen_list 0
  key_loop
}

main "$@"
