#!/bin/sh

# http://invisible-island.net/ncurses/man/terminfo.5.html

#-------------------------------------------------------------------------------

tty_init()
{
  if [ ! -t 0 ]
  then
    # echo "no tty" 1>&2
    exit 1
  fi

  saved_tty_settings=$(stty -g)
  stty -echo -icanon min 1 time 0
}

tty_reset()
{
  stty "$saved_tty_settings"
}

#-------------------------------------------------------------------------------

readc()
{
  read -r key << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF

  if [ "$key" = "esc" ]
  then
    stty -echo -icanon min 0 time 0
    read -r key1 << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF
    read -r key2 << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF
    read -r key3 << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF
    read -r key4 << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF

    key="$key1$key2$key3$key4"
    case "$key" in
      # xterm
      "[A") key="up";;
      "[B") key="down";;
      "[C") key="right";;
      "[D") key="left";;
      "[E") key="keypad_5_2";;
      "[F") key="end";;
      # "[F") key="end_2";;
      "[G") key="keypad_5";;
      "[H") key="home";;
      # "[H") key="home_2";;
      "[1P") key="f1_2";;
      "[1Q") key="f2_2";;
      "[1R") key="f3_2";;
      "[1S") key="f4_2";;
      # vt
      "[1~") key="home";;
      "[2~") key="ins";;
      "[3~") key="canc";;
      "[4~") key="end";;
      "[5~") key="pageup";;
      "[6~") key="pagedown";;
      "[7~") key="home";;
      # "[7~") key="home_3";;
      "[8~") key="end";;
      # "[8~") key="end_3";;
      # "[9~") key="unknown_[9~";;
      "[10~") key="f0";;
      "[11~") key="f1";;
      "[12~") key="f2";;
      "[13~") key="f3";;
      "[14~") key="f4";;
      "[15~") key="f5";;
      # "[16~") key="unknown_[16~";;
      "[17~") key="f6";;
      "[18~") key="f7";;
      "[19~") key="f8";;
      "[20~") key="f9";;
      "[21~") key="f10";;
      # "[22~") key="unknown_[22~";;
      "[23~") key="f11";;
      "[24~") key="f12";;
      "[25~") key="f13";;
      "[26~") key="f14";;
      # "[27~") key="unknown_[27~";;
      "[28~") key="f15";;
      "[29~") key="f16";;
      # "[30~") key="unknown_[30~";;
      "[31~") key="f17";;
      "[32~") key="f18";;
      "[33~") key="f19";;
      "[34~") key="f20";;
      # "[35~") key="unknown_[35~";;
      *) key="esc$key";;
    esac
  elif [ "$key" = "sp" ]
  then
    key="space"
  elif [ "$key" = "ht" ]
  then
    key="tab"
  elif [ "$key" = "lf" ]
  then
    key="enter"
  elif [ "$key" = "nl" ]
  then
    key="enter"
  fi

  echo "$key"
}

trap "tty_reset; exit 2" INT QUIT TERM HUP PIPE ABRT TSTP
tty_init

readc

tty_reset
