#!/bin/sh

# echoes prompts on stderr, read password securely from terminal, verify it a secondo time and
# NB echoes password on stdout!!! (only use it to store on env var or pass to pipe)
# $1=first prompt, $2=prompt to verify, $3,...=verify error message

#------------------------------------------------------------------------------

PASSWORD="$(readpass "$1")"
shift

PASSWORD_VERIFY="$(readpass "$1")"
shift

if [ ! "$PASSWORD" = "$PASSWORD_VERIFY" ]
then
  echo "$@" 1>&2
  exit 1
fi

echo "$PASSWORD"
