#!/bin/sh

# echoes prompt on stderr and read password securely from terminal and
# NB echoes password on stdout!!! (only use it to store on env var or pass to pipe)
# $@=prompt

#------------------------------------------------------------------------------

tty_init()
{
  saved_tty_settings=$(stty -g)
  stty -echo
}

#------------------------------------------------------------------------------

tty_reset()
{
  stty "$saved_tty_settings"
}

#-------------------------------------------------------------------------------

if [ ! -t 0 ]
then
  exit 1
fi

trap "tty_reset; exit 2" INT QUIT TERM HUP PIPE ABRT TSTP
tty_init

echo "$@" 1>&2
read -r PASSWORD

echo "$PASSWORD"

tty_reset
