#!/bin/sh

# echoes prompt on stderr and read password securely from terminal and
# NB echoes password on stdout!!! (only use it to store on env var or pass to pipe)
# $@=prompt

#------------------------------------------------------------------------------

tty_init()
{
  saved_tty_settings=$(stty -g)
  stty -echo
}

#------------------------------------------------------------------------------

tty_reset()
{
  stty "$saved_tty_settings"
}

#-------------------------------------------------------------------------------

trap "tty_reset; exit 2" INT QUIT TERM HUP PIPE ABRT TSTP
tty_init

if [ -t 0 ]
then
  echo "$@" 1>&2
  read -r PASSWORD
else
  read -r PASSWORD
fi

echo "$PASSWORD"

tty_reset
