#!/bin/sh

if [ -d "$1" ]
then
  cd -P -- "$1" && pwd -P
elif [ -f "$1" ] && [ -L "$1" ]
then
  TARGET="$(ls -ld -- "$1")"
  TARGET="${TARGET#*" $1 -> "}"
  if [ "$TARGET" = "${TARGET#/}" ]
  then
    # relative link
    TARGET="$(dirname -- "$1")/$TARGET"
  fi
  echo "$(cd -P -- "$(dirname -- "$TARGET")" && pwd -P)/$(basename -- "$TARGET")"
elif [ -f "$1" ]
then
  echo "$(cd -P -- "$(dirname -- "$1")" && pwd -P)/$(basename -- "$1")"
else
  exit 1
fi
