#!/bin/sh

VERSION="1.5.1"
DOWNLOAD_URL="https://github.com/acoustid/chromaprint/releases/download/v${VERSION}/chromaprint-fpcalc-${VERSION}-linux-x86_64.tar.gz"
FILE_TYPE="tar.gz"
SYMLINKS="fpcalc=fpcalc"

postinstall()
(
  cd ./latest
  sudo chmod +x ./fpcalc
)
