#!/bin/sh

sudo -s << SUDO

groupadd keycloak
useradd -r -g keycloak -d "/m/src/git/m/cmd/pkg/zzz/pkg/keycloak-26.4.0/keycloak-26.4.0" -s /sbin/nologin keycloak
chown -R keycloak:keycloak "/m/src/git/m/cmd/pkg/zzz/pkg/keycloak-26.4.0/keycloak-26.4.0"
#chmod -R o+rwx "/m/src/git/m/cmd/pkg/zzz/pkg/keycloak-26.4.0/keycloak-26.4.0"

mount --bind "/m/src/git/m/cmd/pkg/zzz/pkg/keycloak-26.4.0/keycloak-26.4.0" "/opt/keycloak"
cp "/m/src/git/m/cmd/pkg/zzz/pkg/keycloak-26.4.0/keycloak-26.4.0/keycloak.service" "/etc/systemd/system/keycloak.service"
chown root:root "/etc/systemd/system/keycloak.service"
chmod 644 "/etc/systemd/system/keycloak.service"
systemctl daemon-reload
systemctl enable keycloak

SUDO

