#!/bin/sh

if [ -L "$0" ]
then
  THIS_PATH="$(ls -ld -- "$0")"
  THIS_PATH="${THIS_PATH#*" $0 -> "}"
else
  THIS_PATH="$0"
fi

THIS_FILE="${THIS_PATH##*/}"

THIS_DIR="$(cd -P -- "${THIS_PATH%/*}" && pwd -P)"

#COMMIT_MESSAGE_FILE="${THIS_DIR}/${THIS_FILE}.msg"
COMMIT_MESSAGE_FILE="${THIS_DIR}/commit.msg"
COMMIT_MESSAGE_LAST="$(cat "$COMMIT_MESSAGE_FILE")"

echo "Previous commit message: $COMMIT_MESSAGE_LAST"
read -p "Enter commit message (default to previous): " COMMIT_MESSAGE

if [ -z "$COMMIT_MESSAGE" ]
then
  COMMIT_MESSAGE="$COMMIT_MESSAGE_LAST"
fi

echo "$COMMIT_MESSAGE" > "$COMMIT_MESSAGE_FILE"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "BRANCH: $BRANCH"
[ -z "$BRANCH" ] && echo "empty branch!" && exit 1

for k in *
do
  [ -d "$k/.git" ] && mv "$k/.git" "$k/.git_"
done

git add --all && \
git commit -m "$COMMIT_MESSAGE" && \
git push origin "$BRANCH"
EXIT_CODE="$?"

echo "--------------------------------------------------------------------------------"
echo "GIT STATUS:"
echo "--------------------------------------------------------------------------------"

git status

for k in *
do
  [ -d "$k/.git_" ] && mv "$k/.git_" "$k/.git"
done

exit "$EXIT_CODE"
