#!/bin/sh

if [ -L "$0" ]
then
  THIS_PATH="$(ls -ld -- "$0")"
  THIS_PATH="${THIS_PATH#*" $0 -> "}"
else
  THIS_PATH="$0"
fi

THIS_FILE="${THIS_PATH##*/}"

THIS_DIR="$(cd -P -- "${THIS_PATH%/*}" && pwd -P)"

git fetch origin && \
git status && \
git show -s --format=%s
EXIT_CODE="$?"

exit "$EXIT_CODE"
