#!/bin/sh

#-------------------------------------------------------------------------------

. env.lib.sh
. enc.lib.sh
. menu.lib.sh
. waituser.lib.sh

#-------------------------------------------------------------------------------

menuset nomulti
menuset keys "e:d:m"

MENU_HEADER="FILE ENCODING / DECODING: e=encode, d=decode, m=modify/edit"
MENU_FOOTER=""

env_read "key file selection" tui head "$MENU_HEADER" "$MENU_FOOTER" tui-menu-file .

if [ "$key" = "esc" ] || [ "$key" = "q" ]
then
  false
elif [ ! -f "$file" ]
then
  echo "not a file: $file"
else
  if [ "$key" = "e" ]
  then
    encode < "$file" > "${file}.enc"
  elif [ "$key" = "d" ]
  then
    decode < "$file" > "${file}.dec"
  elif [ "$key" = "m" ]
  then
    encoded_file_edit "$file"
  fi
fi

waituser
