#!/bin/sh

#-------------------------------------------------------------------------------

. env.lib.sh
. term.lib.sh
. menu.lib.sh

#-------------------------------------------------------------------------------

screen_vars_update()
{
  # init header/footer
  if [ -n "$term_mod_HEAD_HEADER" ]
  then
    term_mod_HEAD_HEADER_SIZE_ROW="$(term_string_count_lines "$term_mod_HEAD_HEADER")"
    term_mod_HEAD_HEADER_ROW_0="$term_ROW0"
    term_ROW0="$(($term_ROW0 + $term_mod_HEAD_HEADER_SIZE_ROW))"
    term_ROWS="$(($term_ROWS - $term_mod_HEAD_HEADER_SIZE_ROW))"
  fi

  if [ -n "$term_mod_HEAD_FOOTER" ]
  then
    term_mod_HEAD_FOOTER_SIZE_ROW="$(term_string_count_lines "$term_mod_HEAD_FOOTER")"
    term_ROWS="$(($term_ROWS - $term_mod_HEAD_FOOTER_SIZE_ROW))"
    term_mod_HEAD_FOOTER_ROW_0="$(($term_ROW0 + $term_ROWS))"
  fi
}

screen_background_render()
{
  if [ -n "$term_mod_HEAD_HEADER" ]
  then
    term_render_text_at "$term_mod_HEAD_HEADER" "$term_mod_HEAD_HEADER_ROW_0" "$term_COL0"
  fi

  if [ -n "$term_mod_HEAD_FOOTER" ]
  then
    term_render_text_at "$term_mod_HEAD_FOOTER" "$term_mod_HEAD_FOOTER_ROW_0" "$term_COL0"
  fi
}

#-------------------------------------------------------------------------------

main()
{
  term_mod_HEAD_HEADER="$1"
  shift
  term_mod_HEAD_FOOTER="$1"
  shift

  # ENV_RETURN="export"
  # ENV_LIST="$(env_list "HEADER\|FOOTER")"

  term_region_init
  screen_vars_update
  screen_background_render
  # env_return export $(env_list "term_\|term_mod_HEAD_")
  term_ROW0="$term_ROW0" term_COL0="$term_COL0" term_ROWS="$term_ROWS" term_COLS="$term_COLS" "$@"

  ENV_LIST="$(env_list "term_mod_HEAD_")"
  env_return && exit 0
}

#-------------------------------------------------------------------------------

main "$@"
