#!/bin/sh

#-------------------------------------------------------------------------------

. env.lib.sh
. term.lib.sh

#-------------------------------------------------------------------------------

env_init()
{
  tui_HEAD_HEADER="$1"
  shift
  tui_HEAD_FOOTER="$1"
  shift

  tui_HEAD_ARGS="$(saveargs "$@")"

  tui_HEAD_HEADER_ROW_0="$term_ROW0"
  tui_HEAD_FOOTER_ROW_0="$(($term_ROW0 + $term_ROWS))"

  if [ -n "$tui_HEAD_HEADER" ]
  then
    tui_HEAD_HEADER_SIZE_ROW="$(term_string_count_lines "$tui_HEAD_HEADER")"
    tui_HEAD_HEADER_ROW_0="$term_ROW0"
    term_ROW0="$(($term_ROW0 + $tui_HEAD_HEADER_SIZE_ROW))"
    term_ROWS="$(($term_ROWS - $tui_HEAD_HEADER_SIZE_ROW))"
  fi

  if [ -n "$tui_HEAD_FOOTER" ]
  then
    tui_HEAD_FOOTER_SIZE_ROW="$(term_string_count_lines "$tui_HEAD_FOOTER")"
    term_ROWS="$(($term_ROWS - $tui_HEAD_FOOTER_SIZE_ROW))"
    tui_HEAD_FOOTER_ROW_0="$(($term_ROW0 + $term_ROWS))"
  fi
}

main()
{
  if [ -n "$tui_HEAD_HEADER" ]
  then
    term_render_text_at "$tui_HEAD_HEADER" "$tui_HEAD_HEADER_ROW_0" "$term_COL0"
  fi

  if [ -n "$tui_HEAD_FOOTER" ]
  then
    term_render_text_at "$tui_HEAD_FOOTER" "$tui_HEAD_FOOTER_ROW_0" "$term_COL0"
  fi

  eval "set -- $tui_HEAD_ARGS"
  tui_HEAD_RESULT="$(term_ROW0="$term_ROW0" term_COL0="$term_COL0" term_ROWS="$term_ROWS" term_COLS="$term_COLS" "$@")"
}

env_list_get()
{
  env_list "tui_HEAD_"
}

env_result()
{
  term_output printf "$tui_HEAD_RESULT"
}

#-------------------------------------------------------------------------------

env_main "$@"
