#!/bin/sh

# MENU_ID="false" # disables id detection from menu entries "menu_entry_id=menu_entry_text"
# MENU_MULTISELECTION="true" # enables multi selection
# MENU_CUSTOM_KEYS="key1:key2:key3" # returns selection also with these keys in the form "key:selection"

#-------------------------------------------------------------------------------

. arg.lib.sh
. array.lib.sh

#-------------------------------------------------------------------------------

select_item_toggle()
{
  if [ ! "$tui_MENU_MULTISELECTION" = "true" ]
  then
    return 0
  fi

  tui_MENU_SELECTED_POS="$tui_MENU_ARRAY_POS"
  tui_MENU_SEL_ITEM_CURR_STRING="$(array tui_MENU_SEL get "$tui_MENU_ARRAY_POS")"
  if [ "$tui_MENU_SEL_ITEM_CURR_STRING" = "$tui_MENU_SEL_ITEM_TRUE_STRING" ]
  then
    array tui_MENU_SEL put "$tui_MENU_ARRAY_POS" "$tui_MENU_SEL_ITEM_FALSE_STRING"
  elif [ "$tui_MENU_SEL_ITEM_CURR_STRING" = "$tui_MENU_SEL_ITEM_FALSE_STRING" ]
  then
    array tui_MENU_SEL put "$tui_MENU_ARRAY_POS" "$tui_MENU_SEL_ITEM_TRUE_STRING"
  else
    false
  fi

  print_menu_entry "$tui_MENU_ARRAY_POS" "$tui_MENU_CURSOR_POS"
}

print_menu_entry()
{
  tui_MENU_ENTRY_INDEX="$1"
  tui_MENU_ENTRY_ROW="$2"

  # clear whole line
  term_render tput cup "$(($term_ROW0 + $tui_MENU_ENTRY_ROW))" "$term_COL0"
  term_render printf "%${term_COLS}s"
  term_render tput cup "$(($term_ROW0 + $tui_MENU_ENTRY_ROW))" "$term_COL0"

  # limit too long lines (use line without ascii control codes)
  if [ ! "$tui_MENU_MULTISELECTION" = "true" ]
  then
    line="$tui_MENU_ENTRY_INDEX $(array tui_MENU_TEXTS get "$tui_MENU_ENTRY_INDEX")"
  else
    line="$tui_MENU_ENTRY_INDEX [$(array tui_MENU_SEL get "$tui_MENU_ENTRY_INDEX")] $(array tui_MENU_TEXTS get "$tui_MENU_ENTRY_INDEX")"
  fi
  size="$(printf "$line" | wc -m)"
  line="$(array tui_MENU_TEXTS get "$tui_MENU_ENTRY_INDEX")"
  if [ "$size" -gt "$term_COLS" ]
  then
    sizeexceed="$(($size - $term_COLS))"
    size="$(printf "$line" | wc -m)"
    line="$(printf "$line" | cut -c "1-$(($size - $sizeexceed - 6))")$(tput setaf 1) [...]$(tput sgr0)"
  fi

  # print line
  if [ ! "$tui_MENU_MULTISELECTION" = "true" ]
  then
    line="$(tput setaf 2)$tui_MENU_ENTRY_INDEX$(tput sgr0) $line"
  else
    line="$(tput setaf 2)$tui_MENU_ENTRY_INDEX$(tput sgr0) $(tput setaf 3)[$(array tui_MENU_SEL get "$tui_MENU_ENTRY_INDEX")]$(tput sgr0) $line"
  fi
  term_render printf "$line"

  term_render tput cup "$(($term_ROW0 + $tui_MENU_ENTRY_ROW))" "$term_COL0"
}

screen_render()
{
  tui_MENU_ARRAY_POS_START="$1"

  i="0"
  n="$term_ROWS"
  while [ "$i" -lt "$n" ]
  do
    print_menu_entry "$(($tui_MENU_ARRAY_POS_START + $i))" "$i"
    i="$(($i + 1))"
  done
}

menu_entry_highlight()
{
  term_render tput cup "$(($term_ROW0 + $1))" "$term_COL0"
}

scroll_cursor()
{
  if [ "$1" -lt "0" ]
  then
    if [ "$tui_MENU_CURSOR_POS" = "0" ] && [ "$tui_MENU_ARRAY_POS_START" = "0" ]
    then
      true
    elif [ "$tui_MENU_CURSOR_POS" = "0" ] && [ "$tui_MENU_ARRAY_POS_START" -gt "0" ]
    then
      tui_MENU_ARRAY_POS_START="$(($tui_MENU_ARRAY_POS_START + $1))"
      tui_MENU_ARRAY_POS="$(($tui_MENU_ARRAY_POS + $1))"
      screen_render "$tui_MENU_ARRAY_POS_START"
      menu_entry_highlight "$tui_MENU_CURSOR_POS"
    else
      tui_MENU_CURSOR_POS="$(($tui_MENU_CURSOR_POS + $1))"
      tui_MENU_ARRAY_POS="$(($tui_MENU_ARRAY_POS + $1))"
      menu_entry_highlight "$tui_MENU_CURSOR_POS"
    fi
  elif [ "$1" -gt "0" ]
  then
    if [ "$tui_MENU_CURSOR_POS" = "$(($term_ROWS - 1))" ] && [ "$tui_MENU_ARRAY_POS_START" = "$(($tui_MENU_ARRAY_SIZE - $term_ROWS))" ]
    then
      true
    elif [ "$tui_MENU_CURSOR_POS" = "$(($term_ROWS - 1))" ] && [ "$tui_MENU_ARRAY_POS_START" -lt "$(($tui_MENU_ARRAY_SIZE - $term_ROWS))" ]
    then
      tui_MENU_ARRAY_POS_START="$(($tui_MENU_ARRAY_POS_START + $1))"
      tui_MENU_ARRAY_POS="$(($tui_MENU_ARRAY_POS + $1))"
      screen_render "$tui_MENU_ARRAY_POS_START"
      menu_entry_highlight "$tui_MENU_CURSOR_POS"
    else
      tui_MENU_CURSOR_POS="$(($tui_MENU_CURSOR_POS + $1))"
      tui_MENU_ARRAY_POS="$(($tui_MENU_ARRAY_POS + $1))"
      menu_entry_highlight "$tui_MENU_CURSOR_POS"
    fi
  fi
}

check_cursor()
{
  if [ "$tui_MENU_CURSOR_POS" -lt "0" ]
  then
    tui_MENU_CURSOR_POS="0"
  elif [ "$tui_MENU_CURSOR_POS" -gt "$(($term_ROWS - 1))" ]
  then
    tui_MENU_CURSOR_POS="$(($term_ROWS - 1))"
  fi

  if [ "$tui_MENU_ARRAY_POS" -lt "0" ]
  then
    tui_MENU_ARRAY_POS=0
  elif [ "$tui_MENU_ARRAY_POS" -gt "$(($tui_MENU_ARRAY_SIZE - 1))" ]
  then
    tui_MENU_ARRAY_POS="$(($tui_MENU_ARRAY_SIZE - 1))"
  fi

  if [ "$tui_MENU_ARRAY_POS_START" -lt "0" ]
  then
    tui_MENU_ARRAY_POS_START=0
  elif [ "$tui_MENU_ARRAY_POS_START" -gt "$(($tui_MENU_ARRAY_SIZE - $term_ROWS))" ]
  then
    tui_MENU_ARRAY_POS_START="$(($tui_MENU_ARRAY_SIZE - $term_ROWS))"
  fi
}

scroll_page()
{
  if [ "$1" -lt "0" ]
  then
    if [ "$tui_MENU_CURSOR_POS" = "0" ]
    then
      tui_MENU_ARRAY_POS="$(($tui_MENU_ARRAY_POS - $term_ROWS))"
      tui_MENU_ARRAY_POS_START="$(($tui_MENU_ARRAY_POS_START - $term_ROWS))"
      check_cursor
      screen_render "$tui_MENU_ARRAY_POS_START"
      menu_entry_highlight "$tui_MENU_CURSOR_POS"
    elif [ "$tui_MENU_CURSOR_POS" -gt "0" ]
    then
      tui_MENU_ARRAY_POS="$(($tui_MENU_ARRAY_POS - $tui_MENU_CURSOR_POS))"
      tui_MENU_CURSOR_POS="0"
      menu_entry_highlight "$tui_MENU_CURSOR_POS"
    fi
  elif [ "$1" -gt "0" ]
  then
    if [ "$tui_MENU_CURSOR_POS" = "$(($term_ROWS - 1))" ]
    then
      tui_MENU_ARRAY_POS="$(($tui_MENU_ARRAY_POS + $term_ROWS))"
      tui_MENU_ARRAY_POS_START="$(($tui_MENU_ARRAY_POS_START + $term_ROWS))"
      check_cursor
      screen_render "$tui_MENU_ARRAY_POS_START"
      menu_entry_highlight "$tui_MENU_CURSOR_POS"
    elif [ "$tui_MENU_CURSOR_POS" -lt "$(($term_ROWS - 1))" ]
    then
      tui_MENU_ARRAY_POS="$(($tui_MENU_ARRAY_POS - $tui_MENU_CURSOR_POS))"
      tui_MENU_CURSOR_POS="$(($term_ROWS - 1))"
      menu_entry_highlight "$tui_MENU_CURSOR_POS"
    fi
  fi
}

move_cursor_to_start()
{
  tui_MENU_CURSOR_POS="0"
  tui_MENU_ARRAY_POS="0"
  tui_MENU_ARRAY_POS_START="0"

  screen_render "0"

  menu_entry_highlight "$tui_MENU_CURSOR_POS"
}

move_cursor_to_end()
{
  tui_MENU_CURSOR_POS="$(($term_ROWS - 1))"
  tui_MENU_ARRAY_POS="$(($tui_MENU_ARRAY_SIZE - 1))"

  if [ "$tui_MENU_ARRAY_SIZE" -lt "$term_ROWS" ]
  then
    tui_MENU_ARRAY_POS_START="0"
  else
    tui_MENU_ARRAY_POS_START="$(($tui_MENU_ARRAY_SIZE - $term_ROWS))"
  fi

  screen_render "$tui_MENU_ARRAY_POS_START"
  menu_entry_highlight "$tui_MENU_CURSOR_POS"
}

return_selection()
{
  tui_MENU_RETURN_KEY="$key"
  tui_MENU_RETURN_ITEM="$(array tui_MENU_IDS get "$tui_MENU_ARRAY_POS")"
  array tui_MENU_SELECTED_ITEMS
  i="0"
  n="$(array tui_MENU_SEL size)"
  while [ "$i" -lt "$n" ]
  do
    if [ "$(array tui_MENU_SEL get "$i")" = "$tui_MENU_SEL_ITEM_TRUE_STRING" ]
    then
      array tui_MENU_SELECTED_ITEMS add "$(array tui_MENU_IDS get "$i")"
    fi
    i="$(($i + 1))"
  done
  tui_MENU_RETURN_SELECTION="$(array tui_MENU_SELECTED_ITEMS get)"

  exit 0
}

check_key()
{
  if [ -z "$1" ]
  then
    return 0
  fi

  if [ -z "$tui_MENU_CUSTOM_KEYS" ]
  then
    return 0
  fi

  if [ "${tui_MENU_CUSTOM_KEYS#*${1}*}" = "$tui_MENU_CUSTOM_KEYS" ]
  then
    return 0
  fi

  return_selection
}

#-------------------------------------------------------------------------------

env_init()
{
  # init limits
  if [ -z "$tui_MENU_ENTRY_SIZE_MIN" ]
  then
    tui_MENU_ENTRY_SIZE_MIN="3"
  fi

  # init menu id detection
  if [ -z "$tui_MENU_ID" ]
  then
    tui_MENU_ID="true"
  fi

  # init multi selection
  if [ -z "$tui_MENU_MULTISELECTION" ]
  then
    tui_MENU_MULTISELECTION="false"
  fi

  if [ -z "$tui_MENU_SEL_ITEM_TRUE_STRING" ]
  then
    tui_MENU_SEL_ITEM_TRUE_STRING="+"
  fi

  if [ -z "$tui_MENU_SEL_ITEM_FALSE_STRING" ]
  then
    tui_MENU_SEL_ITEM_FALSE_STRING="-"
  fi

  # return key pressed
  if [ -z "$tui_MENU_KEY_SEPARATOR" ]
  then
    tui_MENU_KEY_SEPARATOR=":"
  fi

  args_init "$@"

  tui_MENU_ARRAY_SIZE="$(array tui_MENU_IDS size)"
  tui_MENU_ARRAY_POS="0"
  tui_MENU_CURSOR_POS="0"

  # adjust render region for small menus

  # if [ "$#" -lt "$term_ROWS" ]
  # then
  #   term_ROWS="$#"
  # fi

  if [ "$tui_MENU_ARRAY_SIZE" -lt "$term_ROWS" ]
  then
    term_ROWS="$tui_MENU_ARRAY_SIZE"
  fi
}

args_init()
{
  array tui_MENU_IDS
  array tui_MENU_TEXTS
  array tui_MENU_SEL

  for k in "$@"
  do
    if [ ! "$tui_MENU_ID" = "false" ]
    then
      ID="${k%%=*}"
      TEXT="${k#*=}"
    else
      ID="$k"
      TEXT="$k"
    fi

    array tui_MENU_IDS add "$ID"
    array tui_MENU_TEXTS add "$TEXT"
    array tui_MENU_SEL add "$tui_MENU_SEL_ITEM_FALSE_STRING"
  done
}

render()
{
  term_region_clear
  screen_render "${tui_MENU_ARRAY_POS_START:-"0"}"
  menu_entry_highlight "${tui_MENU_CURSOR_POS:-"0"}"
}

key_default()
{
  check_key "$key"
}

key_q()
{
  return 1
}

key_esc()
{
  return 1
}

key_up()
{
  scroll_cursor "-1"
}

key_down()
{
  scroll_cursor "+1"
}

key_pageup()
{
  scroll_page "-1"
}

key_pagedown()
{
  scroll_page "+1"
}

key_home()
{
  move_cursor_to_start
}

key_end()
{
  move_cursor_to_end
}

key_space()
{
  select_item_toggle
}

key_enter()
{
  return_selection
}

env_list_get()
{
  env_list "term_ROW\|term_COL\|tui_MENU_\|key"
}

env_result()
{
  if [ -n "$tui_MENU_CUSTOM_KEYS" ]
  then
    term_output quote "${key}"
    term_output printf " "
    term_output quote "$(array tui_MENU_IDS get "$tui_MENU_ARRAY_POS")"
    term_output printf " "
  fi

  if [ ! "$tui_MENU_MULTISELECTION" = "true" ]
  then
    term_output array tui_MENU_IDS get "$tui_MENU_ARRAY_POS"
  else
    array tui_MENU_SELECTED_ITEMS
    i="0"
    n="$(array tui_MENU_SEL size)"
    while [ "$i" -lt "$n" ]
    do
      if [ "$(array tui_MENU_SEL get "$i")" = "$tui_MENU_SEL_ITEM_TRUE_STRING" ]
      then
        array tui_MENU_SELECTED_ITEMS add "$(array tui_MENU_IDS get "$i")"
      fi
      i="$(($i + 1))"
    done
    # term_output array tui_MENU_SELECTED_ITEMS get
    term_output quote "$(array tui_MENU_SELECTED_ITEMS get)"
  fi
}

#-------------------------------------------------------------------------------

. tui-main.src.sh
