#!/bin/sh

#-------------------------------------------------------------------------------

. env.lib.sh
. term.lib.sh

#-------------------------------------------------------------------------------

env_init()
{
  true
  # set proper initial variables values
  # process args "$@"
}

render()
{
  true
  # only render inside region
}

key_default()
{
  true
  # handle keys not explicitly mapped
}

key_q()
{
  return 1
  # exits from key loop
}

key_esc()
{
  return 1
  # exits from key loop
}

key_mykey()
{
  true
  # handle explicitly mapped "mykey"
}

key_loop()
{
  # if defined, handles all key presses
  while true
  do
    key="$(readc)"

    case "$key" in
      "q") return 0;;
      "esc") return 0;;
      "space") true;;
      "enter") true;;
      *) return 1;;
    esac
  done
}

env_list_get()
{
  true
  # echo "myvar1 myvar2 myvar3"
  # env_list "term_TEMPLATE_\|custom_var_pattern"
}

env_result()
{
  true
  # return result
}

#-------------------------------------------------------------------------------

. tui-main.src.sh
