#!/bin/sh

INSTALL_DIR="$(cd "${0%/*}"; pwd)"
M_SRC_DIR="${INSTALL_DIR%/m/os/install*}/m/os/m"

if [ -z "$1" ] || [ "$1" = "dev" ]
then
  ROOT_DIR="$(pwd)"
else
  ROOT_DIR="$1"
  if [ ! -d "$ROOT_DIR" ]
  then
    exit 1
  fi
fi

SRC_DIR="$ROOT_DIR/src"
PKG_DIR="$ROOT_DIR/pkg"

mkdir -p "$SRC_DIR"
mkdir -p "$PKG_DIR"

WRK_DIR="$ROOT_DIR/wrk"
WORK_DIR="$ROOT_DIR/wrk"
DATA_DIR="$ROOT_DIR/wrk/data"

mkdir -p "$DATA_DIR"

rm -rf "$PKG_DIR/m"
rm -f "$ROOT_DIR/m"

if [ "$1" = "dev" ] || [ "$2" = "dev" ]
then
  ln -s "$M_SRC_DIR" "$PKG_DIR/m"
  ln -s "$INSTALL_DIR/m" "$ROOT_DIR/m"
  ln -s "$M_SRC_DIR/def/data" "$DATA_DIR/m"
else
  cp -R "$M_SRC_DIR" "$PKG_DIR"
  cp -R "$INSTALL_DIR/m" "$ROOT_DIR"
  rm -Rf "$PKG_DIR/m/.mk"
  cp -RT "$M_SRC_DIR/def/data" "$DATA_DIR/m"
fi
