#!/bin/sh

#-------------------------------------------------------------------------------

. realpaths.lib.sh
. waituser.lib.sh
# . enc.lib.sh
. array.lib.sh
. menu.lib.sh

#-------------------------------------------------------------------------------

menu_dir___()
{
  if [ ! -d "$1" ]
  then
    return 1
  fi

  eval menuctl multi menukeys key index selection "$keys" $(
    cd "$1"
    set -- "$(cd -L -- "$1" && pwd -L)"

    array DIR_ARRAY

    if [ ! "$(pwd)" = "/" ]
    then
      array DIR_ARRAY add "${1}/..=.."
    else
      set -- ""
    fi

    for k in ..?* .[!.]* *
    do
      if [ -e "$k" ]
      then
        array DIR_ARRAY add "${1}/$k=$k"
      fi
    done

    array DIR_ARRAY get

    # FILE="$(eval menu $(array DIR_ARRAY get))"
    #
    # if [ -n "$FILE" ]
    # then
    #   echo "$(cd -L -- "$1" && pwd -L)/$FILE"
    # fi
  )

  echo "key=$key"; echo "index=$index"; echo "selection=$selection"
}

menu_dir()
{
  if [ ! -d "$1" ]
  then
    return 1
  fi

  cd "$1"
  set -- "$(cd -L -- "$1" && pwd -L)"

  array DIR_ARRAY

  if [ ! "$(pwd)" = "/" ]
  then
    array DIR_ARRAY add "${1}/..=.."
  else
    set -- ""
  fi

  for k in ..?* .[!.]* *
  do
    if [ -e "$k" ]
    then
      array DIR_ARRAY add "${1}/$k=$k"
    fi
  done

  eval menuctl multi menukeys key index selection "$keys" $(array DIR_ARRAY get)

  echo "key=$key"
  echo "index=$index entry=$(array DIR_ARRAY get "$index")"
  echo "selection=$selection"
}

#-------------------------------------------------------------------------------

realpaths

keys="canc:c:d:m:r"

# FILE="$(menu_dir "$THIS_DIR")"
# eval menuctl keys key selection "$keys" $(dir "/")
menu_dir "/"
# waituser

while [ "$key" = "enter" ] && [ -d "$selection" ]
# while [ -n "$FILE" ] && [ -d "$FILE" ]
#while [ -n "$FILE" ]
do
  # FILE_SEL="$FILE"
  # FILE="$(menu_dir "$FILE")"
  # menuctl keys key selection "$keys" id_0=Text_0 id_1=Text_1 id_2=Text_2
  menu_dir "$selection"
done

# if [ -n "$FILE" ]
# then
#   echo "$FILE"
# else
#   echo "$FILE_SEL"
# fi
