#!/bin/sh

#-------------------------------------------------------------------------------

. realpaths.lib.sh
. waituser.lib.sh
# . enc.lib.sh
. array.lib.sh
. menu.lib.sh

#-------------------------------------------------------------------------------

menu_dir___()
{
  if [ ! -d "$1" ]
  then
    return 1
  fi

  eval menuctl multi menukeys key index selection "$keys" $(
    cd "$1"
    set -- "$(cd -L -- "$1" && pwd -L)"

    array DIR_ARRAY

    if [ ! "$(pwd)" = "/" ]
    then
      array DIR_ARRAY add "${1}/..=.."
    else
      set -- ""
    fi

    for k in ..?* .[!.]* *
    do
      if [ -e "$k" ]
      then
        array DIR_ARRAY add "${1}/$k=$k"
      fi
    done

    array DIR_ARRAY get

    # FILE="$(eval menu $(array DIR_ARRAY get))"
    #
    # if [ -n "$FILE" ]
    # then
    #   echo "$(cd -L -- "$1" && pwd -L)/$FILE"
    # fi
  )

  echo "key=$key"; echo "index=$index"; echo "selection=$selection"
}

menu_dir()
{
  if [ ! -d "$1" ]
  then
    return 1
  fi

  cd "$1"
  set -- "$(cd -L -- "$1" && pwd -L)"

  array DIR_ARRAY

  if [ "$(pwd)" = "/" ]
  then
    set -- ""
  else
    array DIR_ARRAY add "${1}/..=.."
  fi

  for k in ..?* .[!.]* *
  do
    if [ -e "$k" ]
    then
      array DIR_ARRAY add "${1}/$k=$k"
    fi
  done

  eval menuread "key" "file" "list" $(array DIR_ARRAY get)

  echo "key=$key"
  echo "file=$file"
  echo "list=$list"
  read x

  array DIR_ARRAY unset
}

#-------------------------------------------------------------------------------

realpaths

keys="canc:c:d:m:r"

menuset id
menuset multi
menuset keys "$keys"

menu_dir "/"

while [ "$key" = "enter" ] && [ -d "$file" ]
do
  menu_dir "$file"
done
