#!/bin/sh

#-------------------------------------------------------------------------------

. array.lib.sh
. menu.lib.sh

#-------------------------------------------------------------------------------

menu_dir()
{
  if [ ! -d "$1" ]
  then
    return 1
  fi

  cd "$1"
  set -- "$(cd -L -- "$1" && pwd -L)"

  array DIR_ARRAY

  if [ "$(pwd)" = "/" ]
  then
    set -- ""
  else
    array DIR_ARRAY add "${1}/..=.."
  fi

  for k in ..?* .[!.]* *
  do
    if [ -e "$k" ]
    then
      array DIR_ARRAY add "${1}/$k=$k"
    fi
  done

  eval menuread "key" "file" "list" $(array DIR_ARRAY get)

  array DIR_ARRAY unset
}

#-------------------------------------------------------------------------------

menuset id

if [ -z "$1" ]
then
  menu_dir "$(pwd)"
else
  menu_dir "$1"
fi

while [ "$key" = "enter" ] && [ -d "$file" ]
do
  menu_dir "$file"
done

# perform action associated with selected key on selecteditems
echo "key=$key"
echo "file=$file"
echo "list=$list"
