#!/bin/sh

#-------------------------------------------------------------------------------

. array.lib.sh

#-------------------------------------------------------------------------------

readc()
{
  stty -echo -icanon min 1 time 0

  read -r key << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF

  if [ "$key" = "esc" ]
  then
    stty -echo -icanon min 0 time 0
    read -r key1 << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF
    read -r key2 << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF
    read -r key3 << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF
    read -r key4 << EOF
$(dd bs=1 count=1 2>/dev/null | od -A n -t a)
EOF
    key="$key1$key2$key3$key4"
    case "$key" in
      "[A") key="up";;
      "[B") key="down";;
      "[C") key="right";;
      "[D") key="left";;
      "[F") key="end";;
      "[H") key="home";;
      "[1~") key="home";;
      "[4~") key="end";;
      "[5~") key="pageup";;
      "[6~") key="pagedown";;
      *) key="esc$key";;
    esac
  elif [ "$key" = "sp" ]
  then
    key="space"
  elif [ "$key" = "ht" ]
  then
    key="tab"
  elif [ "$key" = "lf" ]
  then
    key="enter"
  elif [ "$key" = "nl" ]
  then
    key="enter"
  fi

  eval "$1='$key'"
}

#-------------------------------------------------------------------------------

screen_init()
{
  saved_tty_settings=$(stty -g)
  tput sc
  tput smcup
  tput clear

  screen_vars_update
}

screen_reset()
{
  tput clear
  tput rmcup
  tput rc
  stty "$saved_tty_settings"
}

screen_vars_update()
{
  # fix fo initial wrong values of size from tput
  tput clear
  i=0
  while [ "$i" -lt "999" ]
  do
    printf "                                                 "
    i="$(($i + 1))"
  done
  tput clear

  # get terminal size
  TERM_ROWS="$(tput lines)"
  TERM_COLS="$(tput cols)"

  # init render region
  if [ -z "$ROW_0" ]
  then
    ROW_0="0"
  fi

  if [ -z "$COL_0" ]
  then
    COL_0="0"
  fi

  if [ -z "$ROWS" ]
  then
    ROWS="$TERM_ROWS"
  fi

  if [ -z "$COLS" ]
  then
    COLS="$TERM_COLS"
  fi

  # init limits
  if [ -z "$ROWS_MIN" ]
  then
    ROWS_MIN="2"
  fi

  if [ -z "$MENU_ENTRY_SIZE_MIN" ]
  then
    MENU_ENTRY_SIZE_MIN="3"
  fi

  if [ "$ROW_0" -gt "$(($TERM_ROWS - 1 - $ROWS_MIN))" ]
  then
    ROW_0="$(($TERM_ROWS - 1 - $ROWS_MIN))"
  fi

  if [ "$COL_0" -gt "$(($TERM_COLS - 1 - $MENU_ENTRY_SIZE_MIN))" ]
  then
    COL_0="$(($TERM_COLS - 1 - $MENU_ENTRY_SIZE_MIN))"
  fi

  if [ "$(($ROW_0 + $ROWS))" -gt "$TERM_ROWS" ]
  then
    ROWS="$(($TERM_ROWS - $ROW_0))"
  fi

  if [ "$(($COL_0 + $COLS))" -gt "$TERM_COLS" ]
  then
    COLS="$(($TERM_COLS - $COL_0))"
  fi

  # init multi selection
  if [ -z "$SEL_ITEM_TRUE_STRING" ]
  then
    SEL_ITEM_TRUE_STRING="+"
  fi

  if [ -z "$SEL_ITEM_FALSE_STRING" ]
  then
    SEL_ITEM_FALSE_STRING="-"
  fi
}

#-------------------------------------------------------------------------------

quit()
{
  screen_reset

  if [ -z "$1" ]
  then
    exit 1
  else
    exit "$1"
  fi
}

return_selection()
{
  screen_reset

  if [ ! "$MENU_MULTISELECTION" = "true" ]
  then
    SELECTED_POS="$ARRAY_POS"
    (array MENU_IDS get "$SELECTED_POS") 1>&2
  else
    array MENU_SELECTED_ITEMS
    i="0"
    n="$(array MENU_SEL size)"
    while [ "$i" -lt "$n" ]
    do
      if [ "$(array MENU_SEL get "$i")" = "$SEL_ITEM_TRUE_STRING" ]
      then
        array MENU_SELECTED_ITEMS add "$(array MENU_IDS get "$i")"
      fi
      i="$(($i + 1))"
    done
    echo "result"
    array MENU_SELECTED_ITEMS get
    (array MENU_SELECTED_ITEMS get) 1>&2
  fi

  exit 0
}

select_item_toggle()
{
  if [ ! "$MENU_MULTISELECTION" = "true" ]
  then
    return 0
  fi

  SELECTED_POS="$ARRAY_POS"
  SEL_ITEM_CURR_STRING="$(array MENU_SEL get "$SELECTED_POS")"
  if [ "$SEL_ITEM_CURR_STRING" = "$SEL_ITEM_TRUE_STRING" ]
  then
    array MENU_SEL put "$SELECTED_POS" "$SEL_ITEM_FALSE_STRING"
  elif [ "$SEL_ITEM_CURR_STRING" = "$SEL_ITEM_FALSE_STRING" ]
  then
    array MENU_SEL put "$SELECTED_POS" "$SEL_ITEM_TRUE_STRING"
  else
    # quit
    false
    # array MENU_SEL set "$SELECTED_POS" "$SEL_ITEM_TRUE_STRING"
  fi

  # print_menu_entry "$(($ARRAY_POS_START + $SELECTED_POS))"
  print_menu_entry "$CURSOR_POS"
}

menu_init()
{
  array MENU_IDS
  array MENU_TEXTS
  array MENU_SEL

  for k in "$@"
  do
    ID="${k%%=*}"
    TEXT="${k#*=}"
    array MENU_IDS add "$ID"
    array MENU_TEXTS add "$TEXT"
    array MENU_SEL add "$SEL_ITEM_FALSE_STRING"
  done

  ARRAY_SIZE="$(array MENU_IDS size)"
  ARRAY_POS="0"
  CURSOR_POS="0"

  if [ "$ARRAY_SIZE" -lt "$ROWS" ]
  then
    ROWS="$ARRAY_SIZE"
  fi
}

print_menu_entry()
{
  # clear whole line
  tput cup "$(($ROW_0 + $1))" "$COL_0"
  printf "%${COLS}s"
  tput cup "$(($ROW_0 + $1))" "$COL_0"

  # build line to print
  # line="$(tput setaf 2)${1}$(tput sgr0) $(tput setaf 3)[$(array MENU_SEL get "$1")]$(tput sgr0) $(array MENU_TEXTS get "$1")"

  # line="$(printf "$line" | tr -cd '[:print:]')"
  # line="$(printf "$line" | sed 's/[^[:print:]]//g')"
  # line="$(printf "$line" | sed $'s/\033\[[0-9;]*m//g')"

  # line="$(array MENU_TEXTS get "$1")"

  # limit too long lines (use line without ascii control codes)
  line="$(($ARRAY_POS_START + $1)) [$(array MENU_SEL get "$(($ARRAY_POS_START + $1))")] $(array MENU_TEXTS get "$(($ARRAY_POS_START + $1))")"
  size="$(printf "$line" | wc -m)"
  line="$(array MENU_TEXTS get "$(($ARRAY_POS_START + $1))")"
  if [ "$size" -gt "$COLS" ]
  then
    sizeexceed="$(($size - $COLS))"
    size="$(printf "$line" | wc -m)"
    line="$(printf "$line" | cut -c "1-$(($size - $sizeexceed - 6))")$(tput setaf 1) [...]$(tput sgr0)"
    # line="$(printf "$line" | cut -c "1-$(($COLS - 6))")$(tput setaf 1) [...]$(tput sgr0)"
  fi

  # print line
  # line="$(tput setaf 2)${1}$(tput sgr0) $(tput setaf 3)[$(array MENU_SEL get "$1")]$(tput sgr0) $(array MENU_TEXTS get "$1")"
  line="$(tput setaf 2)$(($ARRAY_POS_START + $1))$(tput sgr0) $(tput setaf 3)[$(array MENU_SEL get "$(($ARRAY_POS_START + $1))")]$(tput sgr0) $line"
  printf "$line"
  # printf "$(tput setaf 2)${1}$(tput sgr0) $(tput setaf 3)'$(array MENU_SEL get "$1")'$(tput sgr0) $line"
  # SEL_ITEM_CURR_STRING="$(array MENU_SEL get "$SELECTED_POS")"
  # printf "$(tput setaf 2)${1}$(tput sgr0) $(tput setaf 3)'$SEL_ITEM_CURR_STRING'$(tput sgr0) $line"
  tput cup "$(($ROW_0 + $1))" "$COL_0"
}

screen_render()
{
  ARRAY_POS_START="$1"

  # tput clear
  i="0"
  n="$ROWS"
  while [ "$i" -lt "$n" ]
  do
    # tput cup "$(($ROW_0 + $i))" "$COL_0"
    # print_menu_entry "$(($ARRAY_POS_START + $i))"
    print_menu_entry "$i" "$ARRAY_POS_START"
    i="$(($i + 1))"
  done

  tput cup "$ROW_0" "$COL_0"
}

scroll_cursor()
{
  UPDATE_SCREEN="false"

  CURSOR_POS="$(($CURSOR_POS + $1))"
  ARRAY_POS="$(($ARRAY_POS + $1))"

  if [ "$CURSOR_POS" -lt "0" ]
  then
    ARRAY_POS_START="$(($ARRAY_POS_START + $1))"
    CURSOR_POS="0"
    UPDATE_SCREEN="true"
  elif [ "$CURSOR_POS" -gt "$(($ROWS - 1))" ]
  then
    ARRAY_POS_START="$(($ARRAY_POS_START + $1))"
    CURSOR_POS="$(($ROWS - 1))"
    UPDATE_SCREEN="true"
  fi

  if [ "$ARRAY_POS" -lt "0" ]
  then
    ARRAY_POS=0
  elif [ "$ARRAY_POS" -gt "$(($ARRAY_SIZE - 1))" ]
  then
    ARRAY_POS="$(($ARRAY_SIZE - 1))"
  fi

  if [ "$ARRAY_POS_START" -lt "0" ]
  then
    ARRAY_POS_START=0
  elif [ "$ARRAY_POS_START" -gt "$(($ARRAY_SIZE - $ROWS))" ]
  then
    ARRAY_POS_START="$(($ARRAY_SIZE - $ROWS))"
  fi

  if [ "$UPDATE_SCREEN" = true ]
  then
    screen_render "$ARRAY_POS_START"
    # screen_render "$((ARRAY_POS - $CURSOR_POS))"
    # screen_render "$((ARRAY_POS - $CURSOR_POS + 1))"
  fi

  # tput cup $CURSOR_POS 0
  tput cup "$(($ROW_0 + $CURSOR_POS))" "$COL_0"
}

scroll_page()
{
  scroll_cursor $(($1 * ($ROWS - 1)))
  # scroll_cursor "$(($1 * $ROWS - 1))"
}

move_cursor_to()
{
  ARRAY_POS="0"
  CURSOR_POS="0"
  scroll_cursor "$1"
  screen_render "$((ARRAY_POS - $CURSOR_POS))"

  # tput cup $CURSOR_POS 0
  tput cup "$(($ROW_0 + $CURSOR_POS))" "$COL_0"
}

key_loop()
{
  while true
  do
    readc key

    case "$key" in
      "q") quit;;
      "up") scroll_cursor "-1";;
      "down") scroll_cursor "+1";;
      "pageup") scroll_page "-1";;
      "pagedown") scroll_page "+1";;
      "home") move_cursor_to "0";;
      "end") move_cursor_to "$(($ARRAY_SIZE - 1))";;
      "space") select_item_toggle;;
      "enter") return_selection;;
      # *) exit 1;;
    esac
  done
}

main()
{
  if [ ! -t 0 ]
  then
    # echo "no tty" 1>&2
    echo "no tty"
    exit 1
  fi

  if [ -z "$*" ]
  then
    # echo "no args" 1>&2
    echo "no args"
    exit 1
  fi

  trap "screen_reset; exit 2" INT QUIT TERM HUP PIPE ABRT TSTP
  screen_init

  # i=0
  # while [ "$i" -lt "999" ]
  # do
  #   printf "*************************************************"
  #   i="$(($i + 1))"
  # done
  menu_init "$@"
  screen_render 0

  key_loop
}

main "$@" 3>&2 2>&1 1>&3
