#!/bin/sh

#-------------------------------------------------------------------------------

. term.lib.sh
. menu.lib.sh

#-------------------------------------------------------------------------------

menu_instance()
{
(
#   echo "args=$@"
#   echo "args=$@" 1>&2
# read x

  # eval $1
  eval "$1"
  # eval "$1" 1>&2
  # echo "m_menu_MENU_HEADER=$m_menu_MENU_HEADER" 1>&2
  # echo "m_menu_MENU_HEADER=$m_menu_MENU_HEADER"
  # return 0
# read x
#   echo "arg1=$1" 1>&2
# read x
#   echo "args=$@" 1>&2
# read x

  # eval set -- \"$1\"
  # for k in "$@"
  # do
  #   echo "k=$k" 1>&2
  # done

#   eval set -- $1
#   for k in "$@"
#   # for k in $1
#   do
#     true
#     # eval  "export $k"
#     # echo "export $k" 1>&2
#     echo "k=$k" 1>&2
#   done
# read x

  # export KEY_LOOP="true"
  # eval $1 term-render-menu "test1 test2 test3"
  # term-render-menu test1 test2 test3
  term-render-menu
)
}

#-------------------------------------------------------------------------------

main()
{
  term_screen_init

  menuset id
  menuset multi
  menuset keys "b:n:m"
  menuset header "$(printf "Menu Header - ROW 1\n---Row 2---\n---Row 3---\n\n")"
  menuset footer "$(printf "Menu Footer - ROW 1\n---Row 2---")"
  menuset region 5 10 20 30

  export m_menu_MENU_RETURN_ENV="true"

  var1="$(KEY_LOOP="false"                   m_menu_CURSOR_POS_START="1" m_menu_ARRAY_POS_START="2" menucmd footer "footer 1" term-render-menu "$@")"
  var2="$(KEY_LOOP="false" m_menu_COL_0="40" m_menu_CURSOR_POS_START="2" m_menu_ARRAY_POS_START="2" menucmd footer "footer 2" term-render-menu "$@")"

  # var1="$(m_menu_CURSOR_POS_START="1" m_menu_ARRAY_POS_START="2" m_menu_ROW_0="$m_menu_ROW_0" m_menu_COL_0="10" m_menu_ROWS="20" m_menu_COLS="30" term-render-menu "$@")"
  # var2="$(m_menu_CURSOR_POS_START="4" m_menu_ARRAY_POS_START="1" m_menu_ROW_0="$m_menu_ROW_0" m_menu_COL_0="40" m_menu_ROWS="20" m_menu_COLS="30" term-render-menu "$@")"
  # echo "var1=$var1"
  # echo "var2=$var2"
  # read x

  # term_region_clear "0" "10" "20" "30"
  # read x

  while [ true ]
  do
    # var1="$(menu_instance "$var1")"
    # var2="$(menu_instance "$var2")"
    # var1="$(eval "$var1" && term-render-menu)"
    # var2="$(eval "$var2" && term-render-menu)"
    menueval "var1" term-render-menu
    menueval "var2" term-render-menu
    # read x
  done

  term_screen_reset

  # echo "var1=$var1" 1>&2
  # echo "var2=$var2" 1>&2
  echo "var1=$var1"
  echo "var2=$var2"
}

#-------------------------------------------------------------------------------

___main()
{
  term_screen_init
  # term-menu "$@"
  term-render-menu "$@"
  term_screen_reset
}

#-------------------------------------------------------------------------------

# main "$@" 3>&2 2>&1 1>&3
main "$@"
