#!/bin/sh

#-------------------------------------------------------------------------------

. env.lib.sh
. term.lib.sh

. array.lib.sh
. menu.lib.sh

#-------------------------------------------------------------------------------

menu_dir()
{
  if [ ! -d "$1" ]
  then
    return 1
  fi

  cd "$1"
  set -- "$(cd -L -- "$1" && pwd -L)"

  array DIR_ARRAY

  if [ "$(pwd)" = "/" ]
  then
    set -- ""
  else
    array DIR_ARRAY add "${1}/..=.."
  fi

  for k in ..?* .[!.]* *
  do
    if [ -e "$k" ]
    then
      # array DIR_ARRAY add "${1}/$k=$k"
      if [ -d "$k" ]
      then
        array DIR_ARRAY add "${1}/$k=[D] $k"
      elif [ -f "$k" ]
      then
        array DIR_ARRAY add "${1}/$k=[F] $k"
      fi
    fi
  done

  # eval menuread "key" "file" "selection" $(array DIR_ARRAY get)
  # array FILE_SELECTION add "$selection"
  #
  # array DIR_ARRAY unset
}

#-------------------------------------------------------------------------------

env_defaults()
{
  true
  # set proper initial variables values
}

args_init()
{
  menu_dir "$@"
}

render()
{
  eval KEY_LOOP="false" tui-menu $(array DIR_ARRAY get)
}

key_loop()
{
  while true
  do
    term_region_clear
    eval menuexec key res selection tui-menu $(array DIR_ARRAY get)

    if [ -z "$res" ]
    then
      return 0
    fi

    case "$key" in
      "q") return 0;;
      "esc") return 0;;
      # "space") select_item_toggle;;
      "enter") menu_dir "$res";;
      # *) check_key "$key";;
    esac
  done
}

env_list_get()
{
  env_list "term_ROW\|term_COL\|term_FS_"
}

#-------------------------------------------------------------------------------

. tui-main.src.sh
