#!/bin/sh

#-------------------------------------------------------------------------------

. arg.lib.sh
. env.lib.sh
. array.lib.sh
. term.lib.sh

#-------------------------------------------------------------------------------

select_item_toggle()
{
  if [ ! "$tui_TEXT_MULTISELECTION" = "true" ]
  then
    return 0
  fi

  tui_TEXT_SELECTED_POS="$tui_TEXT_ARRAY_POS"
  tui_TEXT_SEL_ITEM_CURR_STRING="$(array tui_TEXT_SEL get "$tui_TEXT_ARRAY_POS")"
  if [ "$tui_TEXT_SEL_ITEM_CURR_STRING" = "$tui_TEXT_SEL_ITEM_TRUE_STRING" ]
  then
    array tui_TEXT_SEL put "$tui_TEXT_ARRAY_POS" "$tui_TEXT_SEL_ITEM_FALSE_STRING"
  elif [ "$tui_TEXT_SEL_ITEM_CURR_STRING" = "$tui_TEXT_SEL_ITEM_FALSE_STRING" ]
  then
    array tui_TEXT_SEL put "$tui_TEXT_ARRAY_POS" "$tui_TEXT_SEL_ITEM_TRUE_STRING"
  else
    false
  fi

  print_text_line "$tui_TEXT_ARRAY_POS" "$tui_TEXT_CURSOR_POS"
}

print_text_line()
{
  tui_TEXT_LINE_INDEX="$1"
  tui_TEXT_LINE_ROW="$2"

  # clear whole line
  term_render tput cup "$(($term_ROW0 + $tui_TEXT_LINE_ROW))" "$term_COL0"
  term_render printf "%${term_COLS}s"
  term_render tput cup "$(($term_ROW0 + $tui_TEXT_LINE_ROW))" "$term_COL0"

  # limit too long lines (use line without ascii control codes)
  line="$tui_TEXT_LINE_INDEX $(array tui_TEXT_TEXTS get "$tui_TEXT_LINE_INDEX")"
  size="$(printf "$line" | wc -m)"
  line="$(array tui_TEXT_TEXTS get "$tui_TEXT_LINE_INDEX")"
  if [ "$size" -gt "$term_COLS" ]
  then
    sizeexceed="$(($size - $term_COLS))"
    size="$(printf "$line" | wc -m)"
    line="$(printf "$line" | cut -c "1-$(($size - $sizeexceed - 6))")$(tput setaf 1) [...]$(tput sgr0)"
  fi

  # print line
  line="$(tput setaf 2)$tui_TEXT_LINE_INDEX$(tput sgr0) $line"
  term_render printf "$line"

  term_render tput cup "$(($term_ROW0 + $tui_TEXT_LINE_ROW))" "$term_COL0"
}

screen_render()
{
  tui_TEXT_ARRAY_POS_START="$1"

  i="0"
  n="$term_ROWS"
  while [ "$i" -lt "$n" ]
  do
    print_text_line "$(($tui_TEXT_ARRAY_POS_START + $i))" "$i"
    i="$(($i + 1))"
  done
}

menu_LINE_highlight()
{
  term_render tput cup "$(($term_ROW0 + $1))" "$term_COL0"
}

scroll_cursor()
{
  if [ "$1" -lt "0" ]
  then
    if [ "$tui_TEXT_CURSOR_POS" = "0" ] && [ "$tui_TEXT_ARRAY_POS_START" = "0" ]
    then
      true
    elif [ "$tui_TEXT_CURSOR_POS" = "0" ] && [ "$tui_TEXT_ARRAY_POS_START" -gt "0" ]
    then
      tui_TEXT_ARRAY_POS_START="$(($tui_TEXT_ARRAY_POS_START + $1))"
      tui_TEXT_ARRAY_POS="$(($tui_TEXT_ARRAY_POS + $1))"
      screen_render "$tui_TEXT_ARRAY_POS_START"
      menu_LINE_highlight "$tui_TEXT_CURSOR_POS"
    else
      tui_TEXT_CURSOR_POS="$(($tui_TEXT_CURSOR_POS + $1))"
      tui_TEXT_ARRAY_POS="$(($tui_TEXT_ARRAY_POS + $1))"
      menu_LINE_highlight "$tui_TEXT_CURSOR_POS"
    fi
  elif [ "$1" -gt "0" ]
  then
    if [ "$tui_TEXT_CURSOR_POS" = "$(($term_ROWS - 1))" ] && [ "$tui_TEXT_ARRAY_POS_START" = "$(($tui_TEXT_ARRAY_SIZE - $term_ROWS))" ]
    then
      true
    elif [ "$tui_TEXT_CURSOR_POS" = "$(($term_ROWS - 1))" ] && [ "$tui_TEXT_ARRAY_POS_START" -lt "$(($tui_TEXT_ARRAY_SIZE - $term_ROWS))" ]
    then
      tui_TEXT_ARRAY_POS_START="$(($tui_TEXT_ARRAY_POS_START + $1))"
      tui_TEXT_ARRAY_POS="$(($tui_TEXT_ARRAY_POS + $1))"
      screen_render "$tui_TEXT_ARRAY_POS_START"
      menu_LINE_highlight "$tui_TEXT_CURSOR_POS"
    else
      tui_TEXT_CURSOR_POS="$(($tui_TEXT_CURSOR_POS + $1))"
      tui_TEXT_ARRAY_POS="$(($tui_TEXT_ARRAY_POS + $1))"
      menu_LINE_highlight "$tui_TEXT_CURSOR_POS"
    fi
  fi
}

check_cursor()
{
  if [ "$tui_TEXT_CURSOR_POS" -lt "0" ]
  then
    tui_TEXT_CURSOR_POS="0"
  elif [ "$tui_TEXT_CURSOR_POS" -gt "$(($term_ROWS - 1))" ]
  then
    tui_TEXT_CURSOR_POS="$(($term_ROWS - 1))"
  fi

  if [ "$tui_TEXT_ARRAY_POS" -lt "0" ]
  then
    tui_TEXT_ARRAY_POS=0
  elif [ "$tui_TEXT_ARRAY_POS" -gt "$(($tui_TEXT_ARRAY_SIZE - 1))" ]
  then
    tui_TEXT_ARRAY_POS="$(($tui_TEXT_ARRAY_SIZE - 1))"
  fi

  if [ "$tui_TEXT_ARRAY_POS_START" -lt "0" ]
  then
    tui_TEXT_ARRAY_POS_START=0
  elif [ "$tui_TEXT_ARRAY_POS_START" -gt "$(($tui_TEXT_ARRAY_SIZE - $term_ROWS))" ]
  then
    tui_TEXT_ARRAY_POS_START="$(($tui_TEXT_ARRAY_SIZE - $term_ROWS))"
  fi
}

scroll_page()
{
  if [ "$1" -lt "0" ]
  then
    if [ "$tui_TEXT_CURSOR_POS" = "0" ]
    then
      tui_TEXT_ARRAY_POS="$(($tui_TEXT_ARRAY_POS - $term_ROWS))"
      tui_TEXT_ARRAY_POS_START="$(($tui_TEXT_ARRAY_POS_START - $term_ROWS))"
      check_cursor
      screen_render "$tui_TEXT_ARRAY_POS_START"
      menu_LINE_highlight "$tui_TEXT_CURSOR_POS"
    elif [ "$tui_TEXT_CURSOR_POS" -gt "0" ]
    then
      tui_TEXT_ARRAY_POS="$(($tui_TEXT_ARRAY_POS - $tui_TEXT_CURSOR_POS))"
      tui_TEXT_CURSOR_POS="0"
      menu_LINE_highlight "$tui_TEXT_CURSOR_POS"
    fi
  elif [ "$1" -gt "0" ]
  then
    if [ "$tui_TEXT_CURSOR_POS" = "$(($term_ROWS - 1))" ]
    then
      tui_TEXT_ARRAY_POS="$(($tui_TEXT_ARRAY_POS + $term_ROWS))"
      tui_TEXT_ARRAY_POS_START="$(($tui_TEXT_ARRAY_POS_START + $term_ROWS))"
      check_cursor
      screen_render "$tui_TEXT_ARRAY_POS_START"
      menu_LINE_highlight "$tui_TEXT_CURSOR_POS"
    elif [ "$tui_TEXT_CURSOR_POS" -lt "$(($term_ROWS - 1))" ]
    then
      tui_TEXT_ARRAY_POS="$(($tui_TEXT_ARRAY_POS - $tui_TEXT_CURSOR_POS))"
      tui_TEXT_CURSOR_POS="$(($term_ROWS - 1))"
      menu_LINE_highlight "$tui_TEXT_CURSOR_POS"
    fi
  fi
}

move_cursor_to_start()
{
  tui_TEXT_CURSOR_POS="0"
  tui_TEXT_ARRAY_POS="0"
  tui_TEXT_ARRAY_POS_START="0"

  screen_render "0"

  menu_LINE_highlight "$tui_TEXT_CURSOR_POS"
}

move_cursor_to_end()
{
  tui_TEXT_CURSOR_POS="$(($term_ROWS - 1))"
  tui_TEXT_ARRAY_POS="$(($tui_TEXT_ARRAY_SIZE - 1))"

  if [ "$tui_TEXT_ARRAY_SIZE" -lt "$term_ROWS" ]
  then
    tui_TEXT_ARRAY_POS_START="0"
  else
    tui_TEXT_ARRAY_POS_START="$(($tui_TEXT_ARRAY_SIZE - $term_ROWS))"
  fi

  screen_render "$tui_TEXT_ARRAY_POS_START"
  menu_LINE_highlight "$tui_TEXT_CURSOR_POS"
}

return_selection()
{
  tui_TEXT_RETURN_KEY="$key"
  tui_TEXT_RETURN_ITEM="$(array tui_TEXT_IDS get "$tui_TEXT_ARRAY_POS")"
  array tui_TEXT_SELECTED_ITEMS
  i="0"
  n="$(array tui_TEXT_SEL size)"
  while [ "$i" -lt "$n" ]
  do
    if [ "$(array tui_TEXT_SEL get "$i")" = "$tui_TEXT_SEL_ITEM_TRUE_STRING" ]
    then
      array tui_TEXT_SELECTED_ITEMS add "$(array tui_TEXT_IDS get "$i")"
    fi
    i="$(($i + 1))"
  done
  tui_TEXT_RETURN_SELECTION="$(array tui_TEXT_SELECTED_ITEMS get)"

  exit 0
}

#-------------------------------------------------------------------------------

env_init()
{
  tui_TEXT_ARGS="$(saveargs "$@")"

  init_text_array "$@"

  tui_TEXT_ARRAY_SIZE="$(array tui_TEXT_TEXTS size)"
  tui_TEXT_ARRAY_POS="0"
  tui_TEXT_CURSOR_POS="0"

  if [ "$tui_TEXT_ARRAY_SIZE" -lt "$term_ROWS" ]
  then
    term_ROWS="$tui_TEXT_ARRAY_SIZE"
  fi
}

init_text_array()
{
  array tui_TEXT_TEXTS
OLD_IFS="$IFS"
  # eval set -- $(
    IFS='
'
    for line in $@
    do
      # term_render echo "line=$line"
      array tui_TEXT_TEXTS add "$line"
    done
  # term_render echo "$(array "tui_TEXT_TEXTS" get)"
    # array "tui_TEXT_TEXTS" get
  # )
  # eval array "tui_TEXT_TEXTS" set $@
  IFS="$OLD_IFS"
  term_render echo "$(array "tui_TEXT_TEXTS" get)"
  read x
}

_init_text_array()
{
  array tui_TEXT_TEXTS

  eval array tui_TEXT_TEXTS set $(
    IFS='
'
    for line in $@
    do
      # term_render echo "line=$line"
      array tui_TEXT_TEXTS add "$line"
    done
  term_render echo "$(array "tui_TEXT_TEXTS" get)"
    array "tui_TEXT_TEXTS" get
  )
  term_render echo "$(array "tui_TEXT_TEXTS" get)"
  read x
}

render()
{
  term_region_clear
  eval "set -- $tui_TEXT_ARGS"
  screen_render "${tui_TEXT_ARRAY_POS_START:-"0"}"
  menu_LINE_highlight "${tui_TEXT_CURSOR_POS:-"0"}"
}

key_default()
{
  return 0
}

key_q()
{
  return 1
}

key_esc()
{
  return 1
}

key_up()
{
  scroll_cursor "-1"
}

key_down()
{
  scroll_cursor "+1"
}

key_pageup()
{
  scroll_page "-1"
}

key_pagedown()
{
  scroll_page "+1"
}

key_home()
{
  move_cursor_to_start
}

key_end()
{
  move_cursor_to_end
}

key_space()
{
  select_item_toggle
}

key_enter()
{
  return_selection
}

_key_loop()
{
  while true
  do
    env_export "tui_TEXT_STATE_1" env_import "$tui_TEXT_STATE_1" tui-menu
    env_export "tui_TEXT_STATE_2" env_import "$tui_TEXT_STATE_2" tui-menu

    key="$(readc)"

    case "$key" in
      "q") exit 0;;
      "esc") exit 0;;
      "space") true;;
      "enter") true;;
      *) exit 1;;
    esac
  done
}

env_list_get()
{
  env_list "term_ROW\|term_COL\|tui_TEXT_\|key"
}

env_result()
{
  true
}

#-------------------------------------------------------------------------------

. tui-main.src.sh
