#!/bin/sh

#-------------------------------------------------------------------------------

. env.lib.sh
. term.lib.sh

. array.lib.sh
. menu.lib.sh

#-------------------------------------------------------------------------------

init_menu_dir()
{
  if [ ! -d "$1" ]
  then
    return 1
  fi

  cd "$1"
  set -- "$(cd -L -- "$1" && pwd -L)"

  array DIR_ARRAY

  if [ "$(pwd)" = "/" ]
  then
    set -- ""
  else
    array DIR_ARRAY add "${1}/..=.."
  fi

  for k in ..?* .[!.]* *
  do
    if [ -e "$k" ]
    then
      # array DIR_ARRAY add "${1}/$k=$k"
      if [ -d "$k" ]
      then
        array DIR_ARRAY add "${1}/$k=[D] $k"
      elif [ -f "$k" ]
      then
        array DIR_ARRAY add "${1}/$k=[F] $k"
      fi
    fi
  done

  # eval menuread "key" "file" "selection" $(array DIR_ARRAY get)
  # array FILE_SELECTION add "$selection"
  #
  # array DIR_ARRAY unset
}

#-------------------------------------------------------------------------------

env_defaults()
{
  true
  # set proper initial variables values
}

args_init()
{
  init_menu_dir "$@"
}

render()
{
  eval KEY_LOOP="false" tui-menu $(array DIR_ARRAY get)
}


key_loop()
{
  key="enter"
  res="$(pwd)"

  while [ "$key" = "enter" ] && [ -n "$res" ]
  do
    term_region_clear
    vars="$(eval ENV_RETURN="export" tui-menu $(array DIR_ARRAY get))"
    # term_error echo "vars=$vars"
    KEY_LOOP="false" ENV_IMPORT="true" eval "$vars; menuexec key res selection tui-menu"
    term_region_clear; term_render echo "key=$key"; term_render echo "res=$res"; term_render echo "selection=$selection"; read x
    if [ -d "$res" ]
    then
      # save dir state
      init_menu_dir "$res"
      # get dir state and pass it
    fi
  done
}

env_list_get()
{
  env_list "term_ROW\|term_COL\|term_FS_"
}

return_res()
{
  true
  # return result: custom key pressed + global selection
}

#-------------------------------------------------------------------------------

. tui-main.src.sh
