#!/bin/sh

#-------------------------------------------------------------------------------

. arg.lib.sh
. env.lib.sh
. term.lib.sh
. menu.lib.sh

#-------------------------------------------------------------------------------

env_init()
{
  menuset id
  menuset multi
  menuset keys "b:n:m"

  tui_MULTI_MENU_ARGS="$(saveargs "$@")"
}

render()
{
  term_region_clear
  eval "set -- $tui_MULTI_MENU_ARGS"
  term_COL0="10" env_export tui_MULTI_MENU_STATE_1 tui-menu "$@"
  term_COL0="50" env_export tui_MULTI_MENU_STATE_2 tui-menu "$@"
}

key_loop()
{
  while true
  do
    env_export "tui_MULTI_MENU_STATE_1" env_import "$tui_MULTI_MENU_STATE_1" tui-menu
    env_export "tui_MULTI_MENU_STATE_2" env_import "$tui_MULTI_MENU_STATE_2" tui-menu

    # key="$(readc)"
    #
    # case "$key" in
    #   "q") exit 0;;
    #   "esc") exit 0;;
    #   "space") true;;
    #   "enter") true;;
    #   *) exit 1;;
    # esac
  done
}

env_list_get()
{
  env_list "term_ROW\|term_COL\|tui_MULTI_MENU_\|key"
}

env_result()
{
  true
}

#-------------------------------------------------------------------------------

. tui-main.src.sh
