#!/bin/sh

#-------------------------------------------------------------------------------

. env.lib.sh
. term.lib.sh
. menu.lib.sh

#-------------------------------------------------------------------------------

menucustom()
{
  tui-menu "$@"
}

#-------------------------------------------------------------------------------

main()
{
  menuset id
  menuset multi
  menuset keys "b:n:m"

  export ENV_RETURN="export"

  var1="$(KEY_LOOP="false"                menucustom "$@")"
  var2="$(KEY_LOOP="false" term_COL0="40" menucustom "$@")"
  # term_output echo "vars"
  # term_output eval "$var1"
  # term_output eval "$var2"
  # term_output echo "var1=$var1"
  # term_output echo "var2=$var2"
  # read x

  # set -x
  while [ true ]
  do
    # menucustom
    # var1="$(eval "$var1" && menucustom)"
    # var2="$(eval "$var2" && menucustom)"
    env_eval "var1" tui-menu "$@"
    env_eval "var2" tui-menu "$@"
    # env_eval "var1" tui-menu
    # env_eval "var2" tui-menu
    # read x
  done
  # set +x
}

#-------------------------------------------------------------------------------

# main "$@" 3>&2 2>&1 1>&3
main "$@"
