#!/bin/sh

# dispatches high level commands to specific modules

. log.lib.sh

log_debug COMMAND_LINE="$@"

MODULE="${0}-${1}"
shift

log_debug MODULE="$MODULE"

if [ ! -f "$MODULE" ]
then
  log_fatal "module not found MODULE=$MODULE"
  exit 1
fi

"$MODULE" "$@"
