#!/bin/sh

# rsudo - use env and start interactive session
# rsudo $file:$name - if file not null load file then get env by name and start interactive session
# rsudo user@host - get pass from pipe if connected, ask tty otherwise, then start interactive session

# rsudo $args - use env and execute args as a remote command
# rsudo $file:$name $args  - if file not null load file then get env by name and execute args as a remote command
# rsudo user@host $args  - get pass from pipe if connected, ask tty otherwise, then execute args as a remote command

# if nargs=1, the args = sh -c "$args", else args = saveargs

. log.lib.sh
. arg.lib.sh
. rsudo.lib.sh

# the following lines are executed when ssh uses SSH_ASKPASS command
# maximum security is guaranteed because explicit check that caller process is ssh and
# more importantly RSUDO_PASSWORD environment variable is available only in the rsudo process tree
if [ "$(ps -o "comm=" -p "$PPID")" = "ssh" ]
then
  # RSUDO_PASSWORD="$(cat)"
  echo "$RSUDO_PASSWORD"
  log_debug "rsudo askpass called by ssh! RSUDO_PASSWORD availability=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no")"
  log_trace "RSUDO_PASSWORD=$RSUDO_PASSWORD"
# cat 1>&2
  exit 0
fi

#------------------------------------------------------------------------------

# replaces command to allow safe use of env
rsudo()
{
  log_trace "bypassed rsudo command by rsudo function"

# needs the following env vars to be defined outside

# required:
# RSUDO_HOST
# RSUDO_USER
# RSUDO_PASSWORD

# optional:
# RSUDO_AS_USER
# RSUDO_INTERACTIVE

if [ -z "$RSUDO_HOST" ] || [ -z "$RSUDO_USER" ] || [ -z "$RSUDO_PASSWORD" ]
then
  log_fatal "HOST=$RSUDO_HOST - USER=$RSUDO_USER - RSUDO_PASSWORD(availability)=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no")"
  exit 1
fi

log_info "RSUDO STARTED: HOST=$RSUDO_HOST - USER=$RSUDO_USER - RSUDO_PASSWORD(availability)=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no") - AS_USER=$RSUDO_AS_USER - COMMAND=$@"

# export DISPLAY=":0.0"
export SSH_ASKPASS="${0}"
export SSH_ASKPASS_REQUIRE="force"

# needed by SSH_ASKPASS command, try to see if it can read pipe
export RSUDO_PASSWORD

# DEBUG
for k in "$@"
do
  echo "arg before:'$k'"
done

if [ "$#" -eq "0" ] || [ -z "$*" ]
then
  log_trace "rsudo no args"
  if [ -t 0 ]
  then
    log_info "rsudo starting interactive session"

    RSUDO_INTERACTIVE="true"
    set -- su
  else
    log_trace "rsudo no args -> set command as /bin/sh -s (execute stream commands)"
    set -- sh -s
    log_debug "RSUDO: no args + non interactive term => attached to pipe or file -> get commands through stdin COMMAND=$@"
  fi
# rsudo args if one arg then treat as string with multiple commands, otherwise treat all args as single complex command
elif [ "$#" -eq "1" ]
then
  log_trace "one arg, treating as multicommand string"
  set -- sh -c "$1"
elif [ "$#" -gt "1" ]
then
  log_trace "many args, treating as single complex command (preserve quotes)"
  set -- "$(saveargs "$@")"

  # set -- "sh -c \"$*\""
  # set -- sh -c "$(saveargs "$@")"
  # set -- sh -c "eval \"$(saveargs "$@")\""
  # set -- sh -c "eval \"$@\""
  # set -- sh -c 'echo test; echo "0=$0 - args:$@"' my_cmd "$(saveargs "$@")"
fi

# DEBUG
for k in "$@"
do
  echo "arg after:'$k'"
done


if [ -n "$RSUDO_AS_USER" ]
then
  SUDO_AS_USER="--user=\"$RSUDO_AS_USER\""
fi

# non interactive
# interactive input from tty -> cannot pipe to ssh, pass inside ssh commands
# interactive input from pipe -> pipe commands, or data? NOT data because pipe MUST be disconnected for the session to be interactive
if [ "$RSUDO_INTERACTIVE" = "true" ]
then
  if [ ! -t 0 ]
  then
    RSUDO_PIPE_COMMANDS="$(cat)"
    if [ -n "$RSUDO_PIPE_COMMANDS" ]
    then
      set -- ${RSUDO_PIPE_COMMANDS}\; "$@"
      # set -- ${RSUDO_PIPE_COMMANDS}\; "$(saveargs "$@")"
      # set -- "$(saveargs ${RSUDO_PIPE_COMMANDS}\; "$@")"
      # set -- ${RSUDO_PIPE_COMMANDS} "&&" "$@"
      true
    fi
  fi
echo "interactive command"
# DEBUG
for k in "$@"
do
  echo "arg interactive:'$k'"
done
  # rsudo_interactive "sh -ic \"$@\""
  rsudo_interactive "$@"

  # ssh -t -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" \
  # echo "$RSUDO_PASSWORD" \| sudo -S --prompt='' -- true\; sudo $SUDO_AS_USER -- "sh -ic \"$@\"" </dev/tty
  # echo "$RSUDO_PASSWORD" \| sudo -S --prompt='' -- true\; sudo $SUDO_AS_USER -- "sh -ic \"${RSUDO_PIPE_COMMANDS}; $(saveargs "$@")\"" </dev/tty
  # echo "$RSUDO_PASSWORD" \| sudo -S --prompt='' -- true\; sudo $SUDO_AS_USER -- "sh -ic \"$(saveargs "$@")\"" </dev/tty
  # echo "$RSUDO_PASSWORD" \| sudo -S --prompt='' -- true\; sudo $SUDO_AS_USER -- "$(saveargs "$@")" </dev/tty
  # echo "$RSUDO_PASSWORD" \| sudo -S --prompt='' -- true\; sudo $SUDO_AS_USER -- "sh -ic '$@'" </dev/tty
else
echo "not interactive command"
  rsudo_not_interactive "$@"

  # (echo "$RSUDO_PASSWORD"; [ ! -t 0 ] && cat) | \
  # ssh -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" \
  # sudo -S --prompt='' $SUDO_AS_USER -- "$@"
  # sudo -S --prompt='' $SUDO_AS_USER -- "$(saveargs "$@")"
  # sudo -S --prompt='' $SUDO_AS_USER -- "sh -c \"$(saveargs "$@")\""
  # sudo -S --prompt='' $SUDO_AS_USER -- "sh -c \"$(saveargs "$(saveargs "$@")")\""
  # sudo -S --prompt='' $SUDO_AS_USER -- "sh -c \"echo $(saveargs "$@"); echo $@\""
  # sudo -S --prompt='' $SUDO_AS_USER -- "sh -c '$@'"
fi

EXIT_CODE="$?"

log_info "RSUDO ENDED: HOST=$RSUDO_HOST - USER=$RSUDO_USER"

exit "$EXIT_CODE"

}

#------------------------------------------------------------------------------

rsudo_interactive()
{
  ssh -t -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" \
  echo "$RSUDO_PASSWORD" \| sudo -S --prompt='' -- true\; sudo $SUDO_AS_USER -- "$@" </dev/tty
  # echo "$RSUDO_PASSWORD" \| sudo -S --prompt='' -- true\; sudo $SUDO_AS_USER -- "sh -ic \"$@\"" </dev/tty
}

#------------------------------------------------------------------------------

rsudo_not_interactive()
{
  (echo "$RSUDO_PASSWORD"; [ ! -t 0 ] && cat) | \
  ssh -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" \
  sudo -S --prompt='' $SUDO_AS_USER -- "$@"
  # sudo -S --prompt='' $SUDO_AS_USER -- "sh -c \"$@\""
}

#------------------------------------------------------------------------------

rsudo_main_retrieve_connection_args_and_call_rsudo_module_execute()
{
  # if host/user/pass vars are already exported from caller and no connection param is passed from command line then exported vars are used

  # check first arg for connection params
  # if [ "$1" != "${1#*@}" ]
  if [ "$1" = "-c" ]
  then
    shift
    if [ "$1" = "${1#*@}" ]
    then
      log_fatal "wrong connection string: $1"
      exit 1
    fi
    # user@host | @host
    RSUDO_HOST="${1#*@}"
    RSUDO_USER="${1%@*}"

    shift
  # elif [ "$1" != "${1%:*}" ]
  elif [ "$1" = "-l" ]
  then
    shift
    if [ "$1" = "${1%:*}" ]
    then
      log_fatal "wrong load string: $1"
      exit 1
    fi
    # file:name | :name
    ENV_ENCODED_FILE="${1%:*}"
    ENV_GROUP_NAME="${1#*:}"

    if [ -z "$ENV_ENCODED_FILE" ]
    then
      log_warn "env file not provided, searching into current env."
    elif ! rsudoenv_load "$ENV_ENCODED_FILE"
    then
      log_warn "env file error! not loaded, searching into current env."
    fi

    eval "RSUDO_HOST=\"\$RSUDO_ENV_${ENV_GROUP_NAME}_HOST\""
    eval "RSUDO_USER=\"\$RSUDO_ENV_${ENV_GROUP_NAME}_USER\""
    eval "RSUDO_PASSWORD=\"\$RSUDO_ENV_${ENV_GROUP_NAME}_PASS\""

    shift
  fi

  if [ -z "$RSUDO_HOST" ]
  then
    log_debug "rsudo: empty RSUDO_HOST"
    exit 1
  fi

  if [ -z "$RSUDO_USER" ]
  then
    # if user is not stored, it is intentionally wanted set it to current user
    log_info "rsudo: empty RSUDO_USER, setting it to '$USER'"
    RSUDO_USER="$USER"
  fi

  # unset RSUDO_PASSWORD ### DEBUG prevents reusing exported env
  if [ -z "$RSUDO_PASSWORD" ]
  then
    if [ "$RSUDO_ASKPASS" = "true" ] && [ ! -t 0 ]
    then
      log_debug "read pass from pipe"
      # read not interactively from stdin (pipe attached)
      read -r RSUDO_PASSWORD
      # TODO DEBUG check verify that pipe is closed if no other input
      if [ -t 0 ]
      then
        log_debug "pipe closed after readin password (no more input)"
      else
        log_debug "pipe still open after reading password - showing cat"
        cat
      fi
    else
      # read from tty interactively (user input)
      log_debug "read pass from tty"
      RSUDO_PASSWORD="$(readpass "[rsudo] Enter password for ${RSUDO_USER}@${RSUDO_HOST}:" < /dev/tty)"
    fi
  fi

  if [ -z "$RSUDO_PASSWORD" ]
  then
    log_debug "rsudo: empty RSUDO_PASSWORD"
    exit 1
  fi

  log_debug "rsudo: RSUDO_HOST=$RSUDO_HOST | RSUDO_USER=$RSUDO_USER"
  log_trace "rsudo: RSUDO_HOST=$RSUDO_HOST | RSUDO_USER=$RSUDO_USER | RSUDO_PASSWORD=$RSUDO_PASSWORD"
  log_trace "rsudo: args=$@"

  rsudo_module_execute "$@"
}

#------------------------------------------------------------------------------

rsudo_module_execute()
{
  # check first arg to execute rsudo or submodule

  # if command -v "rsudo-${1}" > /dev/null
  if command -v "rsudo-${1}"
  then
  log_trace "rsudo-${1} ### rsudo-$@"
  exit 55
    . "rsudo-${1}"
    rsudo-"$@"
  else
    rsudo "$@"
  fi
}

#------------------------------------------------------------------------------

rsudo_main_retrieve_connection_args_and_call_rsudo_module_execute "$@"
