#include "service.h"

//SERVICE_METHOD_DISPATCHER(Service)
//  SERVICE_REGISTER_METHOD_BY_ID_BEGIN
//  SERVICE_REGISTER_METHOD_BY_ID(start)
//  SERVICE_REGISTER_METHOD_BY_ID(stop)
//  SERVICE_REGISTER_METHOD_BY_ID(create)
//  SERVICE_REGISTER_METHOD_BY_ID(destroy)
//  SERVICE_REGISTER_METHOD_BY_ID_END
//  SERVICE_REGISTER_METHOD(start)
//  SERVICE_REGISTER_METHOD(stop)
//  SERVICE_REGISTER_METHOD(create)
//  SERVICE_REGISTER_METHOD(destroy)
//SERVICE_METHOD_DISPATCHER_END
