#!/bin/sh

#------------------------------------------------------------------------------

log()
{
  echo "RSCMD-db $(date +"[%Y-%m-%d %H:%M:%S]")" "$@" 1>&2
}

#------------------------------------------------------------------------------

sql()
{
# (
  if [ -z "$1" ]
  then
    exit 1
  fi

  REMOTE_DB="$1"
  shift

  SQL_COMMAND="$@"

  if [ -z "$SQL_COMMAND" ]
  then
    execute_as postgres psql "$REMOTE_DB"
  else
    execute_as postgres psql "$REMOTE_DB" -c "$SQL_COMMAND"
  fi
# )
}

#------------------------------------------------------------------------------

getdb()
{
# (
  if [ -z "$1" ]
  then
    exit 1
  fi

  REMOTE_DB="$1"

  if [ ! -t 0 ]
  then
    cat
  fi

  execute_as postgres pg_dump "$REMOTE_DB"
# )
}

#------------------------------------------------------------------------------

putdb()
{
# (
  if [ -z "$1" ]
  then
    exit 1
  fi

  REMOTE_DB="$1"
  LOCAL_PATH="$2"

  if [ -z "$LOCAL_PATH" ] && [ -t 0 ]
  then
    exit 1
  fi

  # sql "" "SELECT pg_terminate_backend(pg_stat_activity.procid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$REMOTE_DB' AND procid <> pg_backend_pid();" 1>/dev/null 2>/dev/null
  # sql "" "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$REMOTE_DB' AND pid <> pg_backend_pid();" 1>/dev/null 2>/dev/null
  execute service postgresql restart
  execute_as postgres dropdb "$REMOTE_DB"
  # execute_as postgres dropdb "$REMOTE_DB" 1>/dev/null 2>/dev/null
  # execute_as postgres dropdb --if-exists "$REMOTE_DB" 1>/dev/null 2>/dev/null

  if [ -z "$LOCAL_PATH" ]
  then
    shell_as postgres "createdb '$REMOTE_DB' && psql '$REMOTE_DB'"
  else
    cat "$LOCAL_PATH" | shell_as postgres "createdb '$REMOTE_DB' && psql '$REMOTE_DB'"
  fi
# )
}

#------------------------------------------------------------------------------

"$@"
