#!/bin/sh

. log.lib.sh

#------------------------------------------------------------------------------

sql()
{
# (
  if [ -z "$1" ]
  then
    exit 1
  fi

  REMOTE_DB="$1"
  shift

  SQL_COMMAND="$@"

  export RSUDO_AS_USER="postgres"
  if [ -z "$SQL_COMMAND" ]
  then
    rsudo psql "$REMOTE_DB"
  else
    rsudo psql "$REMOTE_DB" -c "$SQL_COMMAND"
  fi
# )
}

#------------------------------------------------------------------------------

getdb()
{
# (
  if [ -z "$1" ]
  then
    exit 1
  fi

  REMOTE_DB="$1"

  if [ ! -t 0 ]
  then
    cat
  fi

  export RSUDO_AS_USER="postgres"
  rsudo pg_dump "$REMOTE_DB"
# )
}

#------------------------------------------------------------------------------

putdb()
{
# (
  if [ -z "$1" ]
  then
    exit 1
  fi

  REMOTE_DB="$1"
  LOCAL_PATH="$2"

  if [ -z "$LOCAL_PATH" ] && [ -t 0 ]
  then
    exit 1
  fi

  # sql "" "SELECT pg_terminate_backend(pg_stat_activity.procid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$REMOTE_DB' AND procid <> pg_backend_pid();" 1>/dev/null 2>/dev/null
  # sql "" "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$REMOTE_DB' AND pid <> pg_backend_pid();" 1>/dev/null 2>/dev/null
  rsudo systemctl restart postgresql
  export RSUDO_AS_USER="postgres"
  rsudo dropdb "$REMOTE_DB"
  # execute_as postgres dropdb "$REMOTE_DB" 1>/dev/null 2>/dev/null
  # execute_as postgres dropdb --if-exists "$REMOTE_DB" 1>/dev/null 2>/dev/null


  if [ -z "$LOCAL_PATH" ]
  then
    sh -c "createdb '$REMOTE_DB' && psql '$REMOTE_DB'"
  else
    cat "$LOCAL_PATH" | sh -c "createdb '$REMOTE_DB' && psql '$REMOTE_DB'"
  fi
# )
}

#------------------------------------------------------------------------------

"$@"
