#!/bin/sh

# rssh: start a rsudo interactive shell
# rssh $commands: execute $commands (eg. eval "commands string", . $script $args) and keeps the shell open
# echo "$commands" | rssh or rssh [heredoc]: executes $commands or heredoc and exits
# NB executing (and not sourcing) a script or launching a shell, loses availability of rsudo functions

# bash --init-file "$(command -v "rsudo.lib.sh")" -i "$@"

if [ -z "$RSSH" ]
then
  . arg.lib.sh

  export RSSH="true"
  export RSSH_ARGS="$(saveargs "$@")"

  # RSSH="true" bash --init-file "$(command -v "rssh")" -i
  bash --init-file "$0" -i
  exit "$?"
fi

. rsudo.lib.sh

LOG_PROC_NAME="rssh"

log_debug "RSSH init args step 0: $@ - RSSH_ARGS=$RSSH_ARGS"
eval "set -- $RSSH_ARGS"

log_debug "RSSH init args: $@ - RSSH_ARGS=$RSSH_ARGS"

"$@"
