#!/bin/sh

# loads rsudo lib and optionally file arguments are decoded and loaded, then start a new shell with the constructed environment

. log.lib.sh
. rsudoenv.lib.sh

#------------------------------------------------------------------------------

log_info "RSUDO SHELL - START"

while [ "$#" -gt "0" ]
do
  rsudoenv load "$1"
  shift
done

bash

log_info "RSUDO SHELL - END"
