#!/bin/sh

. log.lib.sh

if [ "$1" = "--" ]
then
  MODULE="core"
  shift
elif [ "${1#--}" != "$1" ]
then
  MODULE="${1#--}"
  shift
else
  MODULE="core"
fi

MODULE="${0}-${MODULE}"

if [ ! -f "$MODULE" ]
then
  log_fatal "module not found MODULE=$MODULE"
  exit 1
fi

"$MODULE" "$@"
