#!/bin/sh

# loads rsudo lib and optionally file arguments are decoded and loaded, then start a new shell with the constructed environment

. log.lib.sh
. rsudo.lib.sh

#------------------------------------------------------------------------------

log_info "RSUDO SHELL - START"

rsudoenv load "$@"

bash

log_info "RSUDO SHELL - END"
