#!/bin/sh

# needs the following env vars to be defined outside and exported
# RSUDO_HOST
# RSUDO_USER
# RSUDO_PASSWORD
# RSUDO_AS_USER
#
# rsudo no args, no pipe -> interactive session
# rsudo args or pipe -> choose int or not int
# => 2 different commands

. log.lib.sh

# the following lines are executed when ssh uses SSH_ASKPASS command
# maximum security is guaranteed because explicit check that caller process is ssh and
# more importantly RSUDO_PASSWORD environment variable is available only in the rsudo process tree
if [ "$(ps -o "comm=" -p "$PPID")" = "ssh" ]
then
  echo "$RSUDO_PASSWORD"
  log_debug "rsudo askpass called by ssh! RSUDO_PASSWORD availability=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no")"
  exit 0
fi

#------------------------------------------------------------------------------

if [ -z "$RSUDO_HOST" ] || [ -z "$RSUDO_USER" ] || [ -z "$RSUDO_PASSWORD" ]
then
  log_fatal "HOST=$RSUDO_HOST - USER=$RSUDO_USER - RSUDO_PASSWORD(availability)=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no")"
  exit 1
fi

log_info "RSUDO STARTED: HOST=$RSUDO_HOST - USER=$RSUDO_USER - RSUDO_PASSWORD(availability)=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no") - AS_USER=$RSUDO_AS_USER - COMMAND=$@"

# export DISPLAY=":0.0"
export SSH_ASKPASS="${0}"
export SSH_ASKPASS_REQUIRE="force"

if [ -t 0 ] && [ "$#" -eq "0" ]
then
  log_info "rsudo starting interactive session"

  ssh -t -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" bash -ic "\"echo '$RSUDO_PASSWORD' | sudo -S --prompt='' -- true; sudo su; exit\""
  EXIT_CODE="$?"

  log_info "RSUDO ENDED: HOST=$RSUDO_HOST - USER=$RSUDO_USER"

  exit "$EXIT_CODE"
else
  log_info "rsudo starting NOT interactive session"

  SUDO_COMMAND="sudo"
  if [ -n "$RSUDO_AS_USER" ]
  then
    SUDO_COMMAND="$SUDO_COMMAND --user=\"$RSUDO_AS_USER\""
  fi
  log_info "SUDO_COMMAND=$SUDO_COMMAND"

  if [ -t 0 ]
  then
    RSUDO_PIPE="echo \"$RSUDO_PASSWORD\""
  else
    RSUDO_PIPE="(echo \"$RSUDO_PASSWORD\"; cat)"
  fi

  RSUDO_SSH_COMMANDS="$(cat << VAR; cat << 'EOF'
  echo "inside RSUDO_SSH_COMMANDS not executed and i don't now why"
  RSUDO_PASSWORD="$RSUDO_PASSWORD"
  SUDO_COMMAND="$SUDO_COMMAND"
  RSUDO_PIPE="$RSUDO_PIPE"
  set -- $@
VAR
  echo "RSUDO_PASSWORD=$RSUDO_PASSWORD - SUDO_COMMAND=$SUDO_COMMAND - RSUDO_PIPE=$RSUDO_PIPE - args=$@"
  if sudo -n true 1>/dev/null 2>/dev/null
  then
    $SUDO_COMMAND -- "$@"
  else
    $RSUDO_PIPE | $SUDO_COMMAND -S --prompt='' -- true
    # sudo su
    $SUDO_COMMAND "$@"
    # $RSUDO_PIPE | $SUDO_COMMAND -S --prompt='' -- bash -ic "$@"
    # $RSUDO_PIPE | $SUDO_COMMAND -S --prompt='' -- "$@"
  fi
EOF
)"

  echo "RSUDO_SSH_COMMANDS=$RSUDO_SSH_COMMANDS"

  ssh -tt -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" sh -ic "$RSUDO_SSH_COMMANDS"
fi

#------------------------------------------------------------------------------
