#!/bin/sh

#------------------------------------------------------------------------------

log()
{
  echo "$(date +"[%Y-%m-%d %H:%M:%S]")" "$@"
#  echo "$(date +"[%Y-%m-%d %H:%M:%S]")" "$@" 1>&2
}

#------------------------------------------------------------------------------

copy_name()
{
  eval "HOST_$2=\"\$HOST_$1\""
  eval "USER_$2=\"\$USER_$1\""
  eval "PASS_$2=\"\$PASS_$1\""

#  eval "log \"HOST_$2=\$HOST_$2 | USER_$2=\$USER_$2 | PASS_$2=\$PASS_$2\""
}

#------------------------------------------------------------------------------

resolve_name()
{
  if [ -z "$1" ]
  then
    log "resolve_name: empty name"
    exit 1
  fi

  eval "REMOTE_HOST=\"\$HOST_$1\""
  eval "REMOTE_USER=\"\$USER_$1\""
  eval "export RSUDO_PASSWORD=\"\$PASS_$1\""

  log "resolve_name: REMOTE_HOST=$REMOTE_HOST | REMOTE_USER=$REMOTE_USER"
#  log "resolve_name: REMOTE_HOST=$REMOTE_HOST | REMOTE_USER=$REMOTE_USER | RSUDO_PASSWORD=$RSUDO_PASSWORD"
}

#------------------------------------------------------------------------------

rsn()
(
  resolve_name "$1"
  shift

  if [ -z "$1" ]
  then
    log "rsn: empty command"
    exit 1
  fi

  COMMAND="$1"
  shift

  rsudo "$COMMAND" "$REMOTE_HOST" "$REMOTE_USER" "$@"
)

#------------------------------------------------------------------------------

rse()
{
  if [ -z "$1" ]
  then
    log "rse: empty command"
    exit 1
  fi

  COMMAND="$1"
  shift

  rsudo "$COMMAND" "$REMOTE_HOST" "$REMOTE_USER" "$@"
}

#------------------------------------------------------------------------------

if [ "${0##*/}" = "rsudo-ctl" ]
then
  rsn "$@"
fi
