#!/bin/sh

# needs the following env vars to be defined outside and exported
# RSUDO_HOST
# RSUDO_USER
# RSUDO_PASSWORD
# RSUDO_AS_USER

#------------------------------------------------------------------------------

log()
{
  echo "$(date +"[%Y-%m-%d %H:%M:%S]")" "$@" 1>&2
}

#------------------------------------------------------------------------------

# the following lines are executed when ssh uses SSH_ASKPASS command
# maximum security is guaranteed because explicit check that caller process is ssh and
# more importantly RSUDO_PASSWORD environment variable is available only in the rsudo process tree
if [ "$(ps -o "comm=" -p "$PPID")" = "ssh" ]
then
  echo "$RSUDO_PASSWORD"
  log "rsudo askpass called by ssh! RSUDO_PASSWORD availability=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no")"
  exit 0
fi

#------------------------------------------------------------------------------

ssh_interactive()
{
  ssh -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "$@"
  return "$?"
}

#------------------------------------------------------------------------------

ssh_detached()
{
  export DISPLAY=":0.0"
  export SSH_ASKPASS="${0}"

  setsid ssh -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "$@"

  return "$?"
}

#------------------------------------------------------------------------------

if [ -z "$RSUDO_HOST" ] || [ -z "$RSUDO_USER" ] || [ -z "$RSUDO_PASSWORD" ]
then
  exit 1
fi

log "RSUDO STARTED: PID=$$ - HOST=$RSUDO_HOST - USER=$RSUDO_USER - RSUDO_PASSWORD(availability)=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no") - AS_USER=$RSUDO_AS_USER - COMMAND=$@"

if [ "$#" -eq "0" ] || [ -z "$*" ]
then
  log "rsudo no args"
  if [ -t 0 ]
  then
    log "rsudo no args + in/out attached to terminal and not pipes"
    exit 1
  fi

  log "rsudo no args -> set command as /bin/sh -s (execute stream commands)"
  set -- /bin/sh -s
  log "RSUDO: no args + non interactive term => attached to pipe or file -> get commands through stdin COMMAND=$@"
fi

ssh_detached sudo -K\; sudo -n true 1>/dev/null 2>/dev/null
RSUDO_NO_PASS_NEED="$?"

RSUDO_SSH_COMMAND_PREFIX=""
if [ "$RSUDO_NO_PASS_NEED" != "0" ] || [ -n "$RSUDO_AS_USER" ]
then
  RSUDO_SSH_COMMAND_PREFIX="sudo"
  if [ "$RSUDO_NO_PASS_NEED" != "0" ]
  then
    RSUDO_SSH_COMMAND_PREFIX="$RSUDO_SSH_COMMAND_PREFIX -S --prompt=''"
  fi
  if [ -n "$RSUDO_AS_USER" ]
  then
    RSUDO_SSH_COMMAND_PREFIX="$RSUDO_SSH_COMMAND_PREFIX --user=\"$RSUDO_AS_USER\""
  fi
  RSUDO_SSH_COMMAND_PREFIX="$RSUDO_SSH_COMMAND_PREFIX --"
fi

log "RSUDO: SSH_COMMAND_PREFIX=$RSUDO_SSH_COMMAND_PREFIX"

if [ "$RSUDO_NO_PASS_NEED" = "0" ]
then
  ssh_detached "$RSUDO_SSH_COMMAND_PREFIX" "$@"
else
  # echo password to sudo and if terminal is not interactive, reattach stdin
  (echo "$RSUDO_PASSWORD"; [ ! -t 0 ] && cat) | ssh_detached "$RSUDO_SSH_COMMAND_PREFIX" "$@"
fi

log "RSUDO ENDED: PID=$$ - HOST=$RSUDO_HOST - USER=$RSUDO_USER"

#------------------------------------------------------------------------------
