#!/bin/sh

. rsudo.lib.sh
. realpaths.lib.sh
. waituser.lib.sh

realpaths

rsudoenv load rsudo-env.enc

. rsudo-env.conf
. rsudo-lib.sh

cp "$THIS_DIR/rsudo-cmd.sh" "/tmp/rsudo-cmd.$$.sh"
xdg-open "/tmp/rsudo-cmd.$$.sh" 1>/dev/null 2>/dev/null
wait_continue
. "/tmp/rsudo-cmd.$$.sh"
rm -f "/tmp/rsudo-cmd.$$.sh"

waituser
