#!/bin/sh

. log.lib.sh

if [ "$(ps -o "comm=" -p "$PPID")" = "ssh" ]
then
  [ ! -t 0 ] && read -r RSUDO_PASSWORD
  echo "$RSUDO_PASSWORD"
  log_debug "rsudo askpass called by ssh! RSUDO_PASSWORD $([ -n "$RSUDO_PASSWORD" ] && echo "is not null" || echo "is null")"
else
  log_fatal "security checkfailed!"
  exit 1
fi
