#!/bin/sh

. log.lib.sh

log_debug "rsudo askpass called! ...checking if caller is ssh! RSUDO_PASSWORD $([ -n "$RSUDO_PASSWORD" ] && echo "is exported and not null" || echo "is null")"
if [ "$(ps -o "comm=" -p "$PPID")" = "ssh" ]
then
  if [ -t 0 ]
  then
    if [ -n "$RSUDO_FIFO" ]
    then
      exec 0<"$RSUDO_FIFO"
    else
      log_fatal "wrong rsudo-askpass method"
      exit 1
    fi
  fi

  read -r RSUDO_PASSWORD
  echo "$RSUDO_PASSWORD"

  log_debug "rsudo askpass called by ssh! RSUDO_PASSWORD read and $([ -n "$RSUDO_PASSWORD" ] && echo "is not null" || echo "is null")"
  # log_trace "RSUDO_PASSWORD=$RSUDO_PASSWORD"

  if [ -z "$RSUDO_PASSWORD" ]
  then
    log_fatal "password is null!"
    exit 1
  fi
else
  log_fatal "security checkfailed!"
  exit 1
fi
