#!/bin/sh

#------------------------------------------------------------------------------

log()
{
  echo "$(date +"[%Y-%m-%d %H:%M:%S]")" "$@" 1>&2
}

#------------------------------------------------------------------------------

if [ -z "$RSUDO_PASSWORD" ]
then
  exit 1
fi

if [ "$#" -eq 1 ]
then
  echo "$RSUDO_PASSWORD"
  log "askpass called -> RSUDO_PASSWORD=$RSUDO_PASSWORD"
  log ARGS="$@"
  log NARGS="$#"
  exit 0
fi

if [ -z "$RSUDO_HOST" ]
then
  exit 1
fi

if [ -z "$RSUDO_USER" ]
then
  exit 1
fi

export DISPLAY=":0.0"
export SSH_ASKPASS="$0"

log RSUDO_COMMAND="$@"

if [ "$#" -eq "0" ] || [ -z "$*" ]
then
  if [ -t 0 ]
  then
    exit 1
  fi

  set -- /bin/sh -s
fi

for k in "$@"
do
  shift
  set -- "$@" \""$k"\"
done

setsid ssh -n -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" sudo -K\; sudo -n true 1>/dev/null 2>/dev/null
SUDO_NO_PASS="$?"

if [ -z "$EXECUTE_AS" ]
then
  if [ "$RSUDO_USER" = "root" ]
  then
    RSUDO_SSH_COMMAND=""
  elif [ "$SUDO_NO_PASS" = "0" ]
  then
    RSUDO_SSH_COMMAND="sudo --"
  else
    RSUDO_SSH_COMMAND="sudo -S --prompt='' --"
  fi
else
  if [ "$RSUDO_USER" = "root" ] || [ "$SUDO_NO_PASS" = "0" ]
  then
    RSUDO_SSH_COMMAND="sudo --user=\"$EXECUTE_AS\" --"
  else
    RSUDO_SSH_COMMAND="sudo -S --prompt='' --user=\"$EXECUTE_AS\" --"
  fi
fi
# RSUDO_SSH_COMMAND="pwd 1>&2; cd /; $RSUDO_SSH_COMMAND"
RSUDO_SSH_COMMAND="pwd 1>&2; $RSUDO_SSH_COMMAND"
log "RSUDO_SSH_COMMAND=$RSUDO_SSH_COMMAND"

if [ "$SUDO_NO_PASS" = "0" ]
then
  log "no password provided to sudo"
  setsid ssh -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "$RSUDO_SSH_COMMAND" "$@"
else
  log "password provided to sudo"
  (echo "$RSUDO_PASSWORD"; [ ! -t 0 ] && cat) | setsid ssh -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "$RSUDO_SSH_COMMAND" "$@"
fi

#------------------------------------------------------------------------------
