#!/bin/sh

# rsudox $connection_args $rsudo_args - resolves $connection_args and executes proper rsudo or rsudo-* command without changing current env

. rsudo.lib.sh

rsudoenv_get "$1"
shift

# if command -v "rsudo-${1}" > /dev/null
if command -v "rsudo-${1}"
then
  rsudo-"$@"
else
  rsudo "$@"
fi
