#!/bin/sh

# loads rsudo lib and optionally file arguments are decoded and loaded, then start a new shell with the constructed environment

. rsudo.lib.sh

#------------------------------------------------------------------------------

while [ "$#" -gt "0" ]
do
  rsudoenv load "$1"
  shift
done

bash
