#!/bin/sh

# args: host user rsudo_args
# always asks for password, sets environment vars and the executes rsudo with rsudo_args

#------------------------------------------------------------------------------

log()
{
  echo "$(date +"[%Y-%m-%d %H:%M:%S]")" "$@" 1>&2
}

#------------------------------------------------------------------------------

log COMMAND_LINE="$@"

export RSUDO_HOST="$1"
shift

log RSUDO_HOST="$RSUDO_HOST"

export RSUDO_USER="$1"
shift

log RSUDO_USER="$RSUDO_USER"

log COMMAND_PARAMETERS="$@"

if [ -t 0 ]
then
  echo "[rsudo] Enter password for ${RSUDO_USER}@${RSUDO_HOST}:" 1>&2
  stty -echo
  read -r RSUDO_PASSWORD
  stty echo
else
  read -r RSUDO_PASSWORD
fi

if [ -z "$RSUDO_PASSWORD" ]
then
  log "password cannot be empty"
  exit 1
fi

export RSUDO_PASSWORD

rsudo "$@"
