#!/bin/sh

. log.lib.sh

log_trace "exported RSUDO_PASSWORD=$RSUDO_PASSWORD - reading from pipe..."
# tty >&2
if [ "$(ps -o "comm=" -p "$PPID")" = "ssh" ]
then
  # [ ! -t 0 ] && read -r RSUDO_PASSWORD

  # if [ -z "$RSUDO_ASKPASS_METHOD" ]
  # then
  #   read -r RSUDO_PASSWORD
  # elif [ "$RSUDO_ASKPASS_METHOD" = "fifo" ]
  # then
  #   true
  # else
  #   log_fatal "wrong RSUDO_ASKPASS_METHOD=$RSUDO_ASKPASS_METHOD"
  #   exit 1
  # fi

  rdpid="$(ps -o "ppid=" -p "$PPID")"
  log_trace "rdpid=$rdpid - RSUDO_PID=$RSUDO_PID"
  # ls -la /proc/$RSUDO_PID/fd/ 1>&2
  # ls -la /proc/$PPID/fd/ 1>&2
  # ls -la /proc/$$/fd/ 1>&2
  # exec 0</proc/$$/fd/5
  # exec 0</proc/$RSUDO_PID/fd/3
  exec 0<"$RSUDO_FIFO"
  read -r RSUDO_PASSWORD
  echo "$RSUDO_PASSWORD"
  log_debug "rsudo askpass called by ssh! RSUDO_PASSWORD $([ -n "$RSUDO_PASSWORD" ] && echo "is not null" || echo "is null")"
  log_trace "RSUDO_PASSWORD=$RSUDO_PASSWORD"

  # if [ -t 0 ]
  # then
  #   log_fatal "terminal attached!"
  #   exit 1
  # fi
  #
  # if [ -z "$RSUDO_PASSWORD" ]
  # then
  #   log_fatal "password is null!"
  #   exit 1
  # fi
else
  log_fatal "security checkfailed!"
  exit 1
fi
