#!/bin/sh

#------------------------------------------------------------------------------

log()
{
  echo "$(date +"[%Y-%m-%d %H:%M:%S]")" "$@" 1>&2
}

#------------------------------------------------------------------------------

log COMMAND_LINE="$@"

export RSUDO_HOST="$1"
shift
log RSUDO_HOST="$RSUDO_HOST"

export RSUDO_USER="$1"
shift
log RSUDO_USER="$RSUDO_USER"

log COMMAND_PARAMETERS="$@"

if [ -z "$RSUDO_PASSWORD" ]
then
  if [ -t 0 ]
  then
    echo "[rsudo] Enter password for ${RSUDO_USER}@${RSUDO_HOST}:" 1>&2
    stty -echo
    read -r RSUDO_PASSWORD
    stty echo
  else
    read -r RSUDO_PASSWORD
  fi
  export RSUDO_PASSWORD
fi

rsudo "$@"
