#!/bin/sh

# args: host user rsudo_args
# always asks for password, sets environment vars and the executes rsudo with rsudo_args

. log.lib.sh
. rsudoenv.lib.sh

#------------------------------------------------------------------------------

log_info COMMAND_LINE="$@"

export RSUDO_HOST="$1"
shift

log_info RSUDO_HOST="$RSUDO_HOST"

export RSUDO_USER="$1"
shift

log_info RSUDO_USER="$RSUDO_USER"

log_info COMMAND_PARAMETERS="$@"

RSUDO_PASSWORD="$(readpass "[rsudo] Enter password for ${RSUDO_USER}@${RSUDO_HOST}:")"

if [ -z "$RSUDO_PASSWORD" ]
then
  log_fatal "password cannot be empty"
  exit 1
fi

export RSUDO_PASSWORD

rsudo "$@"
