#!/bin/sh

# needs the following env vars to be defined outside and exported

# required:
# RSUDO_HOST
# RSUDO_USER
# RSUDO_PASSWORD

# optional:
# RSUDO_AS_USER
# RSUDO_INTERACTIVE

. log.lib.sh

# the following lines are executed when ssh uses SSH_ASKPASS command
# maximum security is guaranteed because explicit check that caller process is ssh and
# more importantly RSUDO_PASSWORD environment variable is available only in the rsudo process tree
if [ "$(ps -o "comm=" -p "$PPID")" = "ssh" ]
then
  echo "$RSUDO_PASSWORD"
  log_debug "rsudo askpass called by ssh! RSUDO_PASSWORD availability=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no")"
  exit 0
fi

#------------------------------------------------------------------------------

# RSUDO_PASSWORD can be provided by exporting env var (insecure) or by echoing to pipe (secure, like sudo)
if [ -z "$RSUDO_PASSWORD" ]
then
  if [ -t 0 ]
  then
    log_fatal "RSUDO_PASSWORD is empty and not provided by stdin"
    exit 1
  else
    read -r RSUDO_PASSWORD
    export RSUDO_PASSWORD
  fi
fi

if [ -z "$RSUDO_HOST" ] || [ -z "$RSUDO_USER" ] || [ -z "$RSUDO_PASSWORD" ]
then
  log_fatal "HOST=$RSUDO_HOST - USER=$RSUDO_USER - RSUDO_PASSWORD(availability)=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no")"
  exit 1
fi

log_info "RSUDO STARTED: HOST=$RSUDO_HOST - USER=$RSUDO_USER - RSUDO_PASSWORD(availability)=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no") - AS_USER=$RSUDO_AS_USER - COMMAND=$@"

# export DISPLAY=":0.0"
export SSH_ASKPASS="${0}"
export SSH_ASKPASS_REQUIRE="force"

if [ "$#" -eq "0" ] || [ -z "$*" ]
then
  log_trace "rsudo no args"
  if [ -t 0 ]
  then
    log_info "rsudo starting interactive session"

    RSUDO_INTERACTIVE="true"
    set -- su
  else
    log_trace "rsudo no args -> set command as /bin/sh -s (execute stream commands)"
    set -- /bin/sh -s
    log_debug "RSUDO: no args + non interactive term => attached to pipe or file -> get commands through stdin COMMAND=$@"
  fi
else
  true
  # for k in "$@"
  # do
  #   shift
  #   set -- "$@" \""$k"\"
  # done
fi

if [ -n "$RSUDO_AS_USER" ]
then
  SUDO_AS_USER="--user=\"$RSUDO_AS_USER\""
fi

if [ -t 0 ]
then
  RSUDO_PIPE="echo \"$RSUDO_PASSWORD\""
else
  RSUDO_PIPE="(echo \"$RSUDO_PASSWORD\"; cat)"
fi

# not interactive: echo pass; cat if pipe | ssh sudo -S sh -c args
#     interactive: echo pass; cat if pipe | ssh sh -c 'sudo -S true; sudo args'
# SUDO_COMMAND="'$RSUDO_PIPE | sudo -S --prompt='' $SUDO_AS_USER -- \"$@\"'"
# SUDO_COMMAND="'$RSUDO_PIPE | sudo -S --prompt='' $SUDO_AS_USER -- $@'"
SUDO_COMMAND="'$RSUDO_PIPE | sudo -S --prompt='' $SUDO_AS_USER -- sh -c ''$@'' '"
if [ "$RSUDO_INTERACTIVE" = "true" ]
then
  # SSH_INTERACTIVE_SWITCH="-tt"
  SSH_INTERACTIVE_SWITCH="-t"
  SH_INTERACTIVE_SWITCH="-i"
  # SUDO_COMMAND="'echo \"$RSUDO_PASSWORD\" | sudo -S --prompt='' -- true; sudo $SUDO_AS_USER -- \"$@\"'"
  SUDO_COMMAND="'echo \"$RSUDO_PASSWORD\" | sudo -S --prompt='' -- true; sudo $SUDO_AS_USER -- $@'"
fi

# RSUDO_SSH_COMMANDS="$(cat << VAR; cat << 'EOF'
#   true
#   RSUDO_PASSWORD="$RSUDO_PASSWORD"
#   SUDO_AS_USER="$SUDO_AS_USER"
#   RSUDO_PIPE="$RSUDO_PIPE"
#   set -- $@
# VAR
# echo "RSUDO_PASSWORD=$RSUDO_PASSWORD - SUDO_AS_USER=$SUDO_AS_USER - RSUDO_PIPE=$RSUDO_PIPE - args=$@"
#   # echo "$RSUDO_PASSWORD" | sudo -S --prompt='' -- true
#   # sudo $SUDO_AS_USER -- "$@"
#   # echo "$RSUDO_PASSWORD" | sudo -S --prompt='' $SUDO_AS_USER -- "$@"
#   # build pipe command externally!!!
#   eval "$RSUDO_PIPE" | sudo -S --prompt='' $SUDO_AS_USER -- "$@"
# EOF
# )"

RSUDO_SSH_COMMANDS="$SUDO_COMMAND"
log_info "RSUDO_SSH_COMMANDS=$RSUDO_SSH_COMMANDS"

ssh $SSH_INTERACTIVE_SWITCH -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" sh $SH_INTERACTIVE_SWITCH -c "$RSUDO_SSH_COMMANDS"
EXIT_CODE="$?"

log_info "RSUDO ENDED: HOST=$RSUDO_HOST - USER=$RSUDO_USER"

exit "$EXIT_CODE"

#------------------------------------------------------------------------------
