#!/bin/sh

# needs the following env vars to be defined outside and exported
# RSUDO_HOST
# RSUDO_USER
# RSUDO_PASSWORD
# RSUDO_AS_USER

#------------------------------------------------------------------------------

log()
{
  echo "$(date +"[%Y-%m-%d %H:%M:%S]")" "$@" 1>&2
}

#------------------------------------------------------------------------------

if [ -z "$RSUDO_HOST" ] || [ -z "$RSUDO_USER" ] || [ -z "$RSUDO_PASSWORD" ]
then
  exit 1
fi

export DISPLAY=":0.0"
export SSH_ASKPASS="${0}.ap"

log RSUDO_COMMAND="$@"

if [ "$#" -eq "0" ] || [ -z "$*" ]
then
  log "rsudo no args"
  if [ -t 0 ]
  then
    log "rsudo no args + in/out attached to terminal and not pipes"
    exit 1
  fi

  log "rsudo no args -> set command as /bin/sh -s (execute stream commands)"
  set -- /bin/sh -s
fi

setsid ssh -n -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" sudo -K\; sudo -n true 1>/dev/null 2>/dev/null
RSUDO_NO_PASS_NEED="$?"

log RSUDO_NO_PASS_NEED="$RSUDO_NO_PASS_NEED"

RSUDO_COMMAND=""

if [ "$RSUDO_NO_PASS_NEED" != "0" ] || [ -n "$RSUDO_AS_USER" ]
then
  RSUDO_COMMAND="sudo"

  if [ "$RSUDO_NO_PASS_NEED" != "0" ]
  then
    RSUDO_COMMAND="$RSUDO_COMMAND -S --prompt=''"
  fi

  if [ -n "$RSUDO_AS_USER" ]
  then
    RSUDO_COMMAND="$RSUDO_COMMAND --user=\"$RSUDO_AS_USER\""
  fi

  RSUDO_COMMAND="$RSUDO_COMMAND --"
fi

log "RSUDO_COMMAND=$RSUDO_COMMAND"

if [ "$RSUDO_NO_PASS_NEED" = "0" ]
then
  log "no password provided to sudo"
  setsid ssh -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "$RSUDO_COMMAND" "$@"
else
  log "password provided to sudo"
  (echo "$RSUDO_PASSWORD"; [ ! -t 0 ] && cat) | setsid ssh -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "$RSUDO_COMMAND" "$@"
fi

#------------------------------------------------------------------------------
