#!/bin/sh

# rsudo no args, no pipe -> interactive session
# rsudo args or pipe -> choose int or not int
# => 2 different commands

# check if called by ssh as askpass program
# check if required env variables are set
# export ssh askpass variables
# check if interactive by args, pipe and set args
# check if interactive by explicit request by env vars and set vars for switches and args
# set sudo command var with or without user
# check if pipe is attached and set proper pipe vars
# set ssh multiline command with vars exported
# call ssh

# needs the following env vars to be defined outside and exported
# RSUDO_HOST
# RSUDO_USER
# RSUDO_PASSWORD
# RSUDO_AS_USER

. log.lib.sh

# the following lines are executed when ssh uses SSH_ASKPASS command
# maximum security is guaranteed because explicit check that caller process is ssh and
# more importantly RSUDO_PASSWORD environment variable is available only in the rsudo process tree
if [ "$(ps -o "comm=" -p "$PPID")" = "ssh" ]
then
  echo "$RSUDO_PASSWORD"
  log_debug "rsudo askpass called by ssh! RSUDO_PASSWORD availability=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no")"
  exit 0
fi

#------------------------------------------------------------------------------

ssh_command_1()
{
  setsid ssh -n -o 'StrictHostKeyChecking no' -l "$REMOTE_USER" "$REMOTE_HOST" sudo -K\; sudo -n true 1>/dev/null 2>/dev/null
}

ssh_command_2()
{
  # ssh -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST"
  # ssh -t -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "RSUDO_PASSWORD=\"$RSUDO_PASSWORD\"" bash
  # ssh -t -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "RSUDO_PASSWORD=\"$RSUDO_PASSWORD\" bash"
  # ssh -t -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "R=\"echo '$RSUDO_PASSWORD' | sudo -S --prompt='' -- true; sudo su; exit\" bash"
  # ssh -t -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "R=\"echo '$RSUDO_PASSWORD' | sudo -S --prompt='' -- true; sudo su; exit\" bash -ic 'eval \$R'"
  # ssh -t -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "bash -ic 'echo '$RSUDO_PASSWORD' | sudo -S --prompt='' -- true; sudo su; exit'"

  ssh -t -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" bash -ic "\"echo '$RSUDO_PASSWORD' | sudo -S --prompt='' -- true; sudo su; exit\""
  # ssh -t -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" bash -ic "\"echo '$RSUDO_PASSWORD' | sudo -S --prompt='' -- true; sudo top; exit\""
}

ssh_command_3()
{
  ssh -t -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "$RSUDO_SSH_COMMAND_PREFIX" "$@"
}

ssh_command_4()
{
  ssh -t -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" "$RSUDO_SSH_COMMAND_PREFIX" "$@"
}

#------------------------------------------------------------------------------

if [ -z "$RSUDO_HOST" ] || [ -z "$RSUDO_USER" ] || [ -z "$RSUDO_PASSWORD" ]
then
  log_fatal "HOST=$RSUDO_HOST - USER=$RSUDO_USER - RSUDO_PASSWORD(availability)=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no")"
  exit 1
fi

log_info "RSUDO STARTED: HOST=$RSUDO_HOST - USER=$RSUDO_USER - RSUDO_PASSWORD(availability)=$([ -n "$RSUDO_PASSWORD" ] && echo "yes" || echo "no") - AS_USER=$RSUDO_AS_USER - COMMAND=$@"

# export DISPLAY=":0.0"
export SSH_ASKPASS="${0}"
export SSH_ASKPASS_REQUIRE="force"

if [ "$#" -eq "0" ] || [ -z "$*" ]
then
  log_trace "rsudo no args"
  if [ -t 0 ]
  then
    log_info "rsudo starting interactive session"

    RSUDO_INTERACTIVE="true"
    set -- su
  else
    log_trace "rsudo no args -> set command as /bin/sh -s (execute stream commands)"
    set -- /bin/sh -s
    log_debug "RSUDO: no args + non interactive term => attached to pipe or file -> get commands through stdin COMMAND=$@"
  fi
else
  for k in "$@"
  do
    shift
    set -- "$@" \""$k"\"
  done
fi

if [ "$RSUDO_INTERACTIVE" = "true" ]
then
  SSH_INTERACTIVE_SWITCH="-tt"
  SH_INTERACTIVE_SWITCH="-i"
fi

if [ -n "$RSUDO_AS_USER" ]
then
  SUDO_AS_USER="--user=\"$RSUDO_AS_USER\""
fi

RSUDO_SSH_COMMANDS="$(cat << VAR; cat << 'EOF'
  echo "inside RSUDO_SSH_COMMANDS not executed and i don't now why"
  RSUDO_PASSWORD="$RSUDO_PASSWORD"
  SUDO_AS_USER="$SUDO_AS_USER"
  RSUDO_PIPE="$RSUDO_PIPE"
  set -- $@
VAR
echo "RSUDO_PASSWORD=$RSUDO_PASSWORD - SUDO_AS_USER=$SUDO_AS_USER - RSUDO_PIPE=$RSUDO_PIPE - args=$@"
  echo "$RSUDO_PASSWORD" | sudo -S --prompt='' -- true
  # sudo su
  sudo $SUDO_AS_USER -- "$@"
EOF
)"

log_info "RSUDO_SSH_COMMANDS=$RSUDO_SSH_COMMANDS"

ssh $SSH_INTERACTIVE_SWITCH -o 'StrictHostKeyChecking no' -l "$RSUDO_USER" "$RSUDO_HOST" sh $SH_INTERACTIVE_SWITCH -c "$RSUDO_SSH_COMMANDS"
EXIT_CODE="$?"

log_info "RSUDO ENDED: HOST=$RSUDO_HOST - USER=$RSUDO_USER"

exit "$EXIT_CODE"

#------------------------------------------------------------------------------
