#!/bin/sh

VERSION="0.1.2"
DOWNLOAD_URL="https://codeberg.org/derat/soundalike/releases/download/v${VERSION}/soundalike-${VERSION}-linux-amd64.tar.gz"
FILE_TYPE="tar.gz"
SYMLINKS="soundalike=soundalike"

postinstall()
(
  cd ./latest
  sudo chmod +x ./soundalike
)
